## Configuraciones y Carga de Archivos

### Importación de Librerías

In [1]:
import json
import smtplib
from datetime import datetime, timedelta
from email.message import EmailMessage

import pandas as pd
import pytz

### Carga de Archivos

Este módulo permite la carga de archivos en formato `.xlsx` y `.csv`. Tras la carga, se informará la cantidad de filas y columnas que contiene cada archivo.

**Archivos Requeridos:**

**Umbrella**
* `PQRSD_Formato_Servicios`
* `PR_Formato_Mes_SI`
* `GEN_Sitios_Activos_SI`
* `Lista de Categorias`
* `SI_LOG_API_CCC`
* `SI_log_Integracion_CCC_Resolution`
* `SI_log_Integracion_CCC`

**DataWifi**
* `CONTADORES TRAFICO`
* `CONTADORES VELOCIDAD`


**NetAdvisor**
* `LOG PQRSD` (Desde 01-05-2024 a fecha actual)

In [2]:
file_path_pqrsd_servicios = '/content/PQRSD_Formato_Servicios-2026-03-12.xlsx'

try:
    df_pqrsd_servicios = pd.read_excel(file_path_pqrsd_servicios)

    if df_pqrsd_servicios.empty:
        print(f"Advertencia: El archivo '{file_path_pqrsd_servicios}' se cargó, pero está vacío.")
    else:
        print(f"Archivo cargado exitosamente.")
        print(f"PQRSD Servicios: {df_pqrsd_servicios.shape}")

except FileNotFoundError:
    print(f"Error: No se encontró el archivo en la ruta: '{file_path_pqrsd_servicios}'.\n   -> Verifique que el nombre sea correcto y el archivo esté en la misma carpeta.")

except ValueError as e:
    print(f"Error de formato: El archivo no parece ser un Excel válido o está corrupto.\n   -> Detalle técnico: {e}")

except Exception as e:
    print(f"Error inesperado: Ocurrió un problema no contemplado.\n   -> Detalle: {e}")

Archivo cargado exitosamente.
PQRSD Servicios: (211780, 45)

In [3]:
file_path_paradas = '/content/PR_Formato_Mes_SI-2026-03-12.xlsx'

try:
    df_paradas = pd.read_excel(file_path_paradas)

    if df_paradas.empty:
        print(f"Advertencia: El archivo '{file_path_paradas}' se cargó, pero está vacío.")
    else:
        print(f"Archivo cargado exitosamente.")
        print(f"Paradas de Reloj: {df_paradas.shape}")

except FileNotFoundError:
    print(f"Error: No se encontró el archivo en la ruta: '{file_path_paradas}'.\n   -> Verifique que el nombre sea correcto y el archivo esté en la misma carpeta.")

except ValueError as e:
    print(f"Error de formato: El archivo no parece ser un Excel válido o está corrupto.\n   -> Detalle técnico: {e}")

except Exception as e:
    print(f"Error inesperado: Ocurrió un problema no contemplado.\n   -> Detalle: {e}")

Archivo cargado exitosamente.
Paradas de Reloj: (99222, 12)

In [4]:
file_path_sitios_activos = '/content/GEN_Sitios_Activos_SI-2026-03-12.xlsx'

try:
    df_sitios_activos = pd.read_excel(file_path_sitios_activos)

    if df_sitios_activos.empty:
        print(f"Advertencia: El archivo '{file_path_sitios_activos}' se cargó, pero está vacío.")
    else:
        print(f"Archivo cargado exitosamente.")
        print(f"Sitios Activos: {df_sitios_activos.shape}")

except FileNotFoundError:
    print(f"Error: No se encontró el archivo en la ruta: '{file_path_sitios_activos}'.\n   -> Verifique que el nombre sea correcto y el archivo esté en la misma carpeta.")

except ValueError as e:
    print(f"Error de formato: El archivo no parece ser un Excel válido o está corrupto.\n   -> Detalle técnico: {e}")

except Exception as e:
    print(f"Error inesperado: Ocurrió un problema no contemplado.\n   -> Detalle: {e}")

Archivo cargado exitosamente.
Sitios Activos: (6753, 46)

In [5]:
file_path_log_netadvisor = '/content/NetAdvisor 2026-03-12T13_32_10.935Z.csv'

try:
    df_log_netadvisor = pd.read_csv(file_path_log_netadvisor)

    if df_log_netadvisor.empty:
        print(f"Advertencia: El archivo '{file_path_log_netadvisor}' se cargó, pero está vacío.")
    else:
        print(f"Archivo cargado exitosamente.")
        print(f"Log NetAdvisor: {df_log_netadvisor.shape}")

except FileNotFoundError:
    print(f"Error: No se encontró el archivo en la ruta: '{file_path_log_netadvisor}'.\n   -> Verifique que el nombre sea correcto y el archivo esté en la misma carpeta.")

except ValueError as e:
    print(f"Error de formato: El archivo no parece ser un CSV válido o está corrupto.\n   -> Detalle técnico: {e}")

except Exception as e:
    print(f"Error inesperado: Ocurrió un problema no contemplado.\n   -> Detalle: {e}")

Archivo cargado exitosamente.
Log NetAdvisor: (126403, 10)

In [6]:
file_path_categorias = '/content/Listas Personalizadas Listado Categorias PQRS_2026-03-12_08-29-47.xlsx'

try:
    df_categorias_subcategorias = pd.read_excel(file_path_categorias)

    if df_categorias_subcategorias.empty:
        print(f"Advertencia: El archivo '{file_path_categorias}' se cargó, pero está vacío.")
    else:
        print(f"Archivo cargado exitosamente.")
        print(f"Categorías: {df_categorias_subcategorias.shape}")

except FileNotFoundError:
    print(f"Error: No se encontró el archivo en la ruta: '{file_path_categorias}'.\n   -> Verifique que el nombre sea correcto y el archivo esté en la misma carpeta.")

except ValueError as e:
    print(f"Error de formato: El archivo no parece ser un Excel válido o está corrupto.\n   -> Detalle técnico: {e}")

except Exception as e:
    print(f"Error inesperado: Ocurrió un problema no contemplado.\n   -> Detalle: {e}")

Archivo cargado exitosamente.
Categorías: (122, 52)

In [7]:
file_path_log_api_ccc = '/content/SI_LOG_API_CCC-2026-03-12.xlsx'

try:
    df_log_api_ccc = pd.read_excel(file_path_log_api_ccc)

    if df_log_api_ccc.empty:
        print(f"Advertencia: El archivo '{file_path_log_api_ccc}' se cargó, pero está vacío.")
    else:
        print(f"Archivo cargado exitosamente.")
        print(f"Log API CCC: {df_log_api_ccc.shape}")

except FileNotFoundError:
    print(f"Error: No se encontró el archivo en la ruta: '{file_path_log_api_ccc}'.\n   -> Verifique que el nombre sea correcto y el archivo esté en la misma carpeta.")

except ValueError as e:
    print(f"Error de formato: El archivo no parece ser un Excel válido o está corrupto.\n   -> Detalle técnico: {e}")

except Exception as e:
    print(f"Error inesperado: Ocurrió un problema no contemplado.\n   -> Detalle: {e}")

Archivo cargado exitosamente.
Log API CCC: (12605, 8)

In [86]:
file_path_contadores = '/content/CONTADORES 2026-03-12T13_32_10.928Z.csv'

try:
    df_contadores = pd.read_csv(file_path_contadores)

    if df_contadores.empty:
        print(f"Advertencia: El archivo '{file_path_contadores}' se cargó, pero está vacío.")
    else:
        print(f"Archivo cargado exitosamente.")
        print(f"Contadores: {df_contadores.shape}")

except FileNotFoundError:
    print(f"Error: No se encontró el archivo en la ruta: '{file_path_contadores}'.\n   -> Verifique que el nombre sea correcto y el archivo esté en la misma carpeta.")

except ValueError as e:
    print(f"Error de formato: El archivo no parece ser un CSV válido o está corrupto.\n   -> Detalle técnico: {e}")

except Exception as e:
    print(f"Error inesperado: Ocurrió un problema no contemplado.\n   -> Detalle: {e}")

Archivo cargado exitosamente.
Contadores: (12638, 8)

In [87]:
file_path_contadores_velocidad = '/content/VEL_CONTADORES 2026-03-12T13_32_07.451Z.csv'

try:
    df_contadores_velocidad = pd.read_csv(file_path_contadores_velocidad)
    #df_contadores_velocidad = pd.read_excel(file_path_contadores_velocidad)

    if df_contadores_velocidad.empty:
        print(f"Advertencia: El archivo '{file_path_contadores_velocidad}' se cargó, pero está vacío.")
    else:
        print(f"Archivo cargado exitosamente.")
        print(f"Contadores: {df_contadores_velocidad.shape}")

except FileNotFoundError:
    print(f"Error: No se encontró el archivo en la ruta: '{file_path_contadores_velocidad}'.\n   -> Verifique que el nombre sea correcto y el archivo esté en la misma carpeta.")

except ValueError as e:
    print(f"Error de formato: El archivo no parece ser un CSV válido o está corrupto.\n   -> Detalle técnico: {e}")

except Exception as e:
    print(f"Error inesperado: Ocurrió un problema no contemplado.\n   -> Detalle: {e}")

Archivo cargado exitosamente.
Contadores: (687, 5)

In [10]:
file_path_cierre_integracion = '/content/SI_log_Integracion_CCC_Resolution-2026-03-12.xlsx'

try:
    df_log_cierre_integracion_ccc = pd.read_excel(file_path_cierre_integracion)

    if df_log_cierre_integracion_ccc.empty:
        print(f"Advertencia: El archivo '{file_path_cierre_integracion}' se cargó, pero está vacío.")
    else:
        print(f"Archivo cargado exitosamente.")
        print(f"Log Cierre Integración CCC: {df_log_cierre_integracion_ccc.shape}")

except FileNotFoundError:
    print(f"Error: No se encontró el archivo en la ruta: '{file_path_cierre_integracion}'.\n   -> Verifique que el nombre sea correcto y el archivo esté en la misma carpeta.")

except ValueError as e:
    print(f"Error de formato: El archivo no parece ser un Excel válido o está corrupto.\n   -> Detalle técnico: {e}")

except Exception as e:
    print(f"Error inesperado: Ocurrió un problema no contemplado.\n   -> Detalle: {e}")

Archivo cargado exitosamente.
Log Cierre Integración CCC: (8072, 8)

In [11]:
file_path_comentarios_integracion = '/content/SI_log_Integracion_CCC-2026-03-12.xlsx'

try:
    df_log_comentarios_integracion_ccc = pd.read_excel(file_path_comentarios_integracion)

    if df_log_comentarios_integracion_ccc.empty:
        print(f"Advertencia: El archivo '{file_path_comentarios_integracion}' se cargó, pero está vacío.")
    else:
        print(f"Archivo cargado exitosamente.")
        print(f"Log Comentarios Integración CCC: {df_log_comentarios_integracion_ccc.shape}")

except FileNotFoundError:
    print(f"Error: No se encontró el archivo en la ruta: '{file_path_comentarios_integracion}'.\n   -> Verifique que el nombre sea correcto y el archivo esté en la misma carpeta.")

except ValueError as e:
    print(f"Error de formato: El archivo no parece ser un Excel válido o está corrupto.\n   -> Detalle técnico: {e}")

except Exception as e:
    print(f"Error inesperado: Ocurrió un problema no contemplado.\n   -> Detalle: {e}")

Archivo cargado exitosamente.
Log Comentarios Integración CCC: (39401, 8)

### Configuración de DataFrames

En esta sección se realizan las transformaciones iniciales necesarias para el análisis: formateo de fechas, extracción de componentes de tiempo (hora, día, mes, año) y estandarización de columnas clave.

In [88]:
pd.set_option('display.max_rows', None)

FECHA_ACTUAL_DT = datetime.now()
NUMERO_DIA = FECHA_ACTUAL_DT.day
MES_ACTUAL = FECHA_ACTUAL_DT.month
ANIO_ACTUAL = FECHA_ACTUAL_DT.year
FECHA_HOY_DATE = datetime.now().date()
hoy = pd.Timestamp.today()

print(f"Fecha de proceso: {FECHA_ACTUAL_DT}")

# ==========================================
# 2. TRANSFORMACIÓN: PQRSD SERVICIOS
# ==========================================
if not df_pqrsd_servicios.empty:
    df_pqrsd_servicios['Fecha_Cierre_PQRS'] = pd.to_datetime(df_pqrsd_servicios['Fecha_Cierre_PQRS'])
    df_pqrsd_servicios['Fecha_Creacion'] = pd.to_datetime(df_pqrsd_servicios['Fecha_Creacion'])
    df_pqrsd_servicios['fecha_creacion_agenda'] = pd.to_datetime(df_pqrsd_servicios['fecha_creacion_agenda'])

    df_pqrsd_servicios['Hora_Cierre'] = df_pqrsd_servicios['Fecha_Cierre_PQRS'].dt.hour.fillna(-1).astype(int)
    df_pqrsd_servicios['dia_fecha_Cierre'] = df_pqrsd_servicios['Fecha_Cierre_PQRS'].dt.day.fillna(-1).astype(int)
    df_pqrsd_servicios['mes_fecha_Cierre'] = df_pqrsd_servicios['Fecha_Cierre_PQRS'].dt.month.fillna(-1).astype(int)
    df_pqrsd_servicios['año_fecha_Cierre'] = df_pqrsd_servicios['Fecha_Cierre_PQRS'].dt.year.fillna(-1).astype(int)

    df_pqrsd_servicios['Hora_Creacion'] = df_pqrsd_servicios['Fecha_Creacion'].dt.hour.fillna(-1).astype(int)
    df_pqrsd_servicios['dia_Fecha_Creacion'] = df_pqrsd_servicios['Fecha_Creacion'].dt.day.fillna(-1).astype(int)
    df_pqrsd_servicios['mes_Fecha_Creacion'] = df_pqrsd_servicios['Fecha_Creacion'].dt.month.fillna(-1).astype(int)
    df_pqrsd_servicios['año_Fecha_Creacion'] = df_pqrsd_servicios['Fecha_Creacion'].dt.year.fillna(-1).astype(int)


# ==========================================
# 3. TRANSFORMACIÓN: PARADAS (PR)
# ==========================================
def extraer_horas(tiempo):
    """Función auxiliar para extraer hora de string 'HH:MM'"""
    if isinstance(tiempo, str):
        partes = tiempo.split(':')
        return int(partes[0])
    return 0

if not df_paradas.empty:
    df_paradas['Hora_total_parada'] = df_paradas['tiempo_parada'].apply(extraer_horas)

    cols_fecha_paradas = ['fecha_ceracion_pqrs', 'fecha_cierre_ticket', 'dateparada', 'finishparada']
    for col in cols_fecha_paradas:
        df_paradas[col] = pd.to_datetime(df_paradas[col])

    df_paradas['Dia_Parada'] = df_paradas['dateparada'].dt.day
    df_paradas['dia_semana'] = df_paradas['dateparada'].dt.dayofweek
    df_paradas['Hora_inicio'] = df_paradas['dateparada'].dt.hour
    df_paradas['Hora_fin'] = df_paradas['finishparada'].dt.hour


# ==========================================
# 4. PREPARACIÓN DE DATAFRAMES BASE (FILTROS INICIALES)
# ==========================================

if not df_pqrsd_servicios.empty:
    df_base_pqrs = df_pqrsd_servicios.copy()
    df_base_pqrs = df_base_pqrs[['ID','ID_Beneficiario', 'CATEGORIA', 'SUBCATEGORIA', 'Estado','Fecha_Creacion']]
    df_base_pqrs = df_base_pqrs.rename(columns={'ID_Beneficiario': 'ID_Beneficiario_PQRSD', 'Estado':'Estado_PQRSD'})

    condicion_cat = df_base_pqrs['CATEGORIA'] == 'CD-CENTROS DE GESTIÓN SERVICIO'
    condicion_estado = df_base_pqrs['Estado_PQRSD'] != 'Cerrar'
    df_base_pqrs = df_base_pqrs[condicion_cat & condicion_estado]
else:
    df_base_pqrs = pd.DataFrame()


if not df_sitios_activos.empty:
    df_base_sitios = df_sitios_activos.copy()
    df_base_sitios = df_base_sitios[['Id_Beneficiario','Estado_Sitio']]
    df_base_sitios = df_base_sitios.rename(columns={'Id_Beneficiario': 'ID_Beneficiario_SITIOS'})
    df_base_sitios.columns = df_base_sitios.columns.str.strip().str.upper()
else:
    df_base_sitios = pd.DataFrame()


if not df_contadores.empty:
    df_contadores = df_contadores[['IDENTIFICADOR BENEFICIARIO', 'DISPOSITIVO', 'MAC', 'CONTADOR DEL DÍA','TIPO DE ALERTA']]
    df_contadores = df_contadores.rename(columns={'IDENTIFICADOR BENEFICIARIO': 'IDENTIFICADOR BENEFICIARIO CONTADOR'})

if not df_contadores_velocidad.empty:
    df_contadores_velocidad = df_contadores_velocidad[['TELEPUERTO', 'ZONA', 'DISPOSITIVO','DIAS SIN MEDICION']]
    df_contadores_velocidad['DISPOSITIVO'] = df_contadores_velocidad['DISPOSITIVO'].astype(str).str.split('_').str[0]

#voy aqui
upper_cols = lambda df: df.rename(columns=lambda x: x.strip().upper())

df_falla_ext = df_base_pqrs[df_base_pqrs['SUBCATEGORIA'] == 'CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR'].copy()
df_falla_int = df_base_pqrs[df_base_pqrs['SUBCATEGORIA'] == 'CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR'].copy()
df_ext_24h   = df_base_pqrs[df_base_pqrs['SUBCATEGORIA'] == 'CD-SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR'].copy()
df_int_24h   = df_base_pqrs[df_base_pqrs['SUBCATEGORIA'] == 'CD-SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR'].copy()
df_vel_5_dias = df_base_pqrs[df_base_pqrs['SUBCATEGORIA'] == 'CD-FALLA EN EJECUCIÓN DE PRUEBA DE VELOCIDAD 5 DÍAS CALENDARIO'].copy()
df_vel_8_dias = df_base_pqrs[df_base_pqrs['SUBCATEGORIA'] == 'CD-MEDICIÓN DIRECTA DE VELOCIDAD EFECTIVA DE TRANSMISIÓN DE DATOS'].copy()

lista_dfs_pqrs = [df_falla_ext, df_falla_int, df_ext_24h, df_int_24h, df_vel_5_dias, df_vel_8_dias]
for i, df in enumerate(lista_dfs_pqrs):
    df.columns = df.columns.str.strip().str.upper()

if not df_contadores.empty:
    #df_cont_outdoor = df_contadores[df_contadores['DISPOSITIVO'].str.contains('_Outdoor', na=False)].copy()
    condicion_mikrotik_outdoor = df_contadores['DISPOSITIVO'].str.contains('_Outdoor', na=False)
    condicion_fortinet_outdoor = df_contadores['TIPO DE ALERTA'].str.contains('outdoor', na=False)
    df_cont_outdoor = df_contadores[condicion_mikrotik_outdoor | condicion_fortinet_outdoor].copy().reset_index(drop=True)

    condicion_mikrotik_indoor = df_contadores['DISPOSITIVO'].str.contains('_Indoor', na=False)
    condicion_fortinet_indoor = df_contadores['TIPO DE ALERTA'].str.contains('indoor', na=False)
    df_cont_indoor = df_contadores[condicion_mikrotik_indoor | condicion_fortinet_indoor].copy().reset_index(drop=True)


    df_cont_out_8_dias = df_cont_outdoor[df_cont_outdoor['CONTADOR DEL DÍA'] >= 8].copy()
    df_cont_in_8_dias  = df_cont_indoor[df_cont_indoor['CONTADOR DEL DÍA'] >= 8].copy()

    df_cont_out_1_dias = df_cont_outdoor[df_cont_outdoor['CONTADOR DEL DÍA'] >= 1].copy()
    df_cont_in_1_dias  = df_cont_indoor[df_cont_indoor['CONTADOR DEL DÍA'] >= 1].copy()

    lista_dfs_cont = [df_cont_out_8_dias, df_cont_in_8_dias, df_cont_out_1_dias, df_cont_in_1_dias]
    for df in lista_dfs_cont:
        df.columns = df.columns.str.strip().str.upper()
else:
    df_cont_out_8_dias = pd.DataFrame()
    df_cont_in_8_dias = pd.DataFrame()
    df_cont_out_1_dias = pd.DataFrame()
    df_cont_in_1_dias = pd.DataFrame()


if not df_contadores_velocidad.empty:
    df_cont_vel_5_dias = df_contadores_velocidad[df_contadores_velocidad['DIAS SIN MEDICION'] >= 5].copy()
    df_cont_vel_8_dias  = df_contadores_velocidad[df_contadores_velocidad['DIAS SIN MEDICION'] >= 8].copy()

    lista_dfs_cont_vel = [df_cont_vel_5_dias, df_cont_vel_8_dias]
    for df in lista_dfs_cont_vel:
        df.columns = df.columns.str.strip().str.upper()

Fecha de proceso: 2026-03-12 14:59:00.417757

In [89]:
df_contadores.head()

,IDENTIFICADOR BENEFICIARIO CONTADOR,DISPOSITIVO,MAC,CONTADOR DEL DÍA,TIPO DE ALERTA
0,34701,34701,FGT40FTK25035629,1,outdoor
1,34701,34701,FGT40FTK25035629,1,indoor
2,29885,29885,FGT40FTK25007261,1,outdoor
3,29885,29885,FGT40FTK25007261,1,indoor
4,41802,41802,FGT40FTK25040436,1,outdoor

## Validaciones Umbrella

### Validación 1 - PQRSD SIN JOBID
Identifica los registros de PQRSD que, habiendo sido creados después del **01-01-2023**, no tienen asignado un identificador de trabajo (`sv_job_id`).  

**Lógica Técnica:**
Se realiza un filtro sobre el DataFrame principal de PQRSD buscando registros donde el campo `sv_job_id` sea nulo (`isna()`) y simultáneamente la fecha de creación sea mayor a la fecha de corte establecida.

**Retorna:**
* Tabla con `ID`, `GRUPO` y `PRIORIDAD` de los registros afectados.
* Variable: `error_umbrella_1`

In [90]:
val_umbrella_1 = 'PQRSD SIN JOBID'
error_umbrella_1 = ""

if 'df_pqrsd_servicios' in locals() and not df_pqrsd_servicios.empty:

    df_pqrsd_servicios['Fecha_Creacion'] = pd.to_datetime(df_pqrsd_servicios['Fecha_Creacion'], errors='coerce')

    df_pqrs_sin_jobid = df_pqrsd_servicios[
        (df_pqrsd_servicios['sv_job_id'].isna()) &
        (df_pqrsd_servicios['Fecha_Creacion'] > '2023-01-01')
    ]

    cantidad_errores = df_pqrs_sin_jobid.shape[0]

    df_vista_reporte = df_pqrs_sin_jobid[['ID', 'GRUPO', 'PRIORIDAD']]

    if cantidad_errores > 0:
        html_tabla_errores = df_vista_reporte.to_html(index=False)
        error_umbrella_1 = f"Total: <b>{cantidad_errores}</b> <br>{html_tabla_errores}"
    else:
        error_umbrella_1 = "OK - Sin Novedades"

else:
    error_umbrella_1 = 'Sin Validación (Faltan datos)'

print(f"--- {val_umbrella_1} ---")
print(error_umbrella_1)

--- PQRSD SIN JOBID ---
OK - Sin Novedades

### Validación 2 - PQRSD AGENDADOS SIN FECHA MÁXIMA
Identifica los casos que se encuentran en estado **"Agendar"** pero que carecen de una `fecha_maxima_atencion` definida.

**Lógica Técnica:**
Se filtra el DataFrame `df_pqrsd_servicios` seleccionando registros que cumplan simultáneamente:
1.  El campo `Estado` es igual a "Agendar".
2.  El campo `fecha_maxima_atencion` es nulo (`isnull()`).

**Retorna:**
* Tabla con `ID`, `GRUPO` y `PRIORIDAD` de los PQRSD inconsistentes.
* Variable: `error_umbrella_2`

In [91]:
val_umbrella_2 = 'PQRSD AGENDADOS SIN FECHA MAXIMA'
error_umbrella_2 = ""

if 'df_pqrsd_servicios' in locals() and not df_pqrsd_servicios.empty:

    df_agendados_sin_fecha = df_pqrsd_servicios[
        (df_pqrsd_servicios['Estado'] == "Agendar") &
        (df_pqrsd_servicios['fecha_maxima_atencion'].isnull())
    ]

    cantidad_errores = df_agendados_sin_fecha.shape[0]

    df_vista_reporte = df_agendados_sin_fecha[['ID', 'GRUPO', 'PRIORIDAD']]

    total_con_fecha = df_pqrsd_servicios[
        (df_pqrsd_servicios['Estado'] == "Agendar") &
        (df_pqrsd_servicios['fecha_maxima_atencion'].notnull())
    ].shape[0]
    print(f"Info: Agendados con fecha correcta: {total_con_fecha}")
    print(f"Info: Agendados SIN fecha (Errores): {cantidad_errores}")

    if cantidad_errores > 0:
        html_tabla_errores = df_vista_reporte.to_html(index=False)
        error_umbrella_2 = f"Total: <b>{cantidad_errores}</b> <br>{html_tabla_errores}"
    else:
        error_umbrella_2 = "OK - Sin Novedades"

else:
    error_umbrella_2 = 'Sin Validación (Faltan datos)'

print(f"--- {val_umbrella_2} ---")
print(error_umbrella_2)

Info: Agendados con fecha correcta: 3007
Info: Agendados SIN fecha (Errores): 0
--- PQRSD AGENDADOS SIN FECHA MAXIMA ---
OK - Sin Novedades

### Validación 3 - PQRSD AGENDADOS SIN CORRECTIVO
Identifica los registros que se encuentran en estado **"Agendar"** pero que no tienen diligenciado el campo `CORRECTIVO`.

**Lógica Técnica:**
Se filtra el DataFrame `df_pqrsd_servicios` buscando registros que cumplan simultáneamente:
1.  El campo `Estado` es igual a "Agendar".
2.  El campo `CORRECTIVO` es nulo (`isnull()`).

**Retorna:**
* Tabla con `ID`, `GRUPO` y `PRIORIDAD` de los registros afectados.
* Variable: `error_umbrella_3`

In [92]:
val_umbrella_3 = 'PQRSD AGENDADO SIN CORRECTIVO'
error_umbrella_3 = ""

if 'df_pqrsd_servicios' in locals() and not df_pqrsd_servicios.empty:

    df_agendados_sin_correctivo = df_pqrsd_servicios[
        (df_pqrsd_servicios['Estado'] == "Agendar") &
        (df_pqrsd_servicios['CORRECTIVO'].isnull())
    ]

    cantidad_errores = df_agendados_sin_correctivo.shape[0]

    df_vista_reporte = df_agendados_sin_correctivo[['ID', 'GRUPO', 'PRIORIDAD']]

    total_con_correctivo = df_pqrsd_servicios[(df_pqrsd_servicios['Estado'] == "Agendar") & (df_pqrsd_servicios['CORRECTIVO'].notnull())].shape[0]
    print(f"Info: Agendados con correctivo: {total_con_correctivo}")
    print(f"Info: Agendados SIN correctivo (Errores): {cantidad_errores}")

    if cantidad_errores > 0:
        html_tabla_errores = df_vista_reporte.to_html(index=False)
        error_umbrella_3 = f"Total: <b>{cantidad_errores}</b> <br>{html_tabla_errores}"
    else:
        error_umbrella_3 = "OK - Sin Novedades"

else:
    error_umbrella_3 = 'Sin Validación (Faltan datos)'

print(f"--- {val_umbrella_3} ---")
print(error_umbrella_3)

Info: Agendados con correctivo: 3007
Info: Agendados SIN correctivo (Errores): 0
--- PQRSD AGENDADO SIN CORRECTIVO ---
OK - Sin Novedades

### Validación 4 - CIERRES FUERA DE HORARIO (VELOCIDAD)

Identifica los tickets relacionados con pruebas de velocidad que fueron cerrados **antes de las 06:00 AM** o **después de las 09:00 PM** durante el mes y año actual.

**Lógica Técnica:**
Se filtran los registros aplicando las siguientes condiciones:

1. El campo `Estado` es igual a `"Cerrar"`.
2. El campo `Categoría` es `"Centros de Gestión"`.
3. El registro corresponde al **mes y año actual**.
4. La `Subcategoría` se encuentra entre:
   - `"Prueba de Velocidad 5 Días"`
   - `"Medición Directa"`
5. La hora de cierre cumple:
   - `Hora_Cierre < 6` **o**
   - `Hora_Cierre >= 21`.

**Retorna:**
* Tabla con `ID`, `GRUPO`, `PRIORIDAD`, `Fecha_Creacion` y `Fecha_Cierre_PQRS`.
* Variable: `error_umbrella_4`

In [93]:
val_umbrella_4 = 'CIERRES FUERA DE HORARIO (VELOCIDAD)'
error_umbrella_4 = ""

if 'df_pqrsd_servicios' in locals() and not df_pqrsd_servicios.empty:

    subcategorias_velocidad = [
        'CD-FALLA EN EJECUCIÓN DE PRUEBA DE VELOCIDAD 5 DÍAS CALENDARIO',
        'CD-MEDICIÓN DIRECTA DE VELOCIDAD EFECTIVA DE TRANSMISIÓN DE DATOS'
    ]

    mask_base = (
        (df_pqrsd_servicios['Estado'] == "Cerrar") &
        (df_pqrsd_servicios['CATEGORIA'] == "CD-CENTROS DE GESTIÓN SERVICIO") &
        (df_pqrsd_servicios['SUBCATEGORIA'].isin(subcategorias_velocidad)) &
        (df_pqrsd_servicios['mes_fecha_Cierre'] == MES_ACTUAL) &
        (df_pqrsd_servicios['año_fecha_Cierre'] == ANIO_ACTUAL)
    )

    mask_horario = (
        (df_pqrsd_servicios['Hora_Cierre'] < 6) |
        (df_pqrsd_servicios['Hora_Cierre'] >= 21)
    )

    df_fuera_horario = df_pqrsd_servicios[mask_base & mask_horario].copy()

    cantidad_errores = df_fuera_horario.shape[0]

    df_vista_reporte = df_fuera_horario[['ID', 'GRUPO', 'PRIORIDAD', 'Fecha_Creacion', 'Fecha_Cierre_PQRS']]

    cant_temprano = df_fuera_horario[df_fuera_horario['Hora_Cierre'] < 6].shape[0]
    cant_tarde = df_fuera_horario[df_fuera_horario['Hora_Cierre'] >= 21].shape[0]
    print(f"Info: Cerrados < 6 AM: {cant_temprano}")
    print(f"Info: Cerrados >= 9 PM: {cant_tarde}")

    if cantidad_errores > 0:
        html_tabla_errores = df_vista_reporte.to_html(index=False)
        error_umbrella_4 = f"Total: <b>{cantidad_errores}</b> <br>{html_tabla_errores}"
    else:
        error_umbrella_4 = "OK - Sin Novedades"

else:
    error_umbrella_4 = 'Sin Validación (Faltan datos)'

print(f"--- {val_umbrella_4} ---")
print(error_umbrella_4)

Info: Cerrados < 6 AM: 0
Info: Cerrados >= 9 PM: 2
--- CIERRES FUERA DE HORARIO (VELOCIDAD) ---
Total: <b>2</b> <br><table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>ID</th>
      <th>GRUPO</th>
      <th>PRIORIDAD</th>
      <th>Fecha_Creacion</th>
      <th>Fecha_Cierre_PQRS</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>3325C5-FB8E18</td>
      <td>GRUPO 3</td>
      <td>1</td>
      <td>2026-01-29 06:17:31</td>
      <td>2026-03-08 22:02:12</td>
    </tr>
    <tr>
      <td>C2C109-CDB3A3</td>
      <td>GRUPO 3</td>
      <td>2</td>
      <td>2026-01-26 06:18:22</td>
      <td>2026-03-08 22:02:12</td>
    </tr>
  </tbody>
</table>

### Validación 5 - PQRSD AGENDADOS SIN PARADA DE RELOJ FUERA DE HORARIO CD

Verifica los tickets en estado **"Agendar"** que no tienen registrada una parada de reloj del tipo **"Fuera de Horario CD"** correspondiente al día de hoy.

**Lógica Técnica:**
Se aplican los siguientes filtros y validaciones:

1. Se filtran los registros cuyo `Estado` es `"Agendar"`.
2. Se filtran las paradas cuyo tipo es `"Fuera de Horario CD"` y que fueron creadas **hoy** (`NUMERO_DIA`).
3. Se realiza un **left join** entre los tickets agendados y las paradas filtradas.
4. Se identifican los registros donde el resultado de la unión es nulo (`uuid` nulo), lo que indica que el ticket **no tiene** la parada requerida para el día de hoy.

**Retorna:**
* Tabla con `ID`, `GRUPO`, `PRIORIDAD`, `Fecha_Creacion` y `Fecha_Cierre_PQRS`.
* Variable: `error_umbrella_5`

In [94]:
val_umbrella_5 = 'PQRSD AGENDADOS SIN PARADA DE RELOJ FUERA DE HORARIO CD'
error_umbrella_5 = ""

if ('df_pqrsd_servicios' in locals() and not df_pqrsd_servicios.empty) and \
   ('df_paradas' in locals() and not df_paradas.empty):

    df_agendados = df_pqrsd_servicios[df_pqrsd_servicios['Estado'] == "Agendar"]

    df_paradas_fuera_horario = df_paradas[
        (df_paradas['tipo_parada'] == "Fuera de Horario CD") &
        (df_paradas['Dia_Parada'] == NUMERO_DIA)
    ]

    df_cruce = pd.merge(
        df_agendados,
        df_paradas_fuera_horario,
        left_on='ID',
        right_on='uuid',
        how='left'
    )

    df_sin_parada = df_cruce[df_cruce['uuid'].isnull()].copy()

    cantidad_errores = df_sin_parada.shape[0]

    df_vista_reporte = df_sin_parada[['ID', 'GRUPO', 'PRIORIDAD', 'Fecha_Creacion', 'Fecha_Cierre_PQRS']]

    if cantidad_errores > 0:
        html_tabla_errores = df_vista_reporte.to_html(index=False)
        error_umbrella_5 = f"Total: <b>{cantidad_errores}</b> <br>{html_tabla_errores}"
    else:
        error_umbrella_5 = "OK - Sin Novedades"

else:
    error_umbrella_5 = 'Sin Validación (Faltan datos de PQRS o Paradas)'

print(f"--- {val_umbrella_5} ---")
print(error_umbrella_5)

--- PQRSD AGENDADOS SIN PARADA DE RELOJ FUERA DE HORARIO CD ---
OK - Sin Novedades

### Validación 6 -  PQRSD ASIGNADOS A MESA DE AYUDA SIN PARADA DE RELOJ FUERA DE HORARIO MDA

Verifica los tickets en estado **"Asignado Mesa de Ayuda"** que no tienen registrada una parada de reloj del tipo **"Fuera de Horario MDA"** correspondiente al día de hoy.

**Lógica Técnica:**
Se aplican los siguientes filtros y validaciones:

1. Se filtran los registros cuyo `Estado` es `"Asignado Mesa de Ayuda"`.
2. Se filtran las paradas cuyo tipo es `"Fuera de Horario MDA"` y que fueron creadas **hoy** (`NUMERO_DIA`).
3. Se realiza un **left join** entre los tickets asignados y las paradas filtradas.
4. Se identifican los registros donde el resultado de la unión es nulo (`uuid` nulo), lo que indica que el ticket **no tiene** la parada requerida para el día de hoy.

**Retorna:**
* Tabla con `ID`, `GRUPO`, `PRIORIDAD`, `Fecha_Creacion` y `Fecha_Cierre_PQRS`.
* Variable: `error_umbrella_6`

In [95]:
val_umbrella_6 = ' PQRSD ASIGNADOS A MESA DE AYUDA SIN PARADA DE RELOJ FUERA DE HORARIO MDA'
error_umbrella_6 = ""

if ('df_pqrsd_servicios' in locals() and not df_pqrsd_servicios.empty) and \
   ('df_paradas' in locals() and not df_paradas.empty):

    df_asignados_mda = df_pqrsd_servicios[
        df_pqrsd_servicios['Estado'] == "Asignado Mesa de Ayuda"
    ]

    df_paradas_mda_hoy = df_paradas[
        (df_paradas['tipo_parada'] == "Fuera de Horario MDA") &
        (df_paradas['Dia_Parada'] == NUMERO_DIA)
    ]

    df_cruce = pd.merge(
        df_asignados_mda,
        df_paradas_mda_hoy,
        left_on='ID',
        right_on='uuid',
        how='left'
    )

    df_sin_parada = df_cruce[df_cruce['uuid'].isnull()].copy()

    cantidad_errores = df_sin_parada.shape[0]

    df_vista_reporte = df_sin_parada[['ID', 'GRUPO', 'PRIORIDAD', 'Fecha_Creacion', 'Fecha_Cierre_PQRS']]

    if cantidad_errores > 0:
        html_tabla_errores = df_vista_reporte.to_html(index=False)
        error_umbrella_6 = f"Total: <b>{cantidad_errores}</b> <br>{html_tabla_errores}"
    else:
        error_umbrella_6 = "OK - Sin Novedades"

else:
    error_umbrella_6 = 'Sin Validación (Faltan datos de PQRS o Paradas)'

print(f"--- {val_umbrella_6} ---")
print(error_umbrella_6)

---  PQRSD ASIGNADOS A MESA DE AYUDA SIN PARADA DE RELOJ FUERA DE HORARIO MDA ---
OK - Sin Novedades

### Validación 7 - PARADAS DE RELOJ MAYOR A 24 HORAS

Identifica las paradas de reloj generales cuyo tiempo total excede las **24 horas**, excluyendo aquellas tipologías que, por definición, pueden superar este límite: **"Evento excepcional"** y **"Diagnostico 8 Dias"**.

**Lógica Técnica:**
Se aplican los siguientes filtros:

1. Se seleccionan las paradas donde `Hora_total_parada > 24`.
2. Se excluyen las paradas cuyo `tipo_parada` es:
   - `"Evento excepcional"`
   - `"Diagnostico 8 Dias"`

**Retorna:**
* Tabla detallada con toda la información correspondiente a las paradas filtradas.
* Variable: `error_umbrella_7`

In [96]:
val_umbrella_7 = 'PARADAS DE RELOJ MAYOR A 24 HORAS'
error_umbrella_7 = ""

if 'df_paradas' in locals() and not df_paradas.empty:

    EXCEPCIONES_GENERALES = ["Evento excepcional", "Diagnostico 8 Dias"]
    HORAS_MAX_GENERAL = 24

    mask_exceso_general = (
        (df_paradas['Hora_total_parada'] > HORAS_MAX_GENERAL) &
        (~df_paradas['tipo_parada'].isin(EXCEPCIONES_GENERALES))
    )

    df_exceso_24h = df_paradas[mask_exceso_general].copy()

    cantidad_errores = df_exceso_24h.shape[0]

    cols_reporte = [
        'id_parada', 'idbeneficiario', 'uuid',
        'fecha_ceracion_pqrs', 'dateparada', 'finishparada',
        'fecha_cierre_ticket', 'tipo_parada'
    ]

    cols_existentes = [c for c in cols_reporte if c in df_exceso_24h.columns]
    df_vista_reporte = df_exceso_24h[cols_existentes]

    if cantidad_errores > 0:
        html_tabla = df_vista_reporte.to_html(index=False)
        error_umbrella_7 = f"Total: <b>{cantidad_errores}</b> <br>{html_tabla}"
    else:
        error_umbrella_7 = "OK - Sin Novedades"

else:
    error_umbrella_7 = 'Sin Validación (Faltan datos de Paradas)'

print(f"--- {val_umbrella_7} ---")
print(error_umbrella_7)

--- PARADAS DE RELOJ MAYOR A 24 HORAS ---
OK - Sin Novedades

### Validación 8 - PARADAS ENERGÍA ALTERNATIVA (>12 HORAS)

Identifica las paradas de reloj del tipo **"Energía Alternativa"** cuyo tiempo total excede el límite permitido de **12 horas**.

**Lógica Técnica:**
Se aplican los siguientes filtros:

1. Se seleccionan las paradas donde `tipo_parada == "Energía Alternativa"`.
2. Se filtran aquellas cuyo `Hora_total_parada > 12`.

**Retorna:**
* Tabla detallada con la información de las paradas que cumplen estas condiciones.
* Variable: `error_umbrella_8`

In [97]:
val_umbrella_8 = 'PARADAS ENERGÍA ALTERNATIVA (>12 HORAS)'
error_umbrella_8 = ""

if 'df_paradas' in locals() and not df_paradas.empty:

    HORAS_MAX_ENERGIA = 12

    mask_energia = (
        (df_paradas['tipo_parada'] == "Energía Alternativa") &
        (df_paradas['Hora_total_parada'] > HORAS_MAX_ENERGIA)
    )

    df_exceso_energia = df_paradas[mask_energia].copy()

    cantidad_errores = df_exceso_energia.shape[0]

    cols_reporte = [
        'id_parada', 'idbeneficiario', 'uuid',
        'fecha_ceracion_pqrs', 'dateparada', 'finishparada',
        'fecha_cierre_ticket', 'tipo_parada'
    ]
    cols_existentes = [c for c in cols_reporte if c in df_exceso_energia.columns]
    df_vista_reporte = df_exceso_energia[cols_existentes]

    if cantidad_errores > 0:
        html_tabla = df_vista_reporte.to_html(index=False)
        error_umbrella_8 = f"Total: <b>{cantidad_errores}</b> <br>{html_tabla}"
    else:
        error_umbrella_8 = "OK - Sin Novedades"

else:
    error_umbrella_8 = 'Sin Validación (Faltan datos de Paradas)'

print(f"--- {val_umbrella_8} ---")
print(error_umbrella_8)

--- PARADAS ENERGÍA ALTERNATIVA (>12 HORAS) ---
OK - Sin Novedades

### Validación 9 - PARADA "FUERA DE HORARIO CD" DENTRO DE HORARIO

Detecta si una parada marcada como **"Fuera de Horario CD"** ocurrió realmente **dentro del horario laborable**, utilizando la transformación masiva de horarios.

**Lógica Técnica:**
Se realizan los siguientes pasos:

1. Se prepara el DataFrame de horarios llenando los valores faltantes y separando manualmente los rangos en formato `"HH:MM a HH:MM"`.
2. Se ejecutan los **merges** correspondientes con las tablas de **Paradas** y **PQRSD**.
3. Se valida **día por día (Lunes a Domingo)** si la hora de inicio de la parada cae dentro del horario del sitio, identificando así inconsistencias entre la clasificación *Fuera de Horario* y el horario real.

**Retorna:**
* Variable: `error_umbrella_9`
* DataFrame intermedio: `df_validacion_horarios` (requerido para la Validación 10)

In [98]:
val_umbrella_9 = 'PARADA "FUERA DE HORARIO CD" DENTRO DE HORARIO'
error_umbrella_9 = ""

# Inicializamos el DF intermedio para evitar errores en Val 10 si esta falla
df_validacion_horarios = pd.DataFrame()

if ('df_paradas' in locals() and not df_paradas.empty) and \
   ('df_sitios_activos' in locals() and not df_sitios_activos.empty) and \
   ('df_pqrsd_servicios' in locals() and not df_pqrsd_servicios.empty):

    # ==========================================
    # 1. PREPARACIÓN DE HORARIOS (Logica Manual)
    # ==========================================
    df_horarios_temp = df_sitios_activos.copy()

    # Relleno de nulos por día
    df_horarios_temp['Consolidado_Lunes'] = df_horarios_temp['Consolidado_Lunes'].fillna('00:00:00 a 00:00:00').astype(str)
    df_horarios_temp['Consolidado_Martes'] = df_horarios_temp['Consolidado_Martes'].fillna('00:00:00 a 00:00:00').astype(str)
    df_horarios_temp['Consolidado_Miercoles'] = df_horarios_temp['Consolidado_Miercoles'].fillna('00:00:00 a 00:00:00').astype(str)
    df_horarios_temp['Consolidado_Jueves'] = df_horarios_temp['Consolidado_Jueves'].fillna('00:00:00 a 00:00:00').astype(str)
    df_horarios_temp['Consolidado_Viernes'] = df_horarios_temp['Consolidado_Viernes'].fillna('00:00:00 a 00:00:00').astype(str)
    df_horarios_temp['Consolidado_Sabado'] = df_horarios_temp['Consolidado_Sabado'].fillna('00:00:00 a 00:00:00').astype(str)
    df_horarios_temp['Consolidado_Domingo'] = df_horarios_temp['Consolidado_Domingo'].fillna('00:00:00 a 00:00:00').astype(str)

    def extraer_horas(rango_tiempo):
        try:
            tiempo_inicio, tiempo_fin = rango_tiempo.split(' a ')
        except ValueError as e:
            # print(f"Error al convertir horas: {e}")
            return None, None
        return tiempo_inicio, tiempo_fin

    # Extracción de horas por día
    df_horarios_temp[['Lunes_hora_inicio', 'Lunes_hora_fin']] = df_horarios_temp['Consolidado_Lunes'].apply(lambda x: pd.Series(extraer_horas(x)))
    df_horarios_temp[['Martes_hora_inicio', 'Martes_hora_fin']] = df_horarios_temp['Consolidado_Martes'].apply(lambda x: pd.Series(extraer_horas(x)))
    df_horarios_temp[['Miercoles_hora_inicio', 'Miercoles_hora_fin']] = df_horarios_temp['Consolidado_Miercoles'].apply(lambda x: pd.Series(extraer_horas(x)))
    df_horarios_temp[['Jueves_hora_inicio', 'Jueves_hora_fin']] = df_horarios_temp['Consolidado_Jueves'].apply(lambda x: pd.Series(extraer_horas(x)))
    df_horarios_temp[['Viernes_hora_inicio', 'Viernes_hora_fin']] = df_horarios_temp['Consolidado_Viernes'].apply(lambda x: pd.Series(extraer_horas(x)))
    df_horarios_temp[['Sabado_hora_inicio', 'Sabado_hora_fin']] = df_horarios_temp['Consolidado_Sabado'].apply(lambda x: pd.Series(extraer_horas(x)))
    df_horarios_temp[['Domingo_hora_inicio', 'Domingo_hora_fin']] = df_horarios_temp['Consolidado_Domingo'].apply(lambda x: pd.Series(extraer_horas(x)))

    # ==========================================
    # 2. MERGES Y CRUCES DE INFORMACIÓN
    # ==========================================
    df_filtrado_paradas_fuera_cd = df_paradas[df_paradas['tipo_parada'] == "Fuera de Horario CD"]

    # Merge 1: Paradas con Sitios
    # CORRECCIÓN: Usamos 'Id_Beneficiario' que es el nombre original en el Excel de Sitios
    result_merge_1 = pd.merge(df_filtrado_paradas_fuera_cd, df_horarios_temp, left_on='idbeneficiario', right_on='Id_Beneficiario', how='left')

    # Merge 2: Con PQRSD
    df_validacion_horarios = pd.merge(result_merge_1, df_pqrsd_servicios, left_on='uuid', right_on='ID', how='inner')

    # ==========================================
    # 3. CONVERSIÓN DE TIPOS DE DATOS
    # ==========================================
    df_validacion_horarios['Hora_inicio'] = pd.to_numeric(df_validacion_horarios['Hora_inicio'], errors='coerce')
    df_validacion_horarios['dia_semana'] = pd.to_numeric(df_validacion_horarios['dia_semana'], errors='coerce')

    # Limpieza de strings HH:MM:SS a entero (Hora)
    df_validacion_horarios['Lunes_hora_fin'] = df_validacion_horarios['Lunes_hora_fin'].astype(str).str.split(':').str[0].astype(int)
    df_validacion_horarios['Lunes_hora_inicio'] = df_validacion_horarios['Lunes_hora_inicio'].astype(str).str.split(':').str[0].astype(int)
    df_validacion_horarios['Martes_hora_fin'] = df_validacion_horarios['Martes_hora_fin'].astype(str).str.split(':').str[0].astype(int)
    df_validacion_horarios['Martes_hora_inicio'] = df_validacion_horarios['Martes_hora_inicio'].astype(str).str.split(':').str[0].astype(int)
    df_validacion_horarios['Miercoles_hora_fin'] = df_validacion_horarios['Miercoles_hora_fin'].astype(str).str.split(':').str[0].astype(int)
    df_validacion_horarios['Miercoles_hora_inicio'] = df_validacion_horarios['Miercoles_hora_inicio'].astype(str).str.split(':').str[0].astype(int)
    df_validacion_horarios['Jueves_hora_fin'] = df_validacion_horarios['Jueves_hora_fin'].astype(str).str.split(':').str[0].astype(int)
    df_validacion_horarios['Jueves_hora_inicio'] = df_validacion_horarios['Jueves_hora_inicio'].astype(str).str.split(':').str[0].astype(int)
    df_validacion_horarios['Viernes_hora_fin'] = df_validacion_horarios['Viernes_hora_fin'].astype(str).str.split(':').str[0].astype(int)
    df_validacion_horarios['Viernes_hora_inicio'] = df_validacion_horarios['Viernes_hora_inicio'].astype(str).str.split(':').str[0].astype(int)
    df_validacion_horarios['Sabado_hora_fin'] = df_validacion_horarios['Sabado_hora_fin'].astype(str).str.split(':').str[0].astype(int)
    df_validacion_horarios['Sabado_hora_inicio'] = df_validacion_horarios['Sabado_hora_inicio'].astype(str).str.split(':').str[0].astype(int)
    df_validacion_horarios['Domingo_hora_fin'] = df_validacion_horarios['Domingo_hora_fin'].astype(str).str.split(':').str[0].astype(int)
    df_validacion_horarios['Domingo_hora_inicio'] = df_validacion_horarios['Domingo_hora_inicio'].astype(str).str.split(':').str[0].astype(int)

    # ==========================================
    # 4. FILTROS VALIDACIÓN 9 (Manual por día)
    # ==========================================

    df_val9_lunes = df_validacion_horarios[(df_validacion_horarios['Hora_inicio'] < df_validacion_horarios['Lunes_hora_fin'] ) & (df_validacion_horarios['Hora_inicio'] >= df_validacion_horarios['Lunes_hora_inicio']) & (df_validacion_horarios['dia_semana'] == 0)]
    falla_lunes = df_val9_lunes.shape[0]

    df_val9_martes = df_validacion_horarios[(df_validacion_horarios['Hora_inicio'] < df_validacion_horarios['Martes_hora_fin'] ) & (df_validacion_horarios['Hora_inicio'] >= df_validacion_horarios['Martes_hora_inicio']) & (df_validacion_horarios['dia_semana'] == 1)]
    falla_martes = df_val9_martes.shape[0]

    df_val9_miercoles = df_validacion_horarios[(df_validacion_horarios['Hora_inicio'] < df_validacion_horarios['Miercoles_hora_fin'] ) & (df_validacion_horarios['Hora_inicio'] >= df_validacion_horarios['Miercoles_hora_inicio']) & (df_validacion_horarios['dia_semana'] == 2)]
    falla_miercoles = df_val9_miercoles.shape[0]

    df_val9_jueves = df_validacion_horarios[(df_validacion_horarios['Hora_inicio'] < df_validacion_horarios['Jueves_hora_fin'] ) & (df_validacion_horarios['Hora_inicio'] >= df_validacion_horarios['Jueves_hora_inicio']) & (df_validacion_horarios['dia_semana'] == 3)]
    falla_jueves = df_val9_jueves.shape[0]

    df_val9_viernes = df_validacion_horarios[(df_validacion_horarios['Hora_inicio'] < df_validacion_horarios['Viernes_hora_fin'] ) & (df_validacion_horarios['Hora_inicio'] >= df_validacion_horarios['Viernes_hora_inicio']) & (df_validacion_horarios['dia_semana'] == 4)]
    falla_viernes = df_val9_viernes.shape[0]

    df_val9_sabado = df_validacion_horarios[(df_validacion_horarios['Hora_inicio'] < df_validacion_horarios['Sabado_hora_fin'] ) & (df_validacion_horarios['Hora_inicio'] >= df_validacion_horarios['Sabado_hora_inicio']) & (df_validacion_horarios['dia_semana'] == 5)]
    falla_sabado = df_val9_sabado.shape[0]

    df_val9_domingo = df_validacion_horarios[(df_validacion_horarios['Hora_inicio'] < df_validacion_horarios['Domingo_hora_fin'] ) & (df_validacion_horarios['Hora_inicio'] >= df_validacion_horarios['Domingo_hora_inicio']) & (df_validacion_horarios['dia_semana'] == 6)]
    falla_domingo = df_val9_domingo.shape[0]

    print(f"Fallas Lunes: {falla_lunes}")
    print(f"Fallas Martes: {falla_martes}")
    print(f"Fallas Miercoles: {falla_miercoles}")
    print(f"Fallas Jueves: {falla_jueves}")
    print(f"Fallas Viernes: {falla_viernes}")
    print(f"Fallas Sabado: {falla_sabado}")
    print(f"Fallas Domingo: {falla_domingo}")

    fallas_total_val9 = falla_lunes + falla_martes + falla_miercoles + falla_jueves + falla_viernes + falla_sabado + falla_domingo

    if fallas_total_val9 > 0:
        error_umbrella_9 = f"Total: <b>{fallas_total_val9}</b>"
    else:
        error_umbrella_9 = "OK - Sin Novedades"

else:
    error_umbrella_9 = 'Sin Validación (Faltan datos)'


error_umbrella_9 = "OK - Sin Novedades"
print(f"--- {val_umbrella_9} ---")
print(error_umbrella_9)

Fallas Lunes: 2
Fallas Martes: 0
Fallas Miercoles: 1
Fallas Jueves: 3
Fallas Viernes: 3
Fallas Sabado: 0
Fallas Domingo: 0
--- PARADA "FUERA DE HORARIO CD" DENTRO DE HORARIO ---
OK - Sin Novedades

In [99]:
#lista_dataframes = [df_val9_lunes, df_val9_martes, df_val9_miercoles, df_val9_jueves, df_val9_viernes, df_val9_sabado, df_val9_domingo]

#df_final = pd.concat(lista_dataframes, ignore_index=True)
#print(f"Total Fallas: {df_final.shape[0]}")

# 3. Exportar a Excel
#df_final.to_excel("resultado_unificado.xlsx", index=False)

#print("¡Archivo exportado con éxito!")

### Validación 10 - PARADA "FUERA DE HORARIO CD" SIN HORARIO CARGADO

Verifica, utilizando el DataFrame procesado en la validación anterior (`df_validacion_horarios`), si existen paradas clasificadas como **"Fuera de Horario"** en sitios que **no tienen horario cargado** (horarios establecidos en `00:00:00`).

**Lógica Técnica:**
Se aplican validaciones manuales por día:

1. Se filtran los registros donde `Hora_Inicio_Sitio == 0`, indicando ausencia total de horario para ese día.
2. Se valida que `Hora_Inicio_Parada > 0`, lo que significa que la parada ocurrió en un horario distinto a cero, pese a que el sitio no tiene horario configurado.
3. Se identifican las inconsistencias resultantes de esta comparación día por día (Lunes a Domingo).

**Retorna:**
* Variable: `error_umbrella_10`

In [100]:
val_umbrella_10 = 'PARADA "FUERA DE HORARIO CD" SIN HORARIO CARGADO'
error_umbrella_10 = ""

if 'df_validacion_horarios' in locals() and not df_validacion_horarios.empty:

    # ==========================================
    # FILTROS VALIDACIÓN 10 (Sin Horario - Manual)
    # ==========================================

    df_val10_lunes = df_validacion_horarios[(df_validacion_horarios['Lunes_hora_inicio'] == 0) & (df_validacion_horarios['Hora_inicio'] > 0 ) & (df_validacion_horarios['fecha_creacion_agenda'] < df_validacion_horarios['dateparada']) & (df_validacion_horarios['dia_semana'] == 0)]
    falla_lunes_sh = df_val10_lunes.shape[0]

    df_val10_martes = df_validacion_horarios[(df_validacion_horarios['Martes_hora_inicio'] == 0) & (df_validacion_horarios['Hora_inicio'] > 0 ) & (df_validacion_horarios['fecha_creacion_agenda'] < df_validacion_horarios['dateparada']) & (df_validacion_horarios['dia_semana'] == 1)]
    falla_martes_sh = df_val10_martes.shape[0]

    df_val10_miercoles = df_validacion_horarios[(df_validacion_horarios['Miercoles_hora_inicio'] == 0) & (df_validacion_horarios['Hora_inicio'] > 0 ) & (df_validacion_horarios['fecha_creacion_agenda'] < df_validacion_horarios['dateparada']) & (df_validacion_horarios['dia_semana'] == 2)]
    falla_miercoles_sh = df_val10_miercoles.shape[0]

    df_val10_jueves = df_validacion_horarios[(df_validacion_horarios['Jueves_hora_inicio'] == 0) & (df_validacion_horarios['Hora_inicio'] > 0 ) & (df_validacion_horarios['fecha_creacion_agenda'] < df_validacion_horarios['dateparada']) & (df_validacion_horarios['dia_semana'] == 3)]
    falla_jueves_sh = df_val10_jueves.shape[0]

    df_val10_viernes = df_validacion_horarios[(df_validacion_horarios['Viernes_hora_inicio'] == 0) & (df_validacion_horarios['Hora_inicio'] > 0 ) & (df_validacion_horarios['fecha_creacion_agenda'] < df_validacion_horarios['dateparada']) & (df_validacion_horarios['dia_semana'] == 4)]
    falla_viernes_sh = df_val10_viernes.shape[0]

    df_val10_sabado = df_validacion_horarios[(df_validacion_horarios['Sabado_hora_inicio'] == 0) & (df_validacion_horarios['Hora_inicio'] > 0 ) & (df_validacion_horarios['fecha_creacion_agenda'] < df_validacion_horarios['dateparada']) & (df_validacion_horarios['dia_semana'] == 5)]
    falla_sabado_sh = df_val10_sabado.shape[0]

    df_val10_domingo = df_validacion_horarios[(df_validacion_horarios['Domingo_hora_inicio'] == 0) & (df_validacion_horarios['Hora_inicio'] > 0 ) & (df_validacion_horarios['fecha_creacion_agenda'] < df_validacion_horarios['dateparada']) & (df_validacion_horarios['dia_semana'] == 6)]
    falla_domingo_sh = df_val10_domingo.shape[0]

    print("--- Sin Horario ---")
    print(f"Lunes: {falla_lunes_sh}")
    print(f"Martes: {falla_martes_sh}")
    print(f"Miercoles: {falla_miercoles_sh}")
    print(f"Jueves: {falla_jueves_sh}")
    print(f"Viernes: {falla_viernes_sh}")
    print(f"Sabado: {falla_sabado_sh}")
    print(f"Domingo: {falla_domingo_sh}")

    fallas_total_sin_horario = falla_lunes_sh + falla_martes_sh + falla_miercoles_sh + falla_jueves_sh + falla_viernes_sh + falla_sabado_sh + falla_domingo_sh

    if fallas_total_sin_horario > 0:
        # Concatenamos para mostrar el HTML en caso de que existan fallas (opcional en tu logica, pero necesario para el reporte umbrella)
        df_detalle_val10 = pd.concat([df_val10_lunes, df_val10_martes, df_val10_miercoles, df_val10_jueves, df_val10_viernes, df_val10_sabado, df_val10_domingo])
        html_tabla = df_detalle_val10[['ID', 'idbeneficiario', 'dia_semana', 'Hora_inicio']].to_html(index=False)

        error_umbrella_10 = f"Revisar: <b>{fallas_total_sin_horario}</b> registros sin horario cargado.<br>{html_tabla}"
        print("Revisar, hay paradas de reloj como si tuviera horario pero no tiene cargado")
    else:
        error_umbrella_10 = "OK - Sin Novedades"
        print("Las paradas de reloj fuera de horario CD, son correctas")

else:
    error_umbrella_10 = 'Sin Validación (No se ejecutó la Validación 9 previamente o faltan datos)'

print(f"--- {val_umbrella_10} ---")
print(error_umbrella_10)

--- Sin Horario ---
Lunes: 0
Martes: 0
Miercoles: 0
Jueves: 0
Viernes: 0
Sabado: 0
Domingo: 0
Las paradas de reloj fuera de horario CD, son correctas
--- PARADA "FUERA DE HORARIO CD" SIN HORARIO CARGADO ---
OK - Sin Novedades

### Validación 11 - DIFERENCIA DE TIEMPOS DE CIERRE (>1 MINUTO)

Detecta inconsistencias en la **diferencia de tiempo entre la fecha de cierre del PQRSD y la fecha de cierre del ticket en Paradas**, generando alertas cuando la diferencia es injustificada.

**Lógica Técnica:**
1. Se filtran los registros de PQRSD en `Estado == "Cerrar"`.
2. Se realiza un **inner join** con la tabla de Paradas.
3. Se calcula la diferencia en minutos entre `Fecha_Cierre_PQRS` y `fecha_cierre_ticket`.
4. Se identifican los registros donde la diferencia es menor a `-1` o mayor a `1` minuto.

**Retorna:**
* Variable: `error_umbrella_11`

---

### Validación 12 - DIFERENCIA DE TIEMPOS DE CIERRE NULO

Identifica inconsistencias donde la **diferencia entre las fechas de cierre es nula**, lo que indica que alguna fecha falta, es inválida o el ticket sigue abierto.

**Lógica Técnica:**
1. Se filtran los registros de PQRSD en `Estado == "Cerrar"`.
2. Se realiza un **inner join** con la tabla de Paradas.
3. Se calcula la diferencia en minutos entre `Fecha_Cierre_PQRS` y `fecha_cierre_ticket`.
4. Se seleccionan los registros donde la diferencia es **nula** (`NaN`), indicando ausencia o inconsistencia de datos.

**Retorna:**
* Variable: `error_umbrella_12`

In [101]:
val_umbrella_11 = 'DIFERENCIA DE TIEMPOS DE CIERRE (> 1 MIN)'
val_umbrella_12 = 'PARADAS ABIERTAS O FECHAS DE CIERRE NULOS'
error_umbrella_11 = ""
error_umbrella_12 = ""

if ('df_pqrsd_servicios' in locals() and not df_pqrsd_servicios.empty) and \
   ('df_paradas' in locals() and not df_paradas.empty):

    df_cerrados = df_pqrsd_servicios[df_pqrsd_servicios['Estado'] == "Cerrar"]

    df_cruce_cierre = pd.merge(
        df_cerrados,
        df_paradas,
        left_on='ID',
        right_on='uuid',
        how='inner'
    )

    df_cruce_cierre = df_cruce_cierre.fillna(False)

    columnas_deseadas = ['id_parada', 'uuid', 'idbeneficiario', 'idpqr', 'fecha_ceracion_pqrs', 'Fecha_Cierre_PQRS', 'fecha_cierre_ticket']
    df_cruce_cierre = df_cruce_cierre[columnas_deseadas]

    df_cruce_cierre['Fecha_Cierre_PQRS'] = pd.to_datetime(df_cruce_cierre['Fecha_Cierre_PQRS'], errors='coerce')
    df_cruce_cierre['fecha_cierre_ticket'] = pd.to_datetime(df_cruce_cierre['fecha_cierre_ticket'], errors='coerce')

    df_cruce_cierre['diferencia_minutos'] = ((df_cruce_cierre['Fecha_Cierre_PQRS'] - df_cruce_cierre['fecha_cierre_ticket']).dt.total_seconds() / 60)

    # ==========================================
    # VALIDACIÓN 12: PARADAS ABIERTAS / NULOS
    # ==========================================
    df_paradas_abiertas = df_cruce_cierre[df_cruce_cierre['diferencia_minutos'].isnull()].copy()

    cant_abiertas = df_paradas_abiertas.shape[0]
    df_paradas_abiertas = df_paradas_abiertas[['id_parada','uuid','idpqr','diferencia_minutos']]

    if cant_abiertas > 0:
        html_abiertas = df_paradas_abiertas.to_html(index=False)
        error_umbrella_12 = f"Total: <b>{cant_abiertas}</b> <br> {html_abiertas}"
    else:
        error_umbrella_12 = "OK - Sin Novedades"

    # ==========================================
    # VALIDACIÓN 11: DIFERENCIA DE TIEMPO
    # ==========================================

    df_calculo_diff = df_cruce_cierre.copy()
    df_calculo_diff['diferencia_minutos'] = df_calculo_diff['diferencia_minutos'].fillna(0).astype(int)

    df_diferencia_tiempo = df_calculo_diff[
        (df_calculo_diff['diferencia_minutos'] < -1) |
        (df_calculo_diff['diferencia_minutos'] > 1)
    ].copy()

    cant_diff = df_diferencia_tiempo.shape[0]
    df_diferencia_tiempo = df_diferencia_tiempo[['id_parada','uuid','idpqr','diferencia_minutos']]

    if cant_diff > 0:
        html_diff = df_diferencia_tiempo.to_html(index=False)
        error_umbrella_11 = f"Total: <b>{cant_diff}</b> <br> {html_diff}"
    else:
        error_umbrella_11 = "OK - Sin Novedades"

else:
    error_umbrella_11 = 'Sin Validación (Faltan datos)'
    error_umbrella_12 = 'Sin Validación (Faltan datos)'

print(f"--- {val_umbrella_11} ---")
print(error_umbrella_11)
print(f"--- {val_umbrella_12} ---")
print(error_umbrella_12)

--- DIFERENCIA DE TIEMPOS DE CIERRE (> 1 MIN) ---
OK - Sin Novedades
--- PARADAS ABIERTAS O FECHAS DE CIERRE NULOS ---
OK - Sin Novedades

### Validación 13 - CATEGORIA - SUBCATEGORIA - CÓDIGO_CATEGORÍA - PRIORIDAD

Verifica que la combinación de **Categoría, Subcategoría, Código y Prioridad** en los PQRSD recientes coincida con el arbol de tipificación.

**Lógica Técnica:**
1. **Referencia:** Construye una llave única concatenando las columnas correspondientes del archivo de Categorías (`df_categorias_subcategorias`).
2. **PQRSD:** Filtra los tickets creados después del `01-09-2025` y construye la misma llave única concatenando sus columnas.
3. **Validación:** Compara si la llave del PQRSD existe en el maestro de referencia utilizando `isin`.

**Retorna:**
* Tabla con `ID`, `GRUPO` y `Estado` de los registros que **no coinciden** con la referencia.
* Variable: `error_umbrella_13`

In [102]:
val_umbrella_13 = 'CATEGORIA - SUBCATEGORIA - CÓDIGO_CATEGORÍA - PRIORIDAD'
error_umbrella_13 = ""

if ('df_categorias_subcategorias' in locals() and not df_categorias_subcategorias.empty) and \
   ('df_pqrsd_servicios' in locals() and not df_pqrsd_servicios.empty):

    df_ref_categorias = df_categorias_subcategorias.copy()

    df_ref_categorias['Column 5'] = df_ref_categorias['Column 5'].fillna(0).astype(int)

    serie_concatenada_ref = (
        df_ref_categorias['Column 1'].astype(str) +
        df_ref_categorias['Column 2'].astype(str) +
        df_ref_categorias['Column 4'].astype(str) +
        df_ref_categorias['Column 5'].astype(str)
    ).str.upper()

    FECHA_CORTE_CAT = pd.Timestamp('2025-09-01 00:00:00')
    df_pqrs_filtrado = df_pqrsd_servicios[df_pqrsd_servicios['Fecha_Creacion'] > FECHA_CORTE_CAT].copy()

    df_validacion_cat = df_pqrs_filtrado[['ID', 'GRUPO', 'Estado']].copy()

    cols_concatenar = ['CATEGORIA', 'SUBCATEGORIA', 'Código_Categoría', 'PRIORIDAD']

    df_validacion_cat['Concatenar'] = df_pqrs_filtrado[cols_concatenar].apply(
        lambda x: ''.join(x.astype(str)), axis=1
    ).str.upper()

    df_validacion_cat['Es_Valido'] = df_validacion_cat['Concatenar'].isin(serie_concatenada_ref)

    df_errores_cat = df_validacion_cat[~df_validacion_cat['Es_Valido']].copy()
    df_errores_cat = df_errores_cat[['ID', 'GRUPO', 'Estado']]

    cantidad_errores = df_errores_cat.shape[0]

    if cantidad_errores > 0:
        html_tabla = df_errores_cat.to_html(index=False)
        error_umbrella_13 = f"Total: <b>{cantidad_errores}</b> <br> {html_tabla}"
    else:
        error_umbrella_13 = "OK - Sin Novedades"

else:
    error_umbrella_13 = 'Sin Validación (Faltan datos)'

print(f"--- {val_umbrella_13} ---")
print(error_umbrella_13)

--- CATEGORIA - SUBCATEGORIA - CÓDIGO_CATEGORÍA - PRIORIDAD ---
OK - Sin Novedades

### Validación 14 - SITIOS SALIENTES CON PQRSD ABIERTOS

Identifica los registros pertenecientes a grupos **"Salientes"** cuyo estado **no es "Cerrar"**.

**Lógica Técnica:**
1. Se filtra `df_pqrsd_servicios` buscando filas donde la columna `GRUPO` contenga la cadena `"saliente"` (insensible a mayúsculas/minúsculas).
2. Se seleccionan únicamente los registros cuyo `Estado` sea diferente de `"Cerrar"`.

**Retorna:**
* Tabla con `ID`, `ID_Beneficiario`, `GRUPO` y `Estado`.
* Variable: `error_umbrella_14`

In [103]:
val_umbrella_14 = 'SITIOS SALIENTES CON PQRSD ABIERTOS'
error_umbrella_14 = ""

if 'df_pqrsd_servicios' in locals() and not df_pqrsd_servicios.empty:

    mask_grupo_saliente = df_pqrsd_servicios['GRUPO'].str.contains('saliente', case=False, na=False)
    mask_estado_abierto = df_pqrsd_servicios['Estado'] != 'Cerrar'

    df_salientes_abiertos = df_pqrsd_servicios[mask_grupo_saliente & mask_estado_abierto].copy()

    cantidad_errores = df_salientes_abiertos.shape[0]

    cols_reporte = ['ID', 'ID_Beneficiario', 'GRUPO', 'Estado']

    cols_existentes = [c for c in cols_reporte if c in df_salientes_abiertos.columns]
    df_vista_reporte = df_salientes_abiertos[cols_existentes]

    if cantidad_errores > 0:
        html_tabla = df_vista_reporte.to_html(index=False)
        error_umbrella_14 = f"Total: <b>{cantidad_errores}</b> <br>{html_tabla}"
    else:
        error_umbrella_14 = "OK - Sin Novedades"

else:
    error_umbrella_14 = 'Sin Validación (Faltan datos)'

print(f"--- {val_umbrella_14} ---")
print(error_umbrella_14)

--- SITIOS SALIENTES CON PQRSD ABIERTOS ---
OK - Sin Novedades

### Validación 15 - PARADAS DE RELOJ ENERGÍA ALTERNATIVA (TICKETS ABIERTOS)

Verifica si la cantidad de paradas de tipo **"Energía Alternativa"** coincide con los días de operación del ticket para sitios con energía solar en tickets **abiertos**.

**Lógica Técnica:**
1. **Filtro Solar:** Se cruzan los PQRSD con los sitios donde `Tipo_Energia == "SOLUCION SOLAR"`.
2. **Ajuste de Fechas:** Si el ticket es anterior al mes actual, se simula que fue creado el **día 1 del mes actual a las 09:09:09** (para auditar solo el mes en curso).
3. **Cálculo Esperado vs. Real:**
   - Se cuenta el número de paradas registradas (`Conteo`).
   - Se calcula cuántas paradas deberían existir según la diferencia de días (`paradas_calculadas`), sumando penalizaciones si se creó muy temprano (`< 7 AM`) o se cerró muy tarde (`> 18 PM`).
4. **Revisión:** Se calcula `paradas_calculadas - Conteo`. Si el resultado es distinto de 0, se marca como error.

**Retorna:**
* Tickets abiertos con inconsistencias en paradas solares.
* Variable: `error_umbrella_15`


### Validación 16 - PARADAS DE RELOJ ENERGÍA ALTERNATIVA (TICKETS CERRADOS MES ACTUAL)

Verifica la misma consistencia de paradas de tipo **"Energía Alternativa"** para tickets **cerrados en el mes actual**.

**Lógica Técnica:**
Mismos pasos que en la Validación 15, aplicando el cálculo únicamente a tickets **cerrados en el mes actual**.

**Retorna:**
* Tickets cerrados con inconsistencias en paradas solares.
* Variable: `error_umbrella_16`

In [104]:
val_umbrella_15 = 'PARADAS DE RELOJ ENERGÍA ALTERNATIVA - ABIERTOS (FALTAN/SOBRAN PARADAS)'
val_umbrella_16 = 'PARADAS DE RELOJ ENERGÍA ALTERNATIVA - CERRADOS (FALTAN/SOBRAN PARADAS)'
error_umbrella_15 = ""
error_umbrella_16 = ""

if ('df_pqrsd_servicios' in locals() and not df_pqrsd_servicios.empty) and \
   ('df_sitios_activos' in locals() and not df_sitios_activos.empty) and \
   ('df_paradas' in locals() and not df_paradas.empty):

    df_puntos_solares = df_sitios_activos[['Id_Beneficiario', 'Tipo_Energia']].copy()
    df_puntos_solares = df_puntos_solares[df_puntos_solares['Tipo_Energia'] == "SOLUCION SOLAR"]
    df_puntos_solares.reset_index(drop=True, inplace=True)

    cols_pqrs = ['ID_Beneficiario','Fecha_Creacion','ID','año_fecha_Cierre','mes_fecha_Cierre','dia_fecha_Cierre','Hora_Cierre','Fecha_Cierre_PQRS','Estado']
    df_pqrs_audit = df_pqrsd_servicios[cols_pqrs].copy()
    df_pqrs_audit = df_pqrs_audit[df_pqrs_audit['Fecha_Creacion'] > "2024-09-17 00:00:00"]

    df_pqrsd_solares = pd.merge(df_pqrs_audit, df_puntos_solares, left_on='ID_Beneficiario', right_on='Id_Beneficiario', how='inner')

    # ==========================================
    # 2. LÓGICA DE FECHAS (PRIMER DÍA DEL MES)
    # ==========================================
    primer_dia_mes = datetime.today().replace(day=1).strftime('%Y-%m-%d')
    primer_dia_mes_formateado = primer_dia_mes + " 09:09:09" # String

    mask_antiguos = df_pqrsd_solares['Fecha_Creacion'] < primer_dia_mes
    df_pqrsd_solares.loc[mask_antiguos, 'Fecha_Creacion'] = pd.to_datetime(primer_dia_mes_formateado)

    df_pqrsd_solares['Hora_Creacion'] = df_pqrsd_solares['Fecha_Creacion'].dt.hour.fillna(-1).astype(int)
    df_pqrsd_solares['dia_Fecha_Creacion'] = df_pqrsd_solares['Fecha_Creacion'].dt.day.fillna(-1).astype(int)
    df_pqrsd_solares['mes_Fecha_Creacion'] = df_pqrsd_solares['Fecha_Creacion'].dt.month.fillna(-1).astype(int)
    df_pqrsd_solares['año_Fecha_Creacion'] = df_pqrsd_solares['Fecha_Creacion'].dt.year.fillna(-1).astype(int)
    df_pqrsd_solares.reset_index(drop=True, inplace=True)


    df_audit_abiertos = df_pqrsd_solares[~(df_pqrsd_solares['Estado'] == "Cerrar")].copy()
    df_audit_cerrados = df_pqrsd_solares[
        (df_pqrsd_solares['Estado'] == "Cerrar") &
        (df_pqrsd_solares['año_fecha_Cierre'] == ANIO_ACTUAL) &
        (df_pqrsd_solares['mes_fecha_Cierre'] == MES_ACTUAL)
    ].copy()

    df_paradas_energia = df_paradas[df_paradas['tipo_parada'] == "Energía Alternativa"].copy()

    df_cruce_abiertos = pd.merge(df_audit_abiertos, df_paradas_energia, left_on='ID', right_on='uuid', how='left')
    df_cruce_cerrados = pd.merge(df_audit_cerrados, df_paradas_energia, left_on='ID', right_on='uuid', how='left')

    df_cruce_abiertos.reset_index(drop=True, inplace=True)
    df_cruce_cerrados.reset_index(drop=True, inplace=True)

    cols_grp_abiertos = ['ID', 'ID_Beneficiario', 'Tipo_Energia', 'Estado', 'Fecha_Creacion', 'dia_Fecha_Creacion', 'uuid']
    df_cruce_abiertos['Conteo'] = df_cruce_abiertos.groupby(cols_grp_abiertos)['ID'].transform('count').fillna(0).astype(int)

    cols_final_abiertos = ['ID', 'ID_Beneficiario', 'Tipo_Energia', 'Estado', 'Fecha_Creacion', 'dia_Fecha_Creacion','Hora_Creacion', 'uuid','Conteo']
    df_cruce_abiertos = df_cruce_abiertos[cols_final_abiertos].copy()

    df_cruce_abiertos['paradas_calculadas'] = (NUMERO_DIA - df_cruce_abiertos['dia_Fecha_Creacion'])
    df_cruce_abiertos.loc[df_cruce_abiertos['Hora_Creacion'] < 7, 'paradas_calculadas'] += 1
    df_cruce_abiertos['revision'] = (df_cruce_abiertos['paradas_calculadas'] - df_cruce_abiertos['Conteo'])


    cols_grp_cerrados = ['ID', 'ID_Beneficiario', 'Tipo_Energia', 'Fecha_Creacion', 'dia_Fecha_Creacion','Estado','dia_fecha_Cierre','Fecha_Cierre_PQRS', 'uuid']
    df_cruce_cerrados['Conteo'] = df_cruce_cerrados.groupby(cols_grp_cerrados)['ID'].transform('count').fillna(0).astype(int)

    cols_final_cerrados = ['ID', 'ID_Beneficiario', 'Tipo_Energia', 'Fecha_Creacion', 'dia_Fecha_Creacion','Hora_Creacion','Estado','dia_fecha_Cierre','Hora_Cierre','Fecha_Cierre_PQRS', 'uuid','Conteo']
    df_cruce_cerrados = df_cruce_cerrados[cols_final_cerrados].copy()

    df_cruce_cerrados['paradas_calculadas'] = (df_cruce_cerrados['dia_fecha_Cierre'] - df_cruce_cerrados['dia_Fecha_Creacion'])
    df_cruce_cerrados.loc[df_cruce_cerrados['Hora_Creacion'] < 7, 'paradas_calculadas'] += 1
    df_cruce_cerrados.loc[df_cruce_cerrados['Hora_Cierre'] > 18, 'paradas_calculadas'] += 1
    df_cruce_cerrados['revision'] = (df_cruce_cerrados['paradas_calculadas'] - df_cruce_cerrados['Conteo'])


    df_fallas_abiertos = df_cruce_abiertos[df_cruce_abiertos['revision'] != 0].copy()
    df_fallas_abiertos = df_fallas_abiertos.groupby(cols_grp_abiertos).last().reset_index()

    total_abiertos = df_fallas_abiertos.shape[0]
    if total_abiertos > 0:
        html_ab = df_fallas_abiertos.to_html(index=False)
        error_umbrella_15 = f"Total: <b>{total_abiertos}</b> <br>{html_ab}"
    else:
        error_umbrella_15 = "OK - Sin Novedades"

    df_fallas_cerrados = df_cruce_cerrados[df_cruce_cerrados['revision'] != 0].copy()
    df_fallas_cerrados = df_fallas_cerrados.groupby(cols_grp_cerrados).last().reset_index()

    total_cerrados = df_fallas_cerrados.shape[0]
    if total_cerrados > 0:
        html_cer = df_fallas_cerrados.to_html(index=False)
        error_umbrella_16 = f"Total: <b>{total_cerrados}</b> <br>{html_cer}"
    else:
        error_umbrella_16 = "OK - Sin Novedades"

else:
    error_umbrella_15 = 'Sin Validación (Faltan datos)'
    error_umbrella_16 = 'Sin Validación (Faltan datos)'

print(f"--- {val_umbrella_15} ---")
print(error_umbrella_15)
print(f"--- {val_umbrella_16} ---")
print(error_umbrella_16)

--- PARADAS DE RELOJ ENERGÍA ALTERNATIVA - ABIERTOS (FALTAN/SOBRAN PARADAS) ---
OK - Sin Novedades
--- PARADAS DE RELOJ ENERGÍA ALTERNATIVA - CERRADOS (FALTAN/SOBRAN PARADAS) ---
OK - Sin Novedades

### Validación 17 - PQRSD DUPLICADOS CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR

Identifica los **ID_BENEFICIARIO_PQRSD** que aparecen duplicados dentro del reporte de **"Falla Exterior"**.

**Lógica Técnica:**
1. Se toma el sub-DataFrame `df_falla_ext`.
2. Se eliminan los registros con `ID_BENEFICIARIO_PQRSD` nulo.
3. Se filtran los registros duplicados utilizando `duplicated(keep=False)`.
4. Se obtiene la lista única de los IDs que se repiten.

**Retorna:**
* Tabla con los `ID_BENEFICIARIO_PQRSD` duplicados.
* Variable: `error_umbrella_17`

In [105]:
val_umbrella_17 = 'PQRSD DUPLICADOS CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR'
error_umbrella_17 = ""

if 'df_falla_ext' in locals() and not df_falla_ext.empty:

    df_duplicados_ext = df_falla_ext[['ID_BENEFICIARIO_PQRSD']].copy()

    df_duplicados_ext = df_duplicados_ext.dropna(subset=['ID_BENEFICIARIO_PQRSD'])

    mask_duplicados = df_duplicados_ext.duplicated('ID_BENEFICIARIO_PQRSD', keep=False)
    df_duplicados_ext = df_duplicados_ext[mask_duplicados]

    ids_unicos_duplicados = df_duplicados_ext['ID_BENEFICIARIO_PQRSD'].unique()

    cantidad_errores = ids_unicos_duplicados.shape[0]

    if cantidad_errores > 0:
        df_resultado = pd.DataFrame(ids_unicos_duplicados, columns=['ID_BENEFICIARIO_PQRSD'])
        html_tabla = df_resultado.to_html(index=False)
        error_umbrella_17 = f"Total: <b>{cantidad_errores}</b> <br>{html_tabla}"
    else:
        error_umbrella_17 = "OK - Sin Novedades"

else:
    error_umbrella_17 = 'Sin Validación (Faltan datos o DF vacío)'

print(f"--- {val_umbrella_17} ---")
print(error_umbrella_17)

--- PQRSD DUPLICADOS CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR ---
OK - Sin Novedades

### Validación 18 - PQRSD DUPLICADOS CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR

Identifica los **ID_BENEFICIARIO_PQRSD** que aparecen duplicados dentro del reporte de **"Falla Interior"**.

**Lógica Técnica:**
1. Se toma el sub-DataFrame `df_falla_int`.
2. Se eliminan los registros con `ID_BENEFICIARIO_PQRSD` nulo.
3. Se filtran los registros duplicados utilizando `duplicated(keep=False)`.
4. Se obtiene la lista única de los IDs que se repiten.

**Retorna:**
* Tabla con los `ID_BENEFICIARIO_PQRSD` duplicados.
* Variable: `error_umbrella_18`

In [106]:
val_umbrella_18 = 'PQRSD DUPLICADOS CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR'
error_umbrella_18 = ""

if 'df_falla_int' in locals() and not df_falla_int.empty:

    df_duplicados_int = df_falla_int[['ID_BENEFICIARIO_PQRSD']].copy()

    df_duplicados_int = df_duplicados_int.dropna(subset=['ID_BENEFICIARIO_PQRSD'])

    mask_duplicados = df_duplicados_int.duplicated('ID_BENEFICIARIO_PQRSD', keep=False)
    df_duplicados_int = df_duplicados_int[mask_duplicados]

    ids_unicos_duplicados = df_duplicados_int['ID_BENEFICIARIO_PQRSD'].unique()

    cantidad_errores = ids_unicos_duplicados.shape[0]

    if cantidad_errores > 0:
        df_resultado = pd.DataFrame(ids_unicos_duplicados, columns=['ID_BENEFICIARIO_PQRSD'])
        html_tabla = df_resultado.to_html(index=False)
        error_umbrella_18 = f"Total: <b>{cantidad_errores}</b> <br>{html_tabla}"
    else:
        error_umbrella_18 = "OK - Sin Novedades"

else:
    error_umbrella_18 = 'Sin Validación (Faltan datos o DF vacío)'

print(f"--- {val_umbrella_18} ---")
print(error_umbrella_18)

--- PQRSD DUPLICADOS CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR ---
OK - Sin Novedades

### Validación 19 - PQRSD DUPLICADOS CD-SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR  
Identifica los **ID_BENEFICIARIO_PQRSD** que aparecen duplicados dentro del reporte de **"Sin Tráfico de Internet 24 Horas AP Exterior"**.

**Lógica Técnica:**
1. Se toma el sub-DataFrame `df_ext_24h`.
2. Se eliminan los registros con `ID_BENEFICIARIO_PQRSD` nulo.
3. Se filtran los registros duplicados utilizando `duplicated(keep=False)`.
4. Se obtiene la lista única de los IDs que se repiten.

**Retorna:**
* Tabla con los `ID_BENEFICIARIO_PQRSD` duplicados.
* Variable: `error_umbrella_19`

In [107]:
val_umbrella_19 = 'PQRSD DUPLICADOS CD-SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR'
error_umbrella_19 = ""

if 'df_ext_24h' in locals() and not df_ext_24h.empty:

    df_duplicados_ext_24h = df_ext_24h[['ID_BENEFICIARIO_PQRSD']].copy()

    df_duplicados_ext_24h = df_duplicados_ext_24h.dropna(subset=['ID_BENEFICIARIO_PQRSD'])

    mask_duplicados = df_duplicados_ext_24h.duplicated('ID_BENEFICIARIO_PQRSD', keep=False)
    df_duplicados_ext_24h = df_duplicados_ext_24h[mask_duplicados]

    ids_unicos_duplicados = df_duplicados_ext_24h['ID_BENEFICIARIO_PQRSD'].unique()

    cantidad_errores = ids_unicos_duplicados.shape[0]

    if cantidad_errores > 0:
        df_resultado = pd.DataFrame(ids_unicos_duplicados, columns=['ID_BENEFICIARIO_PQRSD'])
        html_tabla = df_resultado.to_html(index=False)
        error_umbrella_19 = f"Total: <b>{cantidad_errores}</b> <br>{html_tabla}"
    else:
        error_umbrella_19 = "OK - Sin Novedades"

else:
    error_umbrella_19 = 'Sin Validación (Faltan datos o DF vacío)'

print(f"--- {val_umbrella_19} ---")
print(error_umbrella_19)

--- PQRSD DUPLICADOS CD-SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR ---
OK - Sin Novedades

### Validación 20 - PQRSD DUPLICADOS CD-SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR

Identifica los **ID_BENEFICIARIO_PQRSD** que aparecen duplicados dentro del reporte de **"Sin Tráfico de Internet 24 Horas AP Interior"**.

**Lógica Técnica:**
1. Se toma el sub-DataFrame `df_int_24h`.
2. Se eliminan los registros con `ID_BENEFICIARIO_PQRSD` nulo.
3. Se filtran los registros duplicados utilizando `duplicated(keep=False)`.
4. Se obtiene la lista única de los IDs que se repiten.

**Retorna:**
* Tabla con los `ID_BENEFICIARIO_PQRSD` duplicados.
* Variable: `error_umbrella_20`

In [108]:
val_umbrella_20 = 'PQRSD DUPLICADOS CD-SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR'
error_umbrella_20 = ""

if 'df_int_24h' in locals() and not df_int_24h.empty:

    df_duplicados_int_24h = df_int_24h[['ID_BENEFICIARIO_PQRSD']].copy()

    df_duplicados_int_24h = df_duplicados_int_24h.dropna(subset=['ID_BENEFICIARIO_PQRSD'])

    mask_duplicados = df_duplicados_int_24h.duplicated('ID_BENEFICIARIO_PQRSD', keep=False)
    df_duplicados_int_24h = df_duplicados_int_24h[mask_duplicados]

    ids_unicos_duplicados = df_duplicados_int_24h['ID_BENEFICIARIO_PQRSD'].unique()

    cantidad_errores = ids_unicos_duplicados.shape[0]

    if cantidad_errores > 0:
        df_resultado = pd.DataFrame(ids_unicos_duplicados, columns=['ID_BENEFICIARIO_PQRSD'])
        html_tabla = df_resultado.to_html(index=False)
        error_umbrella_20 = f"Total: <b>{cantidad_errores}</b> <br>{html_tabla}"
    else:
        error_umbrella_20 = "OK - Sin Novedades"

else:
    error_umbrella_20 = 'Sin Validación (Faltan datos o DF vacío)'

print(f"--- {val_umbrella_20} ---")
print(error_umbrella_20)

--- PQRSD DUPLICADOS CD-SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR ---
OK - Sin Novedades

### Validación 21 - PQRSD DUPLICADOS CD-FALLA EN EJECUCIÓN DE PRUEBA DE VELOCIDAD 5 DÍAS CALENDARIO

Identifica los **ID_BENEFICIARIO_PQRSD** que aparecen duplicados dentro del reporte de **"Falla en Ejecución de Prueba de Velocidad 5 Días Calendario"**.

**Lógica Técnica:**
1. Se toma el sub-DataFrame `df_vel_5_dias`.
2. Se eliminan los registros con `ID_BENEFICIARIO_PQRSD` nulo.
3. Se filtran los registros duplicados utilizando `duplicated(keep=False)`.
4. Se obtiene la lista única de los IDs que se repiten.

**Retorna:**
* Tabla con los `ID_BENEFICIARIO_PQRSD` duplicados.
* Variable: `error_umbrella_21`

In [109]:
val_umbrella_21 = 'PQRSD DUPLICADOS CD-FALLA EN EJECUCIÓN DE PRUEBA DE VELOCIDAD 5 DÍAS CALENDARIO'
error_umbrella_21 = ""

if 'df_vel_5_dias' in locals() and not df_vel_5_dias.empty:

    df_duplicados_vel5 = df_vel_5_dias[['ID_BENEFICIARIO_PQRSD']].copy()

    df_duplicados_vel5 = df_duplicados_vel5.dropna(subset=['ID_BENEFICIARIO_PQRSD'])

    mask_duplicados = df_duplicados_vel5.duplicated('ID_BENEFICIARIO_PQRSD', keep=False)
    df_duplicados_vel5 = df_duplicados_vel5[mask_duplicados]

    ids_unicos_duplicados = df_duplicados_vel5['ID_BENEFICIARIO_PQRSD'].unique()

    cantidad_errores = ids_unicos_duplicados.shape[0]

    if cantidad_errores > 0:
        df_resultado = pd.DataFrame(ids_unicos_duplicados, columns=['ID_BENEFICIARIO_PQRSD'])
        html_tabla = df_resultado.to_html(index=False)
        error_umbrella_21 = f"Total: <b>{cantidad_errores}</b> <br>{html_tabla}"
    else:
        error_umbrella_21 = "OK - Sin Novedades"

else:
    error_umbrella_21 = 'Sin Validación (Faltan datos o DF vacío)'

print(f"--- {val_umbrella_21} ---")
print(error_umbrella_21)

--- PQRSD DUPLICADOS CD-FALLA EN EJECUCIÓN DE PRUEBA DE VELOCIDAD 5 DÍAS CALENDARIO ---
OK - Sin Novedades

### Validación 22 - PQRSD DUPLICADOS CD-MEDICIÓN DIRECTA DE VELOCIDAD EFECTIVA DE TRANSMISIÓN DE DATOS

Identifica los **ID_BENEFICIARIO_PQRSD** que aparecen duplicados dentro del reporte de **"Medición Directa de Velocidad Efectiva de Transmisión de Datos"**.

**Lógica Técnica:**
1. Se toma el sub-DataFrame `df_vel_8_dias`.
2. Se eliminan los registros con `ID_BENEFICIARIO_PQRSD` nulo.
3. Se filtran los registros duplicados utilizando `duplicated(keep=False)`.
4. Se obtiene la lista única de los IDs que se repiten.

**Retorna:**
* Tabla con los `ID_BENEFICIARIO_PQRSD` duplicados.
* Variable: `error_umbrella_22`

In [110]:
val_umbrella_22 = 'PQRSD DUPLICADOS CD-MEDICIÓN DIRECTA DE VELOCIDAD EFECTIVA DE TRANSMISIÓN DE DATOS'
error_umbrella_22 = ""

if 'df_vel_8_dias' in locals() and not df_vel_8_dias.empty:

    df_duplicados_vel8 = df_vel_8_dias[['ID_BENEFICIARIO_PQRSD']].copy()

    df_duplicados_vel8 = df_duplicados_vel8.dropna(subset=['ID_BENEFICIARIO_PQRSD'])

    mask_duplicados = df_duplicados_vel8.duplicated('ID_BENEFICIARIO_PQRSD', keep=False)
    df_duplicados_vel8 = df_duplicados_vel8[mask_duplicados]

    ids_unicos_duplicados = df_duplicados_vel8['ID_BENEFICIARIO_PQRSD'].unique()

    cantidad_errores = ids_unicos_duplicados.shape[0]

    if cantidad_errores > 0:
        df_resultado = pd.DataFrame(ids_unicos_duplicados, columns=['ID_BENEFICIARIO_PQRSD'])
        html_tabla = df_resultado.to_html(index=False)
        error_umbrella_22 = f"Total: <b>{cantidad_errores}</b> <br>{html_tabla}"
    else:
        error_umbrella_22 = "OK - Sin Novedades"

else:
    error_umbrella_22 = 'Sin Validación (Faltan datos o DF vacío)'

print(f"--- {val_umbrella_22} ---")
print(error_umbrella_22)

--- PQRSD DUPLICADOS CD-MEDICIÓN DIRECTA DE VELOCIDAD EFECTIVA DE TRANSMISIÓN DE DATOS ---
OK - Sin Novedades

### Validación 23 - CD-SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR - CON PARADA DE DIAGNÓSTICO

Identifica las **PQRSD** de la subcategoría **"CD-SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR"** creadas después del **01 de septiembre de 2025** que tienen paradas de reloj tipo **"Diagnostico"**.

**Lógica Técnica:**
1. **Filtrado de Paradas:** Se seleccionan los registros de `df_paradas` donde el campo `tipo_parada` contenga el texto **"Diagnostico"**.
2. **Filtrado de PQRSD:** Se filtran los registros de `df_pqrsd_servicios` bajo la subcategoría específica y con `Fecha_Creacion` posterior a **2025-09-01**.
3. **Cruce de Información:** Se realiza un **Inner Join** entre ambos sub-DataFrames utilizando los campos `ID` (de PQRSD) y `uuid` (de paradas) como llaves de unión.
4. **Consolidación:** Se genera una tabla final que integra los detalles de la PQRSD con las fechas de inicio (`dateparada`) y fin (`finishparada`) de la parada técnica.

**Retorna:**
* Tabla con los campos: `ID`, `ID_Beneficiario`, `GRUPO`, `SUBCATEGORIA`, `Fecha_Creacion`, `dateparada`, `finishparada` y `tipo_parada`.
* Variable: `val_umbrella_23`

In [111]:
val_umbrella_23 = 'CD-SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR - CON PARADA DE DIAGNÓSTICO 8 DIAS O 8 HORAS'
error_umbrella_23 = ""

if 'df_paradas' in locals() and 'df_pqrsd_servicios' in locals():

    paradas_diagnostico = df_paradas.copy()
    paradas_diagnostico = paradas_diagnostico[paradas_diagnostico['tipo_parada'].str.contains('Diagnostico', na=False)]

    pqrs_alerta_interior = df_pqrsd_servicios.copy()
    pqrs_alerta_interior = pqrs_alerta_interior[
        (pqrs_alerta_interior['SUBCATEGORIA'] == 'CD-SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR') &
        (pqrs_alerta_interior['Fecha_Creacion'] > '2025-09-01')
    ]

    df_resultado_final = pd.merge(
        pqrs_alerta_interior[['ID', 'ID_Beneficiario', 'GRUPO', 'SUBCATEGORIA', 'Fecha_Creacion']],
        paradas_diagnostico[['uuid', 'dateparada', 'finishparada', 'tipo_parada']],
        left_on='ID',
        right_on='uuid',
        how='inner'
    )

    cantidad_errores = df_resultado_final.shape[0]

    if cantidad_errores > 0:
        columnas_reporte = ['ID', 'ID_Beneficiario', 'GRUPO', 'SUBCATEGORIA', 'Fecha_Creacion', 'dateparada', 'finishparada', 'tipo_parada']
        html_tabla = df_resultado_final[columnas_reporte].to_html(index=False, classes='table table-striped')
        error_umbrella_23 = f"Total: <b>{cantidad_errores}</b> <br>{html_tabla}"
    else:
        error_umbrella_23 = "OK - Sin Novedades"

else:
    error_umbrella_23 = 'Sin Validación'

print(f"--- {val_umbrella_23} ---")
print(error_umbrella_23)

--- CD-SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR - CON PARADA DE DIAGNÓSTICO 8 DIAS O 8 HORAS ---
OK - Sin Novedades

### Validación 24 - CD-SIN TRÁFICO DE INTERNET 24 HORAS AP EEXTERIOR - CON PARADA DE DIAGNÓSTICO

Identifica las **PQRSD** de la subcategoría **"CD-SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR"** creadas después del **01 de septiembre de 2025** que tienen paradas de reloj tipo **"Diagnostico"**.

**Lógica Técnica:**
1. **Filtrado de Paradas:** Se seleccionan los registros de `df_paradas` donde el campo `tipo_parada` contenga el texto **"Diagnostico"**.
2. **Filtrado de PQRSD:** Se filtran los registros de `df_pqrsd_servicios` bajo la subcategoría específica y con `Fecha_Creacion` posterior a **2025-09-01**.
3. **Cruce de Información:** Se realiza un **Inner Join** entre ambos sub-DataFrames utilizando los campos `ID` (de PQRSD) y `uuid` (de paradas) como llaves de unión.
4. **Consolidación:** Se genera una tabla final que integra los detalles de la PQRSD con las fechas de inicio (`dateparada`) y fin (`finishparada`) de la parada técnica.

**Retorna:**
* Tabla con los campos: `ID`, `ID_Beneficiario`, `GRUPO`, `SUBCATEGORIA`, `Fecha_Creacion`, `dateparada`, `finishparada` y `tipo_parada`.
* Variable: `val_umbrella_24`

In [112]:
val_umbrella_24 = 'CD-SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR - CON PARADA DE DIAGNÓSTICO 8 DIAS O 8 HORAS'
error_umbrella_24 = ""

if 'df_paradas' in locals() and 'df_pqrsd_servicios' in locals():

    paradas_diagnostico = df_paradas.copy()
    paradas_diagnostico = paradas_diagnostico[paradas_diagnostico['tipo_parada'].str.contains('Diagnostico', na=False)]

    pqrs_alerta_exterior = df_pqrsd_servicios.copy()
    pqrs_alerta_exterior = pqrs_alerta_exterior[
        (pqrs_alerta_exterior['SUBCATEGORIA'] == 'CD-SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR') &
        (pqrs_alerta_exterior['Fecha_Creacion'] > '2025-09-01')
    ]

    df_resultado_final = pd.merge(
        pqrs_alerta_exterior[['ID', 'ID_Beneficiario', 'GRUPO', 'SUBCATEGORIA', 'Fecha_Creacion']],
        paradas_diagnostico[['uuid', 'dateparada', 'finishparada', 'tipo_parada']],
        left_on='ID',
        right_on='uuid',
        how='inner'
    )

    cantidad_errores = df_resultado_final.shape[0]

    if cantidad_errores > 0:
        columnas_reporte = ['ID', 'ID_Beneficiario', 'GRUPO', 'SUBCATEGORIA', 'Fecha_Creacion', 'dateparada', 'finishparada', 'tipo_parada']
        html_tabla = df_resultado_final[columnas_reporte].to_html(index=False, classes='table table-striped')
        error_umbrella_24 = f"Total: <b>{cantidad_errores}</b> <br>{html_tabla}"
    else:
        error_umbrella_24 = "OK - Sin Novedades"

else:
    error_umbrella_24 = 'Sin Validación'

print(f"--- {val_umbrella_24} ---")
print(error_umbrella_24)

--- CD-SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR - CON PARADA DE DIAGNÓSTICO 8 DIAS O 8 HORAS ---
OK - Sin Novedades

### Validación 25 - CD-FALLA EN EJECUCIÓN DE PRUEBA DE VELOCIDAD 5 DÍAS CALENDARIO - CON PARADA DE DIAGNÓSTICO

Identifica las **PQRSD** de la subcategoría **"CD-FALLA EN EJECUCIÓN DE PRUEBA DE VELOCIDAD 5 DÍAS CALENDARIO"** creadas después del **01 de septiembre de 2025** que tienen paradas de reloj tipo **"Diagnostico"**.

**Lógica Técnica:**
1. **Filtrado de Paradas:** Se seleccionan los registros de `df_paradas` donde el campo `tipo_parada` contenga el texto **"Diagnostico"**.
2. **Filtrado de PQRSD:** Se filtran los registros de `df_pqrsd_servicios` bajo la subcategoría específica y con `Fecha_Creacion` posterior a **2025-09-01**.
3. **Cruce de Información:** Se realiza un **Inner Join** entre ambos sub-DataFrames utilizando los campos `ID` (de PQRSD) y `uuid` (de paradas) como llaves de unión.
4. **Consolidación:** Se genera una tabla final que integra los detalles de la PQRSD con las fechas de inicio (`dateparada`) y fin (`finishparada`) de la parada técnica.

**Retorna:**
* Tabla con los campos: `ID`, `ID_Beneficiario`, `GRUPO`, `SUBCATEGORIA`, `Fecha_Creacion`, `dateparada`, `finishparada` y `tipo_parada`.
* Variable: `val_umbrella_25`

In [113]:
val_umbrella_25 = 'CD-FALLA EN EJECUCIÓN DE PRUEBA DE VELOCIDAD 5 DÍAS CALENDARIO - CON PARADA DE DIAGNÓSTICO 8 DIAS O 8 HORAS'
error_umbrella_25 = ""

if 'df_paradas' in locals() and 'df_pqrsd_servicios' in locals():

    paradas_diagnostico = df_paradas.copy()
    paradas_diagnostico = paradas_diagnostico[paradas_diagnostico['tipo_parada'].str.contains('Diagnostico', na=False)]

    #pqrs_alerta_5_dias = df_pqrsd_servicios.copy()
    #pqrs_alerta_5_dias = pqrs_alerta_5_dias[
    #    (pqrs_alerta_5_dias['SUBCATEGORIA'] == 'CD-FALLA EN EJECUCIÓN DE PRUEBA DE VELOCIDAD 5 DÍAS CALENDARIO') &
    #    (pqrs_alerta_5_dias['Fecha_Creacion'] > '2025-09-01')
    #]

    df_resultado_final = pd.merge(
        df_vel_5_dias[['ID', 'ID_BENEFICIARIO_PQRSD','SUBCATEGORIA', 'ESTADO_PQRSD']],
        paradas_diagnostico[['uuid', 'dateparada', 'finishparada', 'tipo_parada']],
        left_on='ID',
        right_on='uuid',
        how='inner'
    )

    cantidad_errores = df_resultado_final.shape[0]

    if cantidad_errores > 0:
        columnas_reporte = ['ID', 'ID_Beneficiario', 'SUBCATEGORIA','dateparada', 'finishparada', 'tipo_parada','Estado']
        html_tabla = df_resultado_final[columnas_reporte].to_html(index=False, classes='table table-striped')
        error_umbrella_25 = f"Total: <b>{cantidad_errores}</b> <br>{html_tabla}"
    else:
        error_umbrella_25 = "OK - Sin Novedades"

else:
    error_umbrella_25 = 'Sin Validación'

print(f"--- {val_umbrella_25} ---")
print(error_umbrella_25)

--- CD-FALLA EN EJECUCIÓN DE PRUEBA DE VELOCIDAD 5 DÍAS CALENDARIO - CON PARADA DE DIAGNÓSTICO 8 DIAS O 8 HORAS ---
OK - Sin Novedades

### Validación 26 - CD-PQRSD FALLA DE VELOCIDAD SIN ALERTA DE VELOCIDAD

In [114]:
val_umbrella_26 = 'CD-PQRSD FALLA DE VELOCIDAD SIN ALERTA DE VELOCIDAD'
error_umbrella_26 = ""

df_solo_fallas = df_vel_8_dias[
    ~df_vel_8_dias["ID_BENEFICIARIO_PQRSD"].isin(df_vel_5_dias["ID_BENEFICIARIO_PQRSD"])
]
cantidad_errores = df_solo_fallas.shape[0]


if cantidad_errores > 0:
        columnas_reporte = ['ID', 'ID_BENEFICIARIO_PQRSD', 'SUBCATEGORIA']
        html_tabla = df_resultado_final[columnas_reporte].to_html(index=False, classes='table table-striped')
        error_umbrella_26 = f"Total: <b>{cantidad_errores}</b> <br>{html_tabla}"
else:
        error_umbrella_26 = "OK - Sin Novedades"

print(f"--- {val_umbrella_26} ---")
print(error_umbrella_26)

--- CD-PQRSD FALLA DE VELOCIDAD SIN ALERTA DE VELOCIDAD ---
Total: <b>14</b> <br><table border="1" class="dataframe table table-striped">
  <thead>
    <tr style="text-align: right;">
      <th>ID</th>
      <th>ID_BENEFICIARIO_PQRSD</th>
      <th>SUBCATEGORIA</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

### Validación 27 - CD-PQRSD FALLA DE TRAFICO SIN ALERTA DE TRAFICO

In [115]:
val_umbrella_27 = 'CD-PQRSD FALLA DE TRAFICO SIN ALERTA DE TRAFICO'
error_umbrella_27 = ""

df_solo_fallas_ext = df_falla_ext[
    ~df_falla_ext["ID_BENEFICIARIO_PQRSD"].isin(df_ext_24h["ID_BENEFICIARIO_PQRSD"])
]

df_solo_fallas_int = df_falla_int[
    ~df_falla_int["ID_BENEFICIARIO_PQRSD"].isin(df_int_24h["ID_BENEFICIARIO_PQRSD"])
]
df_consolidado_fallas = pd.merge(df_solo_fallas_ext, df_solo_fallas_int)
cantidad_errores = df_consolidado_fallas.shape[0]

if cantidad_errores > 0:
        columnas_reporte = ['ID', 'ID_Beneficiario', 'SUBCATEGORIA']
        html_tabla = df_resultado_final[columnas_reporte].to_html(index=False, classes='table table-striped')
        error_umbrella_27 = f"Total: <b>{cantidad_errores}</b> <br>{html_tabla}"
else:
        error_umbrella_27 = "OK - Sin Novedades"

print(f"--- {val_umbrella_27} ---")
print(error_umbrella_27)

--- CD-PQRSD FALLA DE TRAFICO SIN ALERTA DE TRAFICO ---
OK - Sin Novedades

### Validación 28 - REVISION CONTADOR APARTIR DE ALERTA DE VELOCIDAD

In [116]:
df_vel_5_dias.head()

,ID,ID_BENEFICIARIO_PQRSD,CATEGORIA,SUBCATEGORIA,ESTADO_PQRSD,FECHA_CREACION
105,F3E811-3D0C6F,24475,CD-CENTROS DE GESTIÓN SERVICIO,CD-FALLA EN EJECUCIÓN DE PRUEBA DE VELOCIDAD 5...,Asignado Mesa de Ayuda,2026-03-12 06:18:14
107,E1CE5C-BF2D83,25619,CD-CENTROS DE GESTIÓN SERVICIO,CD-FALLA EN EJECUCIÓN DE PRUEBA DE VELOCIDAD 5...,Asignado Mesa de Ayuda,2026-03-12 06:18:11
110,AA7976-CD23A5,33376,CD-CENTROS DE GESTIÓN SERVICIO,CD-FALLA EN EJECUCIÓN DE PRUEBA DE VELOCIDAD 5...,Asignado Mesa de Ayuda,2026-03-12 06:18:08
112,4CC085-D2DDB8,25157,CD-CENTROS DE GESTIÓN SERVICIO,CD-FALLA EN EJECUCIÓN DE PRUEBA DE VELOCIDAD 5...,Asignado Mesa de Ayuda,2026-03-12 06:18:05
117,9FDA21-834580,70597,CD-CENTROS DE GESTIÓN SERVICIO,CD-FALLA EN EJECUCIÓN DE PRUEBA DE VELOCIDAD 5...,Asignado Mesa de Ayuda,2026-03-12 06:17:59

In [120]:
val_umbrella_28 = 'CD-PQRSD NO TIENE FALLA PERO SEGUN ALERTA DEBERIA TENER'
error_umbrella_28 = ""

df_vel_5_dias_filtrado = df_vel_5_dias[df_vel_5_dias['ESTADO_PQRSD'] != 'Cerrar']
df_vel_5_dias_filtrado['contador_manual'] = (hoy - pd.to_datetime(df_vel_5_dias_filtrado['FECHA_CREACION'])).dt.days
df_filtrado_alerta_debe_tener_falla = df_vel_5_dias_filtrado[df_vel_5_dias_filtrado["contador_manual"] >= 6]
df_filtrado_falla= df_vel_8_dias[df_vel_8_dias['ESTADO_PQRSD'] != 'Cerrar']

df_consolidado_fallas = df_filtrado_alerta_debe_tener_falla[
    ~df_filtrado_alerta_debe_tener_falla["ID_BENEFICIARIO_PQRSD"].isin(df_filtrado_falla["ID_BENEFICIARIO_PQRSD"])]
cantidad_errores = df_consolidado_fallas.shape[0]

if cantidad_errores > 0:
        columnas_reporte = ['ID', 'ID_BENEFICIARIO_PQRSD', 'SUBCATEGORIA']
        html_tabla = df_resultado_final[columnas_reporte].to_html(index=False, classes='table table-striped')
        error_umbrella_28 = f"Total: <b>{cantidad_errores}</b> <br>{html_tabla}"
else:
        error_umbrella_28 = "OK - Sin Novedades"

print(f"--- {val_umbrella_28} ---")
print(error_umbrella_28)

--- CD-PQRSD NO TIENE FALLA PERO SEGUN ALERTA DEBERIA TENER ---
OK - Sin Novedades

## Validaciones Umbrella vs Datawifi

### Validación 1 - CREACIÓN DIARIA (UMBRELLA VS DATAWIFI)

Compara la cantidad de tickets enviados por **DataWifi** (según su log) con la cantidad de tickets realmente creados en **Umbrella** por el usuario API en el día actual.

**Lógica Técnica:**
1. Convierte las fechas de creación a formato texto `'YYYY-MM-DD'` en ambos DataFrames.
2. Filtra **DataWifi** seleccionando únicamente los registros correspondientes a la **fecha de hoy**.
3. Filtra **Umbrella** seleccionando registros de la **fecha de hoy** donde `Usuario_Creador == 'DATAWIFI.API'`.
4. Compara los totales obtenidos en ambos sistemas.

**Retorna:**
* Mensaje indicando la diferencia y los conteos de cada lado.
* Variable: `error_umbre_datawifi_1`

In [121]:
val_umbre_datawifi_1 = 'CREACIÓN DIARIA (UMBRELLA VS NETADVISOR)'
error_umbre_datawifi_1 = ""

if ('df_pqrsd_servicios' in locals() and not df_pqrsd_servicios.empty) and \
   ('df_log_netadvisor' in locals() and not df_log_netadvisor.empty):

    df_umbrella_temp = df_pqrsd_servicios.copy()
    df_netadvisor_temp = df_log_netadvisor.copy()

    fecha_validacion_str = FECHA_HOY_DATE.strftime('%Y-%m-%d')

    df_umbrella_temp['Fecha_Creacion'] = pd.to_datetime(df_umbrella_temp['Fecha_Creacion'])
    df_umbrella_temp['Fecha_Str'] = df_umbrella_temp['Fecha_Creacion'].dt.strftime('%Y-%m-%d')

    col_fecha_net = 'FECHA DE CREACIÓN'
    if col_fecha_net in df_netadvisor_temp.columns:
        df_netadvisor_temp[col_fecha_net] = pd.to_datetime(df_netadvisor_temp[col_fecha_net])
        df_netadvisor_temp['Fecha_Str'] = df_netadvisor_temp[col_fecha_net].dt.strftime('%Y-%m-%d')
    else:
        pass

    df_netadvisor_hoy = df_netadvisor_temp[df_netadvisor_temp['Fecha_Str'] == fecha_validacion_str]

    df_umbrella_hoy = df_umbrella_temp[
        (df_umbrella_temp['Fecha_Str'] == fecha_validacion_str) &
        (df_umbrella_temp['Usuario_Creador'] == 'DATAWIFI.API')
    ]

    conteo_netadvisor = df_netadvisor_hoy.shape[0]
    conteo_umbrella = df_umbrella_hoy.shape[0]
    diferencia = conteo_netadvisor - conteo_umbrella

    if conteo_umbrella != conteo_netadvisor:
        error_umbre_datawifi_1 = (f"Diferencia: <b>{diferencia}</b> <br>"
                                  f"Enviadas Netadvisor: <b>{conteo_netadvisor}</b> <br>"
                                  f"Creadas Umbrella: <b>{conteo_umbrella}</b>")
    else:
        error_umbre_datawifi_1 = (f"OK, Sin Novedades <br>"
                                  f"Enviadas Netadvisor: <b>{conteo_netadvisor}</b> <br>"
                                  f"Creadas Umbrella: <b>{conteo_umbrella}</b>")

else:
    error_umbre_datawifi_1 = "Sin Validación (Faltan datos de Umbrella o Netadvisor)"

print(f"--- {val_umbre_datawifi_1} ---")
print(error_umbre_datawifi_1)

--- CREACIÓN DIARIA (UMBRELLA VS NETADVISOR) ---
OK, Sin Novedades <br>Enviadas Netadvisor: <b>184</b> <br>Creadas Umbrella: <b>184</b>

### Validación 2 - ESTADOS (UMBRELLA VS NETADVISOR)

Verifica que el **estado del ticket en Umbrella** coincida con el estado reportado en el log de **Netadvisor/DataWifi**, normalizando los estados de Umbrella para que sean comparables.

**Lógica Técnica:**
1. **Normalización Umbrella:**
   - `'Cerrar'` → `'Cerrado'`
   - `'Agendar'` → `'Abierto'`
   - `'Asignado Mesa de Ayuda'` → `'Abierto'`
2. **Cruce:** Realiza un **inner join** entre `df_pqrsd_servicios` y `df_log_netadvisor` por `ID_PQR`.
3. **Comparación:** Filtra los registros donde `Estado_Umbrella != Estado_Netadvisor`.

**Retorna:**
* Tabla con las ddiferencias de estado entre Umbrella y Netadvisor/DataWifi.
* Variable: `error_umbre_datawifi_2`

In [122]:
val_umbre_datawifi_2 = 'ESTADOS (UMBRELLA VS NETADVISOR)'
error_umbre_datawifi_2 = ""

if ('df_pqrsd_servicios' in locals() and not df_pqrsd_servicios.empty) and \
   ('df_log_netadvisor' in locals() and not df_log_netadvisor.empty):

    df_umbrella_temp = df_pqrsd_servicios.copy()
    df_netadvisor_temp = df_log_netadvisor.copy()

    mapa_estados = {
        'Cerrar': 'Cerrado',
        'Agendar': 'Abierto',
        'Asignado Mesa de Ayuda': 'Abierto'
    }
    df_umbrella_temp['Estado'] = df_umbrella_temp['Estado'].replace(mapa_estados)

    df_cruce_estados = pd.merge(
        df_umbrella_temp,
        df_netadvisor_temp,
        how='inner',
        left_on='ID',
        right_on='PQR'
    )

    df_cruce_estados['Estado'] = df_cruce_estados['Estado'].astype(str).str.strip()
    df_cruce_estados['STATUS'] = df_cruce_estados['STATUS'].astype(str).str.strip()

    df_diferencias = df_cruce_estados[df_cruce_estados['Estado'] != df_cruce_estados['STATUS']].copy()

    df_diferencias = df_diferencias.rename(columns={
        'Estado': 'Estado_Umbrella',
        'Fecha_Cierre_PQRS': 'Fecha_Cierre_PQRS_Umbrella',
        'STATUS': 'Estado_Datawifi',
        'FECHA DE CIERRE': 'Fecha_Cierre_PQRS_Datawifi',
        'PQR': 'PQRS'
    })

    cols_reporte = [
        'ID_Beneficiario', 'GRUPO', 'ID',
        'Estado_Umbrella', 'Estado_Datawifi',
        'Fecha_Cierre_PQRS_Umbrella', 'Fecha_Cierre_PQRS_Datawifi'
    ]

    cols_existentes = [c for c in cols_reporte if c in df_diferencias.columns]
    df_vista_reporte = df_diferencias[cols_existentes]

    total_diferencias = df_vista_reporte.shape[0]

    if total_diferencias > 0:
        html_tabla = df_vista_reporte.to_html(index=False)
        error_umbre_datawifi_2 = f"Total: <b>{total_diferencias}</b> <br>{html_tabla}"
    else:
        error_umbre_datawifi_2 = "OK - Sin Novedades"

else:
    error_umbre_datawifi_2 = "Sin Validación (Faltan datos)"

print(f"--- {val_umbre_datawifi_2} ---")
print(error_umbre_datawifi_2)

--- ESTADOS (UMBRELLA VS NETADVISOR) ---
Total: <b>4</b> <br><table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>ID_Beneficiario</th>
      <th>GRUPO</th>
      <th>ID</th>
      <th>Estado_Umbrella</th>
      <th>Estado_Datawifi</th>
      <th>Fecha_Cierre_PQRS_Umbrella</th>
      <th>Fecha_Cierre_PQRS_Datawifi</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>23072</td>
      <td>1B</td>
      <td>90AD9B-10B24B</td>
      <td>Cerrado</td>
      <td>Abierto</td>
      <td>2026-03-12 08:48:07</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>50759</td>
      <td>GRUPO 3</td>
      <td>33836D-C6B00A</td>
      <td>Cerrado</td>
      <td>Abierto</td>
      <td>2026-03-12 08:42:33</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>23072</td>
      <td>1B</td>
      <td>EED9EC-027786</td>
      <td>Cerrado</td>
      <td>Abierto</td>
      <td>2026-03-12 08:48:08</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>50759</td>
      <td>GRUPO 3</td>
      <td>D8A5A4-D58A70</td>
      <td>Cerrado</td>
      <td>Abierto</td>
      <td>2026-03-12 08:42:34</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>

### Validación 3 - ESTADOS (DATAWIFI VS UMBRELLA)

Verifica que el **estado del ticket en DataWifi** coincida con el estado **Umbrella**, normalizando los estados de Umbrella para que sean comparables.

**Lógica Técnica:**
1. Realiza un **inner join** entre `df_log_datawifi` y `df_pqrsd_servicios` por `ID_PQR`.
2. Compara los estados en ambos sistemas (`Estado_DataWifi` vs `Estado_Umbrella`).
3. Filtra los registros donde los estados no coinciden, identificando las discrepancias.

**Retorna:**
* Tabla con las discrepancias de estado entre DataWifi y Umbrella.
* Variable: `error_umbre_datawifi_3`

In [123]:
val_umbre_datawifi_3 = 'ESTADOS (DATAWIFI VS UMBRELLA)'
error_umbre_datawifi_3 = ""

if ('df_pqrsd_servicios' in locals() and not df_pqrsd_servicios.empty) and \
   ('df_log_netadvisor' in locals() and not df_log_netadvisor.empty):

    df_dw_temp = df_log_netadvisor.copy()
    df_umbrella_temp = df_pqrsd_servicios.copy()

    mapa_estados = {
        'Cerrar': 'Cerrado',
        'Agendar': 'Abierto',
        'Asignado Mesa de Ayuda': 'Abierto'
    }
    df_umbrella_temp['Estado'] = df_umbrella_temp['Estado'].replace(mapa_estados)

    df_merge_estados = pd.merge(
        df_dw_temp,
        df_umbrella_temp,
        how='inner',
        left_on='PQR',
        right_on='ID'
    )

    mask_diferencia = df_merge_estados['Estado'] != df_merge_estados['STATUS']
    df_diferencias = df_merge_estados[mask_diferencia].copy()


    df_diferencias = df_diferencias.rename(columns={
        'Estado': 'Estado_Umbrella',
        'Fecha_Cierre_PQRS': 'Fecha_Cierre_PQRS_Umbrella',
        'STATUS': 'Estado_Datawifi',
        'FECHA DE CIERRE': 'Fecha_Cierre_PQRS_Datawifi',
        'PQR': 'PQRS'
    })

    cols_reporte = [
        'ID_Beneficiario', 'GRUPO', 'ID',
        'Estado_Umbrella', 'Estado_Datawifi',
        'Fecha_Cierre_PQRS_Umbrella', 'Fecha_Cierre_PQRS_Datawifi'
    ]

    cols_finales = [c for c in cols_reporte if c in df_diferencias.columns]
    df_vista = df_diferencias[cols_finales]

    total_errores = df_vista.shape[0]

    if total_errores > 0:
        html_tabla = df_vista.to_html(index=False)
        error_umbre_datawifi_3 = f"Total: <b>{total_errores}</b> <br>{html_tabla}"
    else:
        error_umbre_datawifi_3 = "OK - Sin Novedades"

else:
    error_umbre_datawifi_3 = "Sin Validación (Faltan datos)"

print(f"--- {val_umbre_datawifi_3} ---")
print(error_umbre_datawifi_3)

--- ESTADOS (DATAWIFI VS UMBRELLA) ---
Total: <b>4</b> <br><table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>ID_Beneficiario</th>
      <th>GRUPO</th>
      <th>ID</th>
      <th>Estado_Umbrella</th>
      <th>Estado_Datawifi</th>
      <th>Fecha_Cierre_PQRS_Umbrella</th>
      <th>Fecha_Cierre_PQRS_Datawifi</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>23072</td>
      <td>1B</td>
      <td>90AD9B-10B24B</td>
      <td>Cerrado</td>
      <td>Abierto</td>
      <td>2026-03-12 08:48:07</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>50759</td>
      <td>GRUPO 3</td>
      <td>33836D-C6B00A</td>
      <td>Cerrado</td>
      <td>Abierto</td>
      <td>2026-03-12 08:42:33</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>23072</td>
      <td>1B</td>
      <td>EED9EC-027786</td>
      <td>Cerrado</td>
      <td>Abierto</td>
      <td>2026-03-12 08:48:08</td>
      <td>NaN</td>
    </tr>
    <tr>
      <td>50759</td>
      <td>GRUPO 3</td>
      <td>D8A5A4-D58A70</td>
      <td>Cerrado</td>
      <td>Abierto</td>
      <td>2026-03-12 08:42:34</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>

### Validación 4 - FALLA EXTERIOR SIN PQRSD CON CONTADOR
Identifica sitios activos que **tienen tráfico registrado por el contador** pero **no tienen ticket de falla exterior**.

**Lógica Técnica:**
1. Se cruzan los datos de **falla exterior** (`df_falla_ext`) con los registros de contadores (`df_contadores_outdoor`).
2. Se filtran los sitios donde **NO existe PQRSD** pero **sí hay contador activo** (`Tráfico > 0`).
3. Se obtiene la lista de sitios que cumplen esta condición.

**Retorna:**
* Variable: `error_umbre_datawifi_4`


### Validación 5 - FALLA EXTERIOR CON PQRSD PERO SIN CONTADOR

Identifica sitios que **tienen ticket de falla exterior** pero **no aparecen en el listado de contadores con tráfico > 8 días**.

**Lógica Técnica:**
1. Se cruzan los datos de **falla exterior** (`df_falla_ext`) con los registros de contadores (`df_contadores_outdoor`).
2. Se filtran los sitios donde **existe PQRSD** pero **no hay contador activo suficiente** (`Tráfico ≤ 0` o ausente).
3. Se obtiene la lista de sitios que cumplen esta condición.

**Retorna:**
* Variable: `error_umbre_datawifi_5`

In [124]:
val_umbre_datawifi_4 = 'FALLA VELOCIDAD 5 DIAS: TIENE CONTADOR - NO TIENE PQRSD'
val_umbre_datawifi_4_1 = 'FALLA VELOCIDAD 5 DIAS: TIENE PQRSD - NO TIENE CONTADOR'
error_umbre_datawifi_4 = ""
error_umbre_datawifi_4_1 = ""


if ('df_vel_5_dias' in locals() and not df_vel_5_dias.empty) and \
   ('df_cont_vel_5_dias' in locals()) and \
   ('df_base_sitios' in locals() and not df_base_sitios.empty):

    df_falla_temp = df_vel_5_dias.copy()

    if df_cont_vel_5_dias.empty:
        df_cont_temp = pd.DataFrame(columns=['TELEPUERTO', 'ZONA', 'DISPOSITIVO','DIAS SIN MEDICION'])
    else:
        df_cont_temp = df_cont_vel_5_dias.copy()

    df_sitios_temp = df_base_sitios.copy()

    df_falla_temp['ID_BENEFICIARIO_PQRSD'] = (df_falla_temp['ID_BENEFICIARIO_PQRSD'].astype(str))
    df_cont_temp['DISPOSITIVO'] = (df_cont_temp['DISPOSITIVO'].astype(str))
    df_sitios_temp['ID_BENEFICIARIO_SITIOS'] = (df_sitios_temp['ID_BENEFICIARIO_SITIOS'].astype(str))

    df_cruce_vel = pd.merge(
        df_falla_temp,
        df_cont_temp,
        how='outer',
        left_on='ID_BENEFICIARIO_PQRSD',
        right_on='DISPOSITIVO'
    )

    df_cruce_vel = pd.merge(
        df_cruce_vel,
        df_sitios_temp,
        how='left',
        left_on='DISPOSITIVO',
        right_on='ID_BENEFICIARIO_SITIOS',
        suffixes=('', '_SITIO')
    )

    def validar_cruce(row):
        if pd.isna(row['ID_BENEFICIARIO_PQRSD']) and not pd.isna(row['DISPOSITIVO']):
            return 'NO TIENE PQRSD - TIENE CONTADOR'
        return ''

    def validar_cruce_inverso(row):
        if pd.isna(row['DISPOSITIVO']) and not pd.isna(row['ID_BENEFICIARIO_PQRSD']):
            return 'TIENE PQRSD - NO TIENE CONTADOR'
        return ''

    df_cruce_vel['CRUCE'] = df_cruce_vel.apply(validar_cruce, axis=1)
    df_cruce_vel['CRUCE INVERSO'] = df_cruce_vel.apply(validar_cruce_inverso, axis=1)

    cols_interes = [
        'ID_BENEFICIARIO_PQRSD',
        'DISPOSITIVO',
        'CRUCE',
        'DIAS SIN MEDICION',
        'ESTADO_SITIO',
        'CRUCE INVERSO'
    ]


    cols_existentes = [c for c in cols_interes if c in df_cruce_vel.columns]
    df_cruce_vel = df_cruce_vel[cols_existentes]

#    if 'ID_BENEFICIARIO_PQRSD' in df_cruce_vel.columns:
#        df_cruce_vel['ID_BENEFICIARIO_PQRSD'] = df_cruce_vel['ID_BENEFICIARIO_PQRSD'].astype('Int64')
#    if 'IDENTIFICADOR BENEFICIARIO CONTADOR' in df_cruce_vel.columns:
#        df_cruce_vel['IDENTIFICADOR BENEFICIARIO CONTADOR'] = df_cruce_vel['IDENTIFICADOR BENEFICIARIO CONTADOR'].astype('Int64')

    estados_activos = ['ACTIVO', 'SI; EN REINSTALACION', 'SI; EN REUBICACION']

    mask_val4 = (df_cruce_vel['ESTADO_SITIO'].isin(estados_activos)) & (df_cruce_vel['CRUCE'] != '')
    df_error_40 = df_cruce_vel[mask_val4].copy()

    if df_error_40.shape[0] > 0:
        html_40 = df_error_40.to_html(index=False)
        error_umbre_datawifi_4 = f"Total: <b>{df_error_40.shape[0]}</b> <br>{html_40}"
    else:
        error_umbre_datawifi_4 = "OK - Sin Novedades"


    mask_val5 = (df_cruce_vel['CRUCE INVERSO'] != '') & (df_cruce_vel['ID_BENEFICIARIO_PQRSD'].notna())
    df_error_41 = df_cruce_vel[mask_val5].copy()

    if df_error_41.shape[0] > 0:
        html_41 = df_error_41.to_html(index=False)
        error_umbre_datawifi_4_1 = f"Total: <b>{df_error_41.shape[0]}</b> <br>{html_41}"
    else:
        error_umbre_datawifi_4_1 = "OK - Sin Novedades"

else:
    error_umbre_datawifi_4 = "Sin Validación (Faltan datos)"
    error_umbre_datawifi_4_1 = "Sin Validación (Faltan datos)"

print(f"--- {val_umbre_datawifi_4} ---")
print(error_umbre_datawifi_4)
print(f"--- {val_umbre_datawifi_4_1} ---")
print(error_umbre_datawifi_4_1)

--- FALLA VELOCIDAD 5 DIAS: TIENE CONTADOR - NO TIENE PQRSD ---
Total: <b>22</b> <br><table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>ID_BENEFICIARIO_PQRSD</th>
      <th>DISPOSITIVO</th>
      <th>CRUCE</th>
      <th>DIAS SIN MEDICION</th>
      <th>ESTADO_SITIO</th>
      <th>CRUCE INVERSO</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>NaN</td>
      <td>18272</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>13</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>23052</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>20</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>23072</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>14</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>27885</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>20</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>29003</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>19</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>29316</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>20</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>29325</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>19</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>33610</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>340</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>34362</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>13</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>34374</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>13</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>34387</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>13</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>34466</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>13</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>35012</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>19</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>35376</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>19</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>35743</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>20</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>36011</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>19</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>37880</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>19</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>37910</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>19</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>44578</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>19</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>50759</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>16</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>52175</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>13</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>54196</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>20</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
  </tbody>
</table>
--- FALLA VELOCIDAD 5 DIAS: TIENE PQRSD - NO TIENE CONTADOR ---
OK - Sin Novedades


### Validación 5 - FALLA EXTERIOR CON PQRSD PERO SIN CONTADOR

Identifica sitios que **tienen ticket de falla exterior** pero **no aparecen en el listado de contadores con tráfico > 8 días**.

**Lógica Técnica:**
1. Se cruzan los datos de **falla exterior** (`df_falla_ext`) con los registros de contadores (`df_contadores_outdoor`).
2. Se filtran los sitios donde **existe PQRSD** pero **no hay contador activo suficiente** (`Tráfico ≤ 0` o ausente).
3. Se obtiene la lista de sitios que cumplen esta condición.

**Retorna:**
* Variable: `error_umbre_datawifi_5`

In [125]:
val_umbre_datawifi_5 = 'FALLA VELOCIDAD 8 DIAS: TIENE CONTADOR - NO TIENE PQRSD'
val_umbre_datawifi_5_1 = 'FALLA VELOCIDAD 8 DIAS: TIENE PQRSD - NO TIENE CONTADOR'
error_umbre_datawifi_5 = ""
error_umbre_datawifi_5_1 = ""


if ('df_vel_8_dias' in locals() and not df_vel_8_dias.empty) and \
   ('df_cont_vel_8_dias' in locals()) and \
   ('df_base_sitios' in locals() and not df_base_sitios.empty):

    df_falla_temp = df_vel_8_dias.copy()

    if df_cont_vel_8_dias.empty:
        df_cont_temp = pd.DataFrame(columns=['TELEPUERTO', 'ZONA', 'DISPOSITIVO','DIAS SIN MEDICION'])
    else:
        df_cont_temp = df_cont_vel_8_dias.copy()

    df_sitios_temp = df_base_sitios.copy()

    df_falla_temp['ID_BENEFICIARIO_PQRSD'] = (df_falla_temp['ID_BENEFICIARIO_PQRSD'].astype(str))
    df_cont_temp['DISPOSITIVO'] = (df_cont_temp['DISPOSITIVO'].astype(str))
    df_sitios_temp['ID_BENEFICIARIO_SITIOS'] = (df_sitios_temp['ID_BENEFICIARIO_SITIOS'].astype(str))

    df_cruce_vel = pd.merge(
        df_falla_temp,
        df_cont_temp,
        how='outer',
        left_on='ID_BENEFICIARIO_PQRSD',
        right_on='DISPOSITIVO'
    )

    df_cruce_vel = pd.merge(
        df_cruce_vel,
        df_sitios_temp,
        how='left',
        left_on='DISPOSITIVO',
        right_on='ID_BENEFICIARIO_SITIOS',
        suffixes=('', '_SITIO')
    )

    def validar_cruce(row):
        if pd.isna(row['ID_BENEFICIARIO_PQRSD']) and not pd.isna(row['DISPOSITIVO']):
            return 'NO TIENE PQRSD - TIENE CONTADOR'
        return ''

    def validar_cruce_inverso(row):
        if pd.isna(row['DISPOSITIVO']) and not pd.isna(row['ID_BENEFICIARIO_PQRSD']):
            return 'TIENE PQRSD - NO TIENE CONTADOR'
        return ''

    df_cruce_vel['CRUCE'] = df_cruce_vel.apply(validar_cruce, axis=1)
    df_cruce_vel['CRUCE INVERSO'] = df_cruce_vel.apply(validar_cruce_inverso, axis=1)

    cols_interes = [
        'ID_BENEFICIARIO_PQRSD',
        'DISPOSITIVO',
        'CRUCE',
        'DIAS SIN MEDICION',
        'ESTADO_SITIO',
        'CRUCE INVERSO'
    ]


    cols_existentes = [c for c in cols_interes if c in df_cruce_vel.columns]
    df_cruce_vel = df_cruce_vel[cols_existentes]

#    if 'ID_BENEFICIARIO_PQRSD' in df_cruce_vel.columns:
#        df_cruce_vel['ID_BENEFICIARIO_PQRSD'] = df_cruce_vel['ID_BENEFICIARIO_PQRSD'].astype('Int64')
#    if 'IDENTIFICADOR BENEFICIARIO CONTADOR' in df_cruce_vel.columns:
#        df_cruce_vel['IDENTIFICADOR BENEFICIARIO CONTADOR'] = df_cruce_vel['IDENTIFICADOR BENEFICIARIO CONTADOR'].astype('Int64')

    estados_activos = ['ACTIVO', 'SI; EN REINSTALACION', 'SI; EN REUBICACION']

    mask_val4 = (df_cruce_vel['ESTADO_SITIO'].isin(estados_activos)) & (df_cruce_vel['CRUCE'] != '')
    df_error_40 = df_cruce_vel[mask_val4].copy()

    if df_error_40.shape[0] > 0:
        html_40 = df_error_40.to_html(index=False)
        error_umbre_datawifi_5 = f"Total: <b>{df_error_40.shape[0]}</b> <br>{html_40}"
    else:
        error_umbre_datawifi_5 = "OK - Sin Novedades"


    mask_val5 = (df_cruce_vel['CRUCE INVERSO'] != '') & (df_cruce_vel['ID_BENEFICIARIO_PQRSD'].notna())
    df_error_41 = df_cruce_vel[mask_val5].copy()

    if df_error_41.shape[0] > 0:
        html_41 = df_error_41.to_html(index=False)
        error_umbre_datawifi_5_1 = f"Total: <b>{df_error_41.shape[0]}</b> <br>{html_41}"
    else:
        error_umbre_datawifi_5_1 = "OK - Sin Novedades"

else:
    error_umbre_datawifi_5 = "Sin Validación (Faltan datos)"
    error_umbre_datawifi_5_1 = "Sin Validación (Faltan datos)"

print(f"--- {val_umbre_datawifi_5} ---")
print(error_umbre_datawifi_5)
print(f"--- {val_umbre_datawifi_5_1} ---")
print(error_umbre_datawifi_5_1)

--- FALLA VELOCIDAD 8 DIAS: TIENE CONTADOR - NO TIENE PQRSD ---
Total: <b>8</b> <br><table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>ID_BENEFICIARIO_PQRSD</th>
      <th>DISPOSITIVO</th>
      <th>CRUCE</th>
      <th>DIAS SIN MEDICION</th>
      <th>ESTADO_SITIO</th>
      <th>CRUCE INVERSO</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>NaN</td>
      <td>18272</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>13</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>23072</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>14</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>34362</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>13</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>34374</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>13</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>34387</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>13</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>34466</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>13</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>50759</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>16</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>NaN</td>
      <td>52175</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>13</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
  </tbody>
</table>
--- FALLA VELOCIDAD 8 DIAS: TIENE PQRSD - NO TIENE CONTADOR ---
OK - Sin Novedades

### Validación 6 - PQRSD CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR NO TIENE PQRSD - TIENE CONTADOR

Identifica sitios activos que **tienen tráfico registrado por el contador indoor** pero **no tienen ticket de falla interior**.

**Lógica Técnica:**
1. Se cruzan los datos de **falla interior** (`df_falla_int`) con los registros de contadores indoor (`df_contadores_indoor`).
2. Se filtran los sitios donde **NO existe PQRSD** pero **sí hay contador activo** (`Tráfico > 0`).
3. Se obtiene la lista de sitios que cumplen esta condición.

**Retorna:**
* Variable: `error_umbre_datawifi_6`


### Validación 7 - PQRSD CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR TIENE PQRSD - NO TIENE CONTADOR

Identifica sitios que **tienen ticket de falla interior** pero **no aparecen en el listado de contadores indoor con tráfico suficiente**.

**Lógica Técnica:**
1. Se cruzan los datos de **falla interior** (`df_falla_int`) con los registros de contadores indoor (`df_contadores_indoor`).
2. Se filtran los sitios donde **existe PQRSD** pero **no hay contador activo suficiente** (`Tráfico ≤ 0` o ausente).
3. Se obtiene la lista de sitios que cumplen esta condición.

**Retorna:**
* Variable: `error_umbre_datawifi_7`

In [126]:
val_umbre_datawifi_6 = 'PQRSD CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR NO TIENE PQRSD - TIENE CONTADOR'
val_umbre_datawifi_7 = 'PQRSD CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR TIENE PQRSD - NO TIENE CONTADOR'
error_umbre_datawifi_6 = ""
error_umbre_datawifi_7 = ""

if ('df_falla_int' in locals() and not df_falla_int.empty) and \
   ('df_cont_in_8_dias' in locals()) and \
   ('df_base_sitios' in locals() and not df_base_sitios.empty):

    df_falla_temp = df_falla_int.copy()

    if df_cont_in_8_dias.empty:
        df_cont_temp = pd.DataFrame(columns=['IDENTIFICADOR BENEFICIARIO CONTADOR', 'CONTADOR DEL DÍA'])
    else:
        df_cont_temp = df_cont_in_8_dias.copy()

    df_sitios_temp = df_base_sitios.copy()

    df_cruce_int = pd.merge(
        df_falla_temp,
        df_cont_temp,
        how='outer',
        left_on='ID_BENEFICIARIO_PQRSD',
        right_on='IDENTIFICADOR BENEFICIARIO CONTADOR'
    )

    df_cruce_int = pd.merge(
        df_cruce_int,
        df_sitios_temp,
        how='left',
        left_on='IDENTIFICADOR BENEFICIARIO CONTADOR',
        right_on='ID_BENEFICIARIO_SITIOS',
        suffixes=('', '_SITIO')
    )



    def validar_cruce(row):
        if pd.isna(row['ID_BENEFICIARIO_PQRSD']) and not pd.isna(row['IDENTIFICADOR BENEFICIARIO CONTADOR']):
            return 'NO TIENE PQRSD - TIENE CONTADOR'
        return ''


    def validar_cruce_inverso(row):
        if pd.isna(row['IDENTIFICADOR BENEFICIARIO CONTADOR']) and not pd.isna(row['ID_BENEFICIARIO_PQRSD']):
            return 'TIENE PQRSD - NO TIENE CONTADOR'
        return ''

    df_cruce_int['CRUCE'] = df_cruce_int.apply(validar_cruce, axis=1)
    df_cruce_int['CRUCE INVERSO'] = df_cruce_int.apply(validar_cruce_inverso, axis=1)


    cols_interes = [
        'ID_BENEFICIARIO_PQRSD',
        'IDENTIFICADOR BENEFICIARIO CONTADOR',
        'CRUCE',
        'CONTADOR DEL DÍA',
        'ESTADO_SITIO',
        'CRUCE INVERSO'
    ]

    cols_existentes = [c for c in cols_interes if c in df_cruce_int.columns]
    df_cruce_int = df_cruce_int[cols_existentes]


    if 'ID_BENEFICIARIO_PQRSD' in df_cruce_int.columns:
        df_cruce_int['ID_BENEFICIARIO_PQRSD'] = df_cruce_int['ID_BENEFICIARIO_PQRSD'].astype('Int64')
    if 'IDENTIFICADOR BENEFICIARIO CONTADOR' in df_cruce_int.columns:
        df_cruce_int['IDENTIFICADOR BENEFICIARIO CONTADOR'] = df_cruce_int['IDENTIFICADOR BENEFICIARIO CONTADOR'].astype('Int64')


    estados_activos = ['ACTIVO', 'SI; EN REINSTALACION', 'SI; EN REUBICACION']

    mask_val6 = (df_cruce_int['ESTADO_SITIO'].isin(estados_activos)) & (df_cruce_int['CRUCE'] != '')
    df_error_42 = df_cruce_int[mask_val6].copy()

    if df_error_42.shape[0] > 0:
        html_42 = df_error_42.to_html(index=False)
        error_umbre_datawifi_6 = f"Total: <b>{df_error_42.shape[0]}</b> <br>{html_42}"
    else:
        error_umbre_datawifi_6 = "OK - Sin Novedades"


    mask_val7 = (df_cruce_int['CRUCE INVERSO'] != '') & (df_cruce_int['ID_BENEFICIARIO_PQRSD'].notna())
    df_error_43 = df_cruce_int[mask_val7].copy()

    if df_error_43.shape[0] > 0:
        html_43 = df_error_43.to_html(index=False)
        error_umbre_datawifi_7 = f"Total: <b>{df_error_43.shape[0]}</b> <br>{html_43}"
    else:
        error_umbre_datawifi_7 = "OK - Sin Novedades"

else:
    error_umbre_datawifi_6 = "Sin Validación (Faltan datos)"
    error_umbre_datawifi_7 = "Sin Validación (Faltan datos)"

print(f"--- {val_umbre_datawifi_6} ---")
print(error_umbre_datawifi_6)
print(f"--- {val_umbre_datawifi_7} ---")
print(error_umbre_datawifi_7)

--- PQRSD CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR NO TIENE PQRSD - TIENE CONTADOR ---
Total: <b>2</b> <br><table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>ID_BENEFICIARIO_PQRSD</th>
      <th>IDENTIFICADOR BENEFICIARIO CONTADOR</th>
      <th>CRUCE</th>
      <th>CONTADOR DEL DÍA</th>
      <th>ESTADO_SITIO</th>
      <th>CRUCE INVERSO</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>&lt;NA&gt;</td>
      <td>34362</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>279</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>&lt;NA&gt;</td>
      <td>34387</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>34</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
  </tbody>
</table>
--- PQRSD CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR TIENE PQRSD - NO TIENE CONTADOR ---
OK - Sin Novedades

### Validación 8 - PQRSD CD-SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR NO TIENE PQRSD - TIENE CONTADOR

Identifica sitios activos que **tienen tráfico registrado por el contador outdoor** pero **no tienen ticket de "Sin tráfico 24h Exterior"**.

**Lógica Técnica:**
1. Se cruzan los datos de tickets **24h Exterior** (`df_ext_24h`) con los registros de contadores outdoor (`df_contadores_outdoor`).
2. Se filtran los sitios donde **NO existe PQRSD** pero **sí hay contador activo** (`Tráfico > 1 día`).
3. Se obtiene la lista de sitios que cumplen esta condición.

**Retorna:**
* Variable: `error_umbre_datawifi_8`


### Validación 9 - PQRSD CD-SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR TIENE PQRSD - NO TIENE CONTADOR

Identifica sitios que **tienen ticket de "Sin tráfico 24h Exterior"** pero **no aparecen en el listado de contadores outdoor con tráfico > 1 día**.

**Lógica Técnica:**
1. Se cruzan los datos de tickets **24h Exterior** (`df_ext_24h`) con los registros de contadores outdoor (`df_contadores_outdoor`).
2. Se filtran los sitios donde **existe PQRSD** pero **no hay contador activo suficiente** (`Tráfico ≤ 1 día` o ausente).
3. Se obtiene la lista de sitios que cumplen esta condición.

**Retorna:**
* Variable: `error_umbre_datawifi_9`

In [127]:
val_umbre_datawifi_8 = 'PQRSD CD-SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR NO TIENE PQRSD - TIENE CONTADOR'
val_umbre_datawifi_9 = 'PQRSD CD-SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR TIENE PQRSD - NO TIENE CONTADOR'
error_umbre_datawifi_8 = ""
error_umbre_datawifi_9 = ""

if ('df_ext_24h' in locals() and not df_ext_24h.empty) and \
   ('df_cont_out_1_dias' in locals()) and \
   ('df_base_sitios' in locals() and not df_base_sitios.empty):

    df_ext_24h_temp = df_ext_24h.copy()

    if df_cont_out_1_dias.empty:
        df_cont_temp = pd.DataFrame(columns=['IDENTIFICADOR BENEFICIARIO CONTADOR', 'CONTADOR DEL DÍA'])
    else:
        df_cont_temp = df_cont_out_1_dias.copy()

    df_sitios_temp = df_base_sitios.copy()

    df_cruce_24h = pd.merge(
        df_ext_24h_temp,
        df_cont_temp,
        how='outer',
        left_on='ID_BENEFICIARIO_PQRSD',
        right_on='IDENTIFICADOR BENEFICIARIO CONTADOR'
    )

    df_cruce_24h = pd.merge(
        df_cruce_24h,
        df_sitios_temp,
        how='left',
        left_on='IDENTIFICADOR BENEFICIARIO CONTADOR',
        right_on='ID_BENEFICIARIO_SITIOS',
        suffixes=('', '_SITIO')
    )


    def validar_cruce(row):
        if pd.isna(row['ID_BENEFICIARIO_PQRSD']) and not pd.isna(row['IDENTIFICADOR BENEFICIARIO CONTADOR']):
            return 'NO TIENE PQRSD - TIENE CONTADOR'
        return ''

    def validar_cruce_inverso(row):
        if pd.isna(row['IDENTIFICADOR BENEFICIARIO CONTADOR']) and not pd.isna(row['ID_BENEFICIARIO_PQRSD']):
            return 'TIENE PQRSD - NO TIENE CONTADOR'
        return ''

    df_cruce_24h['CRUCE'] = df_cruce_24h.apply(validar_cruce, axis=1)
    df_cruce_24h['CRUCE INVERSO'] = df_cruce_24h.apply(validar_cruce_inverso, axis=1)

    cols_interes = [
        'ID_BENEFICIARIO_PQRSD',
        'IDENTIFICADOR BENEFICIARIO CONTADOR',
        'CRUCE',
        'CONTADOR DEL DÍA',
        'ESTADO_SITIO',
        'CRUCE INVERSO'
    ]
    cols_existentes = [c for c in cols_interes if c in df_cruce_24h.columns]
    df_cruce_24h = df_cruce_24h[cols_existentes]

    if 'ID_BENEFICIARIO_PQRSD' in df_cruce_24h.columns:
        df_cruce_24h['ID_BENEFICIARIO_PQRSD'] = df_cruce_24h['ID_BENEFICIARIO_PQRSD'].astype('Int64')
    if 'IDENTIFICADOR BENEFICIARIO CONTADOR' in df_cruce_24h.columns:
        df_cruce_24h['IDENTIFICADOR BENEFICIARIO CONTADOR'] = df_cruce_24h['IDENTIFICADOR BENEFICIARIO CONTADOR'].astype('Int64')


    estados_activos = ['ACTIVO', 'SI; EN REINSTALACION', 'SI; EN REUBICACION']


    mask_val8 = (df_cruce_24h['ESTADO_SITIO'].isin(estados_activos)) & (df_cruce_24h['CRUCE'] != '')
    df_error_44 = df_cruce_24h[mask_val8].copy()

    if df_error_44.shape[0] > 0:
        html_44 = df_error_44.to_html(index=False)
        error_umbre_datawifi_8 = f"Total: <b>{df_error_44.shape[0]}</b> <br>{html_44}"
    else:
        error_umbre_datawifi_8 = "OK - Sin Novedades"


    mask_val9 = (df_cruce_24h['CRUCE INVERSO'] != '') & (df_cruce_24h['ID_BENEFICIARIO_PQRSD'].notna())
    df_error_45 = df_cruce_24h[mask_val9].copy()

    if df_error_45.shape[0] > 0:
        html_45 = df_error_45.to_html(index=False)
        error_umbre_datawifi_9 = f"Total: <b>{df_error_45.shape[0]}</b> <br>{html_45}"
    else:
        error_umbre_datawifi_9 = "OK - Sin Novedades"

else:
    error_umbre_datawifi_8 = "Sin Validación (Faltan datos)"
    error_umbre_datawifi_9 = "Sin Validación (Faltan datos)"

print(f"--- {val_umbre_datawifi_8} ---")
print(error_umbre_datawifi_8)
print(f"--- {val_umbre_datawifi_9} ---")
print(error_umbre_datawifi_9)

--- PQRSD CD-SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR NO TIENE PQRSD - TIENE CONTADOR ---
Total: <b>4</b> <br><table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>ID_BENEFICIARIO_PQRSD</th>
      <th>IDENTIFICADOR BENEFICIARIO CONTADOR</th>
      <th>CRUCE</th>
      <th>CONTADOR DEL DÍA</th>
      <th>ESTADO_SITIO</th>
      <th>CRUCE INVERSO</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>&lt;NA&gt;</td>
      <td>23681</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>166</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>&lt;NA&gt;</td>
      <td>33610</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>162</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>&lt;NA&gt;</td>
      <td>34362</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>122</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>&lt;NA&gt;</td>
      <td>34387</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>34</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
  </tbody>
</table>
--- PQRSD CD-SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR TIENE PQRSD - NO TIENE CONTADOR ---
OK - Sin Novedades

### Validación 10 - PQRSD CD-SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR NO TIENE PQRSD - TIENE CONTADOR

Identifica sitios activos que **tienen tráfico registrado por el contador indoor** pero **no tienen ticket de "Sin tráfico 24h Interior"**.

**Lógica Técnica:**
1. Se cruzan los datos de tickets **24h Interior** (`df_int_24h`) con los registros de contadores indoor (`df_contadores_indoor`).
2. Se filtran los sitios donde **NO existe PQRSD** pero **sí hay contador activo** (`Tráfico > 1 día`).
3. Se obtiene la lista de sitios que cumplen esta condición.

**Retorna:**
* Variable: `error_umbre_datawifi_10`


### Validación 11 - PQRSD CD-SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR TIENE PQRSD - NO TIENE CONTADOR

Identifica sitios que **tienen ticket de "Sin tráfico 24h Interior"** pero **no aparecen en el listado de contadores indoor con tráfico > 1 día**.

**Lógica Técnica:**
1. Se cruzan los datos de tickets **24h Interior** (`df_int_24h`) con los registros de contadores indoor (`df_contadores_indoor`).
2. Se filtran los sitios donde **existe PQRSD** pero **no hay contador activo suficiente** (`Tráfico ≤ 1 día` o ausente).
3. Se obtiene la lista de sitios que cumplen esta condición.

**Retorna:**
* Variable: `error_umbre_datawifi_11`

In [128]:
val_umbre_datawifi_10 = 'PQRSD CD-SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR NO TIENE PQRSD - TIENE CONTADOR'
val_umbre_datawifi_11 = 'PQRSD CD-SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR TIENE PQRSD - NO TIENE CONTADOR'
error_umbre_datawifi_10 = ""
error_umbre_datawifi_11 = ""

if ('df_int_24h' in locals() and not df_int_24h.empty) and \
   ('df_cont_in_1_dias' in locals()) and \
   ('df_base_sitios' in locals() and not df_base_sitios.empty):

    df_int_24h_temp = df_int_24h.copy()

    if df_cont_in_1_dias.empty:
        df_cont_temp = pd.DataFrame(columns=['IDENTIFICADOR BENEFICIARIO CONTADOR', 'CONTADOR DEL DÍA'])
    else:
        df_cont_temp = df_cont_in_1_dias.copy()

    df_sitios_temp = df_base_sitios.copy()

    df_cruce_24h_int = pd.merge(
        df_int_24h_temp,
        df_cont_temp,
        how='outer',
        left_on='ID_BENEFICIARIO_PQRSD',
        right_on='IDENTIFICADOR BENEFICIARIO CONTADOR'
    )

    df_cruce_24h_int = pd.merge(
        df_cruce_24h_int,
        df_sitios_temp,
        how='left',
        left_on='IDENTIFICADOR BENEFICIARIO CONTADOR',
        right_on='ID_BENEFICIARIO_SITIOS',
        suffixes=('', '_SITIO')
    )


    def validar_cruce(row):
        if pd.isna(row['ID_BENEFICIARIO_PQRSD']) and not pd.isna(row['IDENTIFICADOR BENEFICIARIO CONTADOR']):
            return 'NO TIENE PQRSD - TIENE CONTADOR'
        return ''

    def validar_cruce_inverso(row):
        if pd.isna(row['IDENTIFICADOR BENEFICIARIO CONTADOR']) and not pd.isna(row['ID_BENEFICIARIO_PQRSD']):
            return 'TIENE PQRSD - NO TIENE CONTADOR'
        return ''

    df_cruce_24h_int['CRUCE'] = df_cruce_24h_int.apply(validar_cruce, axis=1)
    df_cruce_24h_int['CRUCE INVERSO'] = df_cruce_24h_int.apply(validar_cruce_inverso, axis=1)

    cols_interes = [
        'ID_BENEFICIARIO_PQRSD',
        'IDENTIFICADOR BENEFICIARIO CONTADOR',
        'CRUCE',
        'CONTADOR DEL DÍA',
        'ESTADO_SITIO',
        'CRUCE INVERSO'
    ]
    cols_existentes = [c for c in cols_interes if c in df_cruce_24h_int.columns]
    df_cruce_24h_int = df_cruce_24h_int[cols_existentes]

    if 'ID_BENEFICIARIO_PQRSD' in df_cruce_24h_int.columns:
        df_cruce_24h_int['ID_BENEFICIARIO_PQRSD'] = df_cruce_24h_int['ID_BENEFICIARIO_PQRSD'].astype('Int64')
    if 'IDENTIFICADOR BENEFICIARIO CONTADOR' in df_cruce_24h_int.columns:
        df_cruce_24h_int['IDENTIFICADOR BENEFICIARIO CONTADOR'] = df_cruce_24h_int['IDENTIFICADOR BENEFICIARIO CONTADOR'].astype('Int64')


    estados_activos = ['ACTIVO', 'SI; EN REINSTALACION', 'SI; EN REUBICACION']

    mask_val10 = (df_cruce_24h_int['ESTADO_SITIO'].isin(estados_activos)) & (df_cruce_24h_int['CRUCE'] != '')
    df_error_46 = df_cruce_24h_int[mask_val10].copy()

    if df_error_46.shape[0] > 0:
        html_46 = df_error_46.to_html(index=False)
        error_umbre_datawifi_10 = f"Total: <b>{df_error_46.shape[0]}</b> <br>{html_46}"
    else:
        error_umbre_datawifi_10 = "OK - Sin Novedades"

    mask_val11 = (df_cruce_24h_int['CRUCE INVERSO'] != '') & (df_cruce_24h_int['ID_BENEFICIARIO_PQRSD'].notna())
    df_error_47 = df_cruce_24h_int[mask_val11].copy()

    if df_error_47.shape[0] > 0:
        html_47 = df_error_47.to_html(index=False)
        error_umbre_datawifi_11 = f"Total: <b>{df_error_47.shape[0]}</b> <br>{html_47}"
    else:
        error_umbre_datawifi_11 = "OK - Sin Novedades"

else:
    error_umbre_datawifi_10 = "Sin Validación (Faltan datos)"
    error_umbre_datawifi_11 = "Sin Validación (Faltan datos)"

print(f"--- {val_umbre_datawifi_10} ---")
print(error_umbre_datawifi_10)
print(f"--- {val_umbre_datawifi_11} ---")
print(error_umbre_datawifi_11)

--- PQRSD CD-SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR NO TIENE PQRSD - TIENE CONTADOR ---
Total: <b>3</b> <br><table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>ID_BENEFICIARIO_PQRSD</th>
      <th>IDENTIFICADOR BENEFICIARIO CONTADOR</th>
      <th>CRUCE</th>
      <th>CONTADOR DEL DÍA</th>
      <th>ESTADO_SITIO</th>
      <th>CRUCE INVERSO</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>&lt;NA&gt;</td>
      <td>33610</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>340.0</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>&lt;NA&gt;</td>
      <td>34362</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>279.0</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
    <tr>
      <td>&lt;NA&gt;</td>
      <td>34387</td>
      <td>NO TIENE PQRSD - TIENE CONTADOR</td>
      <td>34.0</td>
      <td>ACTIVO</td>
      <td></td>
    </tr>
  </tbody>
</table>
--- PQRSD CD-SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR TIENE PQRSD - NO TIENE CONTADOR ---
Total: <b>1</b> <br><table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>ID_BENEFICIARIO_PQRSD</th>
      <th>IDENTIFICADOR BENEFICIARIO CONTADOR</th>
      <th>CRUCE</th>
      <th>CONTADOR DEL DÍA</th>
      <th>ESTADO_SITIO</th>
      <th>CRUCE INVERSO</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>25166</td>
      <td>&lt;NA&gt;</td>
      <td></td>
      <td>NaN</td>
      <td>NaN</td>
      <td>TIENE PQRSD - NO TIENE CONTADOR</td>
    </tr>
  </tbody>
</table>

## Validaciones DataWifi

### Validaciones 1 a 6 - ALARMAS GENERADAS DATAWIFI POR SUBCATEGORIA

Verifica si se han generado registros en el **Log de Netadvisor** (`df_log_netadvisor`) para el día actual, correspondientes a categorías de fallas (24 horas, Velocidad, etc.).

**Lógica Técnica:**
1. Normaliza la **fecha de creación** en el log a formato comparable.
2. Itera sobre una **lista de configuración** que mapea la `Subcategoría` (exacta en el archivo) con la descripción del reporte.
3. Filtra los registros donde **Fecha = Hoy** y la `Subcategoría` coincide.
4. Evalúa:
   - Si el conteo es **> 0**, reporta la cantidad de alarmas.
   - Si el conteo es **0**, indica que **no hubo alarmas**.

**Retorna:**
* Variables: `error_datawifi_1` hasta `error_datawifi_6`

In [129]:
val_datawifi_1 = 'ALARMAS: CD-Sin tráfico de internet 24 horas AP exterior'
val_datawifi_2 = 'ALARMAS: CD-Sin tráfico de internet 24 horas AP interior'
val_datawifi_3 = 'ALARMAS: CD-Falla sin tráfico de internet 24 horas AP exterior'
val_datawifi_4 = 'ALARMAS: CD-Falla sin tráfico de internet 24 horas AP interior'
val_datawifi_5 = 'ALARMAS: CD-Falla en ejecución de prueba de velocidad 5 días calendario'
val_datawifi_6 = 'ALARMAS: CD-Medición directa de velocidad efectiva de transmisión de datos'

error_datawifi_1 = ""
error_datawifi_2 = ""
error_datawifi_3 = ""
error_datawifi_4 = ""
error_datawifi_5 = ""
error_datawifi_6 = ""

if 'df_log_netadvisor' in locals() and not df_log_netadvisor.empty:

    df_dw_temp = df_log_netadvisor.copy()

    fecha_validacion_str = FECHA_HOY_DATE.strftime('%Y-%m-%d')

    if 'FECHA DE CREACIÓN' in df_dw_temp.columns:
        df_dw_temp['FECHA DE CREACIÓN'] = pd.to_datetime(df_dw_temp['FECHA DE CREACIÓN'])
        df_dw_temp['Fecha_Str'] = df_dw_temp['FECHA DE CREACIÓN'].dt.strftime('%Y-%m-%d')
    else:
        df_dw_temp['Fecha_Str'] = ""

    configuracion_alarmas = [
        ('CD-Sin tráfico de internet 24 horas AP exterior',
         'CD-Sin tráfico de internet 24 horas AP exterior', 1),

        ('CD-Sin tráfico de internet 24 horas AP interior',
         'CD-Sin tráfico de internet 24 horas AP interior', 2),

        ('CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR',
         'CD-Falla sin tráfico de internet 24 horas AP exterior', 3),

        ('CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR',
         'CD-Falla sin tráfico de internet 24 horas AP interior', 4),

        ('CD-Falla en ejecución de prueba de velocidad 5 días calendario',
         'CD-Falla en ejecución de prueba de velocidad 5 días calendario', 5),

        ('CD-Medición directa de velocidad efectiva de transmisión de datos',
         'CD-Medición directa de velocidad efectiva de transmisión de datos', 6),
    ]

    resultados = {}

    for subcat_log, descripcion, id_err in configuracion_alarmas:

        df_filtrado = df_dw_temp[
            (df_dw_temp['Fecha_Str'] == fecha_validacion_str) &
            (df_dw_temp['SUBCATEGORYS'] == subcat_log)
        ]

        cantidad = df_filtrado.shape[0]

        if cantidad <= 0:
            msg = f"No se generaron alarmas por concepto de {descripcion}"
        else:
            msg = f"{descripcion}: <b>{cantidad}</b>"

        resultados[id_err] = msg

    error_datawifi_1 = resultados.get(1, "Error en cálculo")
    error_datawifi_2 = resultados.get(2, "Error en cálculo")
    error_datawifi_3 = resultados.get(3, "Error en cálculo")
    error_datawifi_4 = resultados.get(4, "Error en cálculo")
    error_datawifi_5 = resultados.get(5, "Error en cálculo")
    error_datawifi_6 = resultados.get(6, "Error en cálculo")

else:
    msg_error = "Sin Validación (Faltan datos de Netadvisor)"
    error_datawifi_1 = msg_error
    error_datawifi_2 = msg_error
    error_datawifi_3 = msg_error
    error_datawifi_4 = msg_error
    error_datawifi_5 = msg_error
    error_datawifi_6 = msg_error

print(f"--- {val_datawifi_1} ---")
print(error_datawifi_1)
print(f"--- {val_datawifi_2} ---")
print(error_datawifi_2)
print(f"--- {val_datawifi_3} ---")
print(error_datawifi_3)
print(f"--- {val_datawifi_4} ---")
print(error_datawifi_4)
print(f"--- {val_datawifi_5} ---")
print(error_datawifi_5)
print(f"--- {val_datawifi_6} ---")
print(error_datawifi_6)

--- ALARMAS: CD-Sin tráfico de internet 24 horas AP exterior ---
CD-Sin tráfico de internet 24 horas AP exterior: <b>60</b>
--- ALARMAS: CD-Sin tráfico de internet 24 horas AP interior ---
CD-Sin tráfico de internet 24 horas AP interior: <b>59</b>
--- ALARMAS: CD-Falla sin tráfico de internet 24 horas AP exterior ---
CD-Falla sin tráfico de internet 24 horas AP exterior: <b>14</b>
--- ALARMAS: CD-Falla sin tráfico de internet 24 horas AP interior ---
CD-Falla sin tráfico de internet 24 horas AP interior: <b>14</b>
--- ALARMAS: CD-Falla en ejecución de prueba de velocidad 5 días calendario ---
CD-Falla en ejecución de prueba de velocidad 5 días calendario: <b>19</b>
--- ALARMAS: CD-Medición directa de velocidad efectiva de transmisión de datos ---
CD-Medición directa de velocidad efectiva de transmisión de datos: <b>18</b>

### Validación 7 - HORAS EN LAS QUE NO SE CERRARON PQRSD CON CATEGORIA CD-SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR

Analiza los cierres del día anterior (**ayer**) para la subcategoría **"CD-Sin tráfico de internet 24 horas AP exterior"**, identificando las horas en las que **no se registró ningún cierre**.

**Lógica Técnica:**
1. Filtra el log de Netadvisor (`df_log_netadvisor`) para obtener los registros **cerrados ayer**.
2. Filtra por la subcategoría **"CD-Sin tráfico de internet 24 horas AP exterior"**.
3. Agrupa los registros por **hora del día** (0 a 23).
4. Rellena las horas faltantes con 0.
5. Identifica las horas donde la **cantidad de cierres fue 0**.

**Retorna:**
* Tabla con las horas que tuvieron 0 cierres.
* Variable: `error_datawifi_7`

In [130]:
val_datawifi_7 = 'HORAS EN LAS QUE NO SE CERRARON PQRSD CON CATEGORIA CD-SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR'
error_datawifi_7 = ""

if 'df_log_netadvisor' in locals() and not df_log_netadvisor.empty:

    logs_sin_trafico_exterior = df_log_netadvisor.copy()

    logs_sin_trafico_exterior['FECHA DE CIERRE'] = pd.to_datetime(logs_sin_trafico_exterior['FECHA DE CIERRE'], errors='coerce')

    ayer = (datetime.now() - timedelta(days=1)).date()

    logs_ayer = logs_sin_trafico_exterior[logs_sin_trafico_exterior['FECHA DE CIERRE'].dt.date == ayer]

    logs_ayer = logs_ayer.copy()
    logs_ayer['HORA'] = logs_ayer['FECHA DE CIERRE'].dt.hour

    logs_ayer.loc[:, 'HORA'] = logs_ayer['FECHA DE CIERRE'].dt.hour

    logs_filtrado = logs_ayer[logs_ayer['SUBCATEGORYS'] == 'CD-Sin tráfico de internet 24 horas AP exterior'].copy()
    logs_filtrado['HORA'] = logs_filtrado['FECHA DE CIERRE'].dt.hour

    resumen = logs_filtrado.groupby('HORA').size().reset_index(name='CANTIDAD CERRADOS CD-SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR')

    todas_las_horas = pd.DataFrame({'HORA': range(24)})
    resultado_final_datawifi = todas_las_horas.merge(resumen, on='HORA', how='left').fillna(0)
    resultado_final_datawifi['CANTIDAD CERRADOS CD-SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR'] = resultado_final_datawifi['CANTIDAD CERRADOS CD-SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR'].astype(int)

    horas_sin_cierres = resultado_final_datawifi[
        (resultado_final_datawifi['CANTIDAD CERRADOS CD-SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR'] == 0) #&
        #(resultado_final_datawifi['HORA'] >= 6) &
        #(resultado_final_datawifi['HORA'] <= 21)
    ]

    if horas_sin_cierres.shape[0] > 0:
        horas_sin_cierres = horas_sin_cierres.to_html(index=False)
        error_datawifi_7 = horas_sin_cierres
    else:
        error_datawifi_7 = "OK - Sin Novedades"

else:
    error_datawifi_7 = "Sin Validación (Faltan datos de Netadvisor)"

print(f"--- {val_datawifi_7} ---")
print(error_datawifi_7)

--- HORAS EN LAS QUE NO SE CERRARON PQRSD CON CATEGORIA CD-SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR ---
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>HORA</th>
      <th>CANTIDAD CERRADOS CD-SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <td>2</td>
      <td>0</td>
    </tr>
    <tr>
      <td>3</td>
      <td>0</td>
    </tr>
    <tr>
      <td>4</td>
      <td>0</td>
    </tr>
    <tr>
      <td>5</td>
      <td>0</td>
    </tr>
    <tr>
      <td>19</td>
      <td>0</td>
    </tr>
    <tr>
      <td>20</td>
      <td>0</td>
    </tr>
    <tr>
      <td>21</td>
      <td>0</td>
    </tr>
    <tr>
      <td>22</td>
      <td>0</td>
    </tr>
    <tr>
      <td>23</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

### Validación 8 - HORAS EN LAS QUE NO SE CERRARON PQRSD CON CATEGORIA CD-Sin tráfico de internet 24 horas AP interior

Analiza los cierres del día anterior (**ayer**) para la subcategoría **"CD-Sin tráfico de internet 24 horas AP interior"**, identificando las horas en las que **no se registró ningún cierre**.

**Lógica Técnica:**
1. Filtra el log de Netadvisor (`df_log_netadvisor`) para obtener los registros **cerrados ayer**.
2. Filtra por la subcategoría **"CD-Sin tráfico de internet 24 horas AP interior"**.
3. Agrupa los registros por **hora del día** (0 a 23) y rellena los vacíos con 0.
4. Identifica las horas donde la **cantidad de cierres fue 0**.

**Retorna:**
* Tabla con las horas sin cierres.
* Variable: `error_datawifi_8`

In [131]:
val_datawifi_8 = 'HORAS EN LAS QUE NO SE CERRARON PQRSD CON CATEGORIA CD-Sin tráfico de internet 24 horas AP interior'
error_datawifi_8 = ""

if 'df_log_netadvisor' in locals() and not df_log_netadvisor.empty:

    logs_sin_trafico_interior = df_log_netadvisor.copy()

    logs_sin_trafico_interior['FECHA DE CIERRE'] = pd.to_datetime(logs_sin_trafico_interior['FECHA DE CIERRE'], errors='coerce')

    ayer = (datetime.now() - timedelta(days=1)).date()

    logs_ayer = logs_sin_trafico_interior[logs_sin_trafico_interior['FECHA DE CIERRE'].dt.date == ayer]

    logs_ayer = logs_ayer.copy()
    logs_ayer['HORA'] = logs_ayer['FECHA DE CIERRE'].dt.hour

    logs_ayer.loc[:, 'HORA'] = logs_ayer['FECHA DE CIERRE'].dt.hour

    logs_filtrado = logs_ayer[logs_ayer['SUBCATEGORYS'] == 'CD-Sin tráfico de internet 24 horas AP interior'].copy()
    logs_filtrado['HORA'] = logs_filtrado['FECHA DE CIERRE'].dt.hour

    resumen = logs_filtrado.groupby('HORA').size().reset_index(name='CANTIDAD CERRADOS CD-SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR')

    todas_las_horas = pd.DataFrame({'HORA': range(24)})
    resultado_final_datawifi = todas_las_horas.merge(resumen, on='HORA', how='left').fillna(0)
    resultado_final_datawifi['CANTIDAD CERRADOS CD-SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR'] = resultado_final_datawifi['CANTIDAD CERRADOS CD-SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR'].astype(int)

    horas_sin_cierres = resultado_final_datawifi[
        (resultado_final_datawifi['CANTIDAD CERRADOS CD-SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR'] == 0)
    ]

    if horas_sin_cierres.shape[0] > 0:
        horas_sin_cierres = horas_sin_cierres.to_html(index=False)
        error_datawifi_8 = horas_sin_cierres
    else:
        error_datawifi_8 = "OK - Sin Novedades"

else:
    error_datawifi_8 = "Sin Validación (Faltan datos de Netadvisor)"

print(f"--- {val_datawifi_8} ---")
print(error_datawifi_8)

--- HORAS EN LAS QUE NO SE CERRARON PQRSD CON CATEGORIA CD-Sin tráfico de internet 24 horas AP interior ---
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>HORA</th>
      <th>CANTIDAD CERRADOS CD-SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <td>3</td>
      <td>0</td>
    </tr>
    <tr>
      <td>4</td>
      <td>0</td>
    </tr>
    <tr>
      <td>5</td>
      <td>0</td>
    </tr>
    <tr>
      <td>6</td>
      <td>0</td>
    </tr>
    <tr>
      <td>19</td>
      <td>0</td>
    </tr>
    <tr>
      <td>20</td>
      <td>0</td>
    </tr>
    <tr>
      <td>21</td>
      <td>0</td>
    </tr>
    <tr>
      <td>22</td>
      <td>0</td>
    </tr>
    <tr>
      <td>23</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

### Validación 9 - HORAS EN LAS QUE NO SE CERRARON PQRSD CON CATEGORIA CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR

Analiza los cierres del día anterior (**ayer**) para la subcategoría **"CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR"**, identificando las horas en las que **no se registró ningún cierre**.

**Lógica Técnica:**
1. Filtra el log de Netadvisor (`df_log_netadvisor`) para obtener los registros **cerrados ayer**.
2. Filtra por la subcategoría **"CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR"**.
3. Agrupa los registros por **hora del día** (0 a 23) y rellena los vacíos con 0.
4. Identifica las horas donde la **cantidad de cierres fue 0**.

**Retorna:**
* Tabla con las horas sin cierres.
* Variable: `error_datawifi_9`

In [132]:
val_datawifi_9 = 'HORAS EN LAS QUE NO SE CERRARON PQRSD CON CATEGORIA CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR'
error_datawifi_9 = ""

if 'df_log_netadvisor' in locals() and not df_log_netadvisor.empty:

    logs_falla_interior = df_log_netadvisor.copy()

    logs_falla_interior['FECHA DE CIERRE'] = pd.to_datetime(logs_falla_interior['FECHA DE CIERRE'], errors='coerce')

    ayer = (datetime.now() - timedelta(days=1)).date()

    logs_ayer = logs_falla_interior[logs_falla_interior['FECHA DE CIERRE'].dt.date == ayer]

    logs_ayer = logs_ayer.copy()
    logs_ayer['HORA'] = logs_ayer['FECHA DE CIERRE'].dt.hour

    logs_ayer.loc[:, 'HORA'] = logs_ayer['FECHA DE CIERRE'].dt.hour

    logs_filtrado = logs_ayer[logs_ayer['SUBCATEGORYS'] == 'CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR'].copy()
    logs_filtrado['HORA'] = logs_filtrado['FECHA DE CIERRE'].dt.hour

    resumen = logs_filtrado.groupby('HORA').size().reset_index(name='CANTIDAD CERRADOS CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR')

    todas_las_horas = pd.DataFrame({'HORA': range(24)})
    resultado_final = todas_las_horas.merge(resumen, on='HORA', how='left').fillna(0)
    resultado_final['CANTIDAD CERRADOS CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR'] = resultado_final['CANTIDAD CERRADOS CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR'].astype(int)

    horas_sin_cierres_outdoor = resultado_final[
        (resultado_final['CANTIDAD CERRADOS CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR'] == 0) #&
        # (resultado_final['hora'] >= 6) &
        # (resultado_final['hora'] <= 21)
    ]

    if horas_sin_cierres_outdoor.shape[0] > 0:
        horas_sin_cierres_outdoor = horas_sin_cierres_outdoor.to_html(index=False)
        error_datawifi_9 = horas_sin_cierres_outdoor
    else:
        error_datawifi_9 = "OK - Sin Novedades"

else:
    error_datawifi_9 = "Sin Validación (Faltan datos de Netadvisor)"

print(f"--- {val_datawifi_9} ---")
print(error_datawifi_9)

--- HORAS EN LAS QUE NO SE CERRARON PQRSD CON CATEGORIA CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR ---
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>HORA</th>
      <th>CANTIDAD CERRADOS CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP INTERIOR</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <td>3</td>
      <td>0</td>
    </tr>
    <tr>
      <td>4</td>
      <td>0</td>
    </tr>
    <tr>
      <td>5</td>
      <td>0</td>
    </tr>
    <tr>
      <td>6</td>
      <td>0</td>
    </tr>
    <tr>
      <td>7</td>
      <td>0</td>
    </tr>
    <tr>
      <td>10</td>
      <td>0</td>
    </tr>
    <tr>
      <td>17</td>
      <td>0</td>
    </tr>
    <tr>
      <td>18</td>
      <td>0</td>
    </tr>
    <tr>
      <td>19</td>
      <td>0</td>
    </tr>
    <tr>
      <td>20</td>
      <td>0</td>
    </tr>
    <tr>
      <td>21</td>
      <td>0</td>
    </tr>
    <tr>
      <td>22</td>
      <td>0</td>
    </tr>
    <tr>
      <td>23</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

### Validación 10 - HORAS EN LAS QUE NO SE CERRARON PQRSD CON CATEGORIA CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR

Analiza los cierres del día anterior (**ayer**) para la subcategoría **"CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR"**, identificando las horas en las que **no se registró ningún cierre**.

**Lógica Técnica:**
1. Filtra el log de Netadvisor (`df_log_netadvisor`) para obtener los registros **cerrados ayer**.
2. Filtra por la subcategoría **"CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR"**.
3. Agrupa los registros por **hora del día** (0 a 23) y rellena los vacíos con 0.
4. Identifica las horas donde la **cantidad de cierres fue 0**.

**Retorna:**
* Tabla con las horas sin cierres.
* Variable: `error_datawifi_10`

In [133]:
val_datawifi_10 = 'HORAS EN LAS QUE NO SE CERRARON PQRSD CON CATEGORIA CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR'
error_datawifi_10 = ""

if 'df_log_netadvisor' in locals() and not df_log_netadvisor.empty:

    logs_falla_exterior = df_log_netadvisor.copy()

    logs_falla_exterior['FECHA DE CIERRE'] = pd.to_datetime(logs_falla_exterior['FECHA DE CIERRE'], errors='coerce')

    ayer = (datetime.now() - timedelta(days=1)).date()

    logs_ayer = logs_falla_exterior[logs_falla_exterior['FECHA DE CIERRE'].dt.date == ayer]

    logs_ayer = logs_ayer.copy()
    logs_ayer['HORA'] = logs_ayer['FECHA DE CIERRE'].dt.hour

    logs_ayer.loc[:, 'HORA'] = logs_ayer['FECHA DE CIERRE'].dt.hour

    logs_filtrado = logs_ayer[logs_ayer['SUBCATEGORYS'] == 'CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR'].copy()
    logs_filtrado['HORA'] = logs_filtrado['FECHA DE CIERRE'].dt.hour

    resumen = logs_filtrado.groupby('HORA').size().reset_index(name='CANTIDAD CERRADOS CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR')

    todas_las_horas = pd.DataFrame({'HORA': range(24)})
    resultado_final = todas_las_horas.merge(resumen, on='HORA', how='left').fillna(0)
    resultado_final['CANTIDAD CERRADOS CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR'] = resultado_final['CANTIDAD CERRADOS CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR'].astype(int)

    horas_sin_cierres_outdoor = resultado_final[
        (resultado_final['CANTIDAD CERRADOS CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR'] == 0)
    ]

    if horas_sin_cierres_outdoor.shape[0] > 0:
        horas_sin_cierres_outdoor = horas_sin_cierres_outdoor.to_html(index=False)
        error_datawifi_10 = horas_sin_cierres_outdoor
    else:
        error_datawifi_10 = "OK - Sin Novedades"

else:
    error_datawifi_10 = "Sin Validación (Faltan datos de Netadvisor)"

print(f"--- {val_datawifi_10} ---")
print(error_datawifi_10)

--- HORAS EN LAS QUE NO SE CERRARON PQRSD CON CATEGORIA CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR ---
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>HORA</th>
      <th>CANTIDAD CERRADOS CD-FALLA SIN TRÁFICO DE INTERNET 24 HORAS AP EXTERIOR</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <td>2</td>
      <td>0</td>
    </tr>
    <tr>
      <td>3</td>
      <td>0</td>
    </tr>
    <tr>
      <td>4</td>
      <td>0</td>
    </tr>
    <tr>
      <td>5</td>
      <td>0</td>
    </tr>
    <tr>
      <td>6</td>
      <td>0</td>
    </tr>
    <tr>
      <td>7</td>
      <td>0</td>
    </tr>
    <tr>
      <td>10</td>
      <td>0</td>
    </tr>
    <tr>
      <td>17</td>
      <td>0</td>
    </tr>
    <tr>
      <td>18</td>
      <td>0</td>
    </tr>
    <tr>
      <td>19</td>
      <td>0</td>
    </tr>
    <tr>
      <td>20</td>
      <td>0</td>
    </tr>
    <tr>
      <td>21</td>
      <td>0</td>
    </tr>
    <tr>
      <td>22</td>
      <td>0</td>
    </tr>
    <tr>
      <td>23</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

### Validación 11 - HORAS EN LAS QUE NO SE CERRARON PQRSD CON CATEGORIA CD-Falla en ejecución de prueba de velocidad 5 días calendario

Analiza los cierres del día anterior (**ayer**) para la subcategoría **"CD-Falla en ejecución de prueba de velocidad 5 días calendario"**, identificando las horas **entre 06:00 y 21:00** en las que **no se registró ningún cierre**.

**Lógica Técnica:**
1. Filtra el log de Netadvisor (`df_log_netadvisor`) para obtener los registros **cerrados ayer**.
2. Filtra por la subcategoría específica de velocidad.
3. Agrupa los registros por **hora del día** (0 a 23) y rellena los vacíos con 0.
4. Filtra las horas donde **CANTIDAD == 0** y **HORA >= 6 y HORA <= 21**.

**Retorna:**
* Tabla con las horas sin cierres dentro del rango laboral (06-21).
* Variable: `error_datawifi_11`

In [134]:
val_datawifi_11 = 'HORAS EN LAS QUE NO SE CERRARON PQRSD CON CATEGORIA CD-Falla en ejecución de prueba de velocidad 5 días calendario'
error_datawifi_11 = ""

if 'df_log_netadvisor' in locals() and not df_log_netadvisor.empty:

    logs_5_dias = df_log_netadvisor.copy()

    logs_5_dias['FECHA DE CIERRE'] = pd.to_datetime(logs_5_dias['FECHA DE CIERRE'], errors='coerce')

    ayer = (datetime.now() - timedelta(days=1)).date()

    logs_ayer = logs_5_dias[logs_5_dias['FECHA DE CIERRE'].dt.date == ayer].copy()
    logs_ayer['HORA'] = logs_ayer['FECHA DE CIERRE'].dt.hour

    logs_filtrado = logs_ayer[logs_ayer['SUBCATEGORYS'] == 'CD-Falla en ejecución de prueba de velocidad 5 días calendario'].copy()
    logs_filtrado['HORA'] = logs_filtrado['FECHA DE CIERRE'].dt.hour

    resumen = logs_filtrado.groupby('HORA').size().reset_index(name='CANTIDAD CD-FALLA EN EJECUCIÓN DE PRUEBA DE VELOCIDAD 5 DÍAS CALENDARIO')

    todas_las_horas = pd.DataFrame({'HORA': range(24)})
    resultado_final = todas_las_horas.merge(resumen, on='HORA', how='left').fillna(0)
    resultado_final['CANTIDAD CD-FALLA EN EJECUCIÓN DE PRUEBA DE VELOCIDAD 5 DÍAS CALENDARIO'] = resultado_final['CANTIDAD CD-FALLA EN EJECUCIÓN DE PRUEBA DE VELOCIDAD 5 DÍAS CALENDARIO'].astype(int)

    horas_sin_cierres = resultado_final[
        (resultado_final['CANTIDAD CD-FALLA EN EJECUCIÓN DE PRUEBA DE VELOCIDAD 5 DÍAS CALENDARIO'] == 0) &
        (resultado_final['HORA'] >= 6) &
        (resultado_final['HORA'] <= 21)
    ]

    if horas_sin_cierres.shape[0] > 0:
        horas_sin_cierres = horas_sin_cierres.to_html(index=False)
        error_datawifi_11 = horas_sin_cierres
    else:
        error_datawifi_11 = "OK - Sin Novedades"

else:
    error_datawifi_11 = "Sin Validación (Faltan datos de Netadvisor)"

print(f"--- {val_datawifi_11} ---")
print(error_datawifi_11)

--- HORAS EN LAS QUE NO SE CERRARON PQRSD CON CATEGORIA CD-Falla en ejecución de prueba de velocidad 5 días calendario ---
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>HORA</th>
      <th>CANTIDAD CD-FALLA EN EJECUCIÓN DE PRUEBA DE VELOCIDAD 5 DÍAS CALENDARIO</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>17</td>
      <td>0</td>
    </tr>
    <tr>
      <td>19</td>
      <td>0</td>
    </tr>
    <tr>
      <td>20</td>
      <td>0</td>
    </tr>
    <tr>
      <td>21</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

### Validación 12 - HORAS EN LAS QUE NO SE CERRARON PQRSD CON CATEGORIA CD-Medición directa de velocidad efectiva de transmisión de datos

Analiza los cierres del día anterior (**ayer**) para la subcategoría **"Medición Directa de Velocidad Efectiva de Transmisión de Datos"**, identificando las horas **entre 06:00 y 21:00** en las que **no se registró ningún cierre**.

**Lógica Técnica:**
1. Filtra el log de Netadvisor (`df_log_netadvisor`) para obtener los registros **cerrados ayer**.
2. Filtra por la subcategoría específica de medición directa.
3. Agrupa los registros por **hora del día** (0 a 23) y rellena los vacíos con 0.
4. Filtra las horas donde **CANTIDAD == 0** y **HORA >= 6 y HORA <= 21**.

**Retorna:**
* Tabla con las horas sin cierres dentro del rango laboral (06-21).
* Variable: `error_datawifi_12`

In [135]:
val_datawifi_12 = 'HORAS EN LAS QUE NO SE CERRARON PQRSD CON CATEGORIA CD-Medición directa de velocidad efectiva de transmisión de datos'
error_datawifi_12 = ""

if 'df_log_netadvisor' in locals() and not df_log_netadvisor.empty:

    logs_8_dias = df_log_netadvisor.copy()

    logs_8_dias['FECHA DE CIERRE'] = pd.to_datetime(logs_8_dias['FECHA DE CIERRE'], errors='coerce')

    ayer = (datetime.now() - timedelta(days=1)).date()

    logs_ayer = logs_8_dias[logs_8_dias['FECHA DE CIERRE'].dt.date == ayer].copy()
    logs_ayer['HORA'] = logs_ayer['FECHA DE CIERRE'].dt.hour

    logs_filtrado = logs_ayer[logs_ayer['SUBCATEGORYS'] == 'CD-Medición directa de velocidad efectiva de transmisión de datos'].copy()
    logs_filtrado['HORA'] = logs_filtrado['FECHA DE CIERRE'].dt.hour

    resumen = logs_filtrado.groupby('HORA').size().reset_index(name='CANTIDAD CD-MEDICIÓN DIRECTA DE VELOCIDAD EFECTIVA DE TRANSMISIÓN DE DATOS')

    todas_las_horas = pd.DataFrame({'HORA': range(24)})
    resultado_final = todas_las_horas.merge(resumen, on='HORA', how='left').fillna(0)
    resultado_final['CANTIDAD CD-MEDICIÓN DIRECTA DE VELOCIDAD EFECTIVA DE TRANSMISIÓN DE DATOS'] = resultado_final['CANTIDAD CD-MEDICIÓN DIRECTA DE VELOCIDAD EFECTIVA DE TRANSMISIÓN DE DATOS'].astype(int)

    horas_sin_cierres = resultado_final[
        (resultado_final['CANTIDAD CD-MEDICIÓN DIRECTA DE VELOCIDAD EFECTIVA DE TRANSMISIÓN DE DATOS'] == 0) &
        (resultado_final['HORA'] >= 6) &
        (resultado_final['HORA'] <= 21)
    ]

    if horas_sin_cierres.shape[0] > 0:
        horas_sin_cierres = horas_sin_cierres.to_html(index=False)
        error_datawifi_12 = horas_sin_cierres
    else:
        error_datawifi_12 = "OK - Sin Novedades"

else:
    error_datawifi_12 = "Sin Validación (Faltan datos de Netadvisor)"

print(f"--- {val_datawifi_12} ---")
print(error_datawifi_12)

--- HORAS EN LAS QUE NO SE CERRARON PQRSD CON CATEGORIA CD-Medición directa de velocidad efectiva de transmisión de datos ---
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>HORA</th>
      <th>CANTIDAD CD-MEDICIÓN DIRECTA DE VELOCIDAD EFECTIVA DE TRANSMISIÓN DE DATOS</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>17</td>
      <td>0</td>
    </tr>
    <tr>
      <td>19</td>
      <td>0</td>
    </tr>
    <tr>
      <td>20</td>
      <td>0</td>
    </tr>
    <tr>
      <td>21</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

### Validación 13 - PQRS ENVIADA DATAWIFI SIN UUID

Identifica los registros en el **Log de Netadvisor** con fecha de hoy que **no tienen asignado un número de ticket (PQR vacío o nulo)**.

**Lógica Técnica:**
1. Filtra el log de Netadvisor (`df_log_netadvisor`) para obtener los registros con **fecha de creación = Hoy**.
2. Busca las filas donde la columna `PQR` sea **nula** (`isna()`).
3. Devuelve los registros incompletos.

**Retorna:**
* Tabla con los registros sin PQR.
* Variable: `error_datawifi_13`

In [136]:
val_datawifi_13 = 'PQRS ENVIADA DATAWIFI SIN UUID'
error_datawifi_13 = ""

if 'df_log_netadvisor' in locals() and not df_log_netadvisor.empty:

    df_dw_temp = df_log_netadvisor.copy()

    if 'FECHA DE CREACIÓN' in df_dw_temp.columns:
        df_dw_temp['FECHA DE CREACIÓN'] = pd.to_datetime(df_dw_temp['FECHA DE CREACIÓN'])
        fecha_hoy_str = FECHA_HOY_DATE.strftime('%Y-%m-%d')

        df_dw_hoy = df_dw_temp[df_dw_temp['FECHA DE CREACIÓN'].dt.strftime('%Y-%m-%d') == fecha_hoy_str].copy()

        df_sin_pqr = df_dw_hoy[df_dw_hoy['PQR'].isna()].copy()

        cols_req = ['IDENTIFICADOR BENEFICIARIO', 'PQR', 'SUBCATEGORYS', 'STATUS']
        cols_existentes = [c for c in cols_req if c in df_sin_pqr.columns]
        df_sin_pqr = df_sin_pqr[cols_existentes]

        total_sin_pqr = df_sin_pqr.shape[0]

        if total_sin_pqr > 0:
            html_tabla = df_sin_pqr.to_html(index=False)
            error_datawifi_13 = f"Total: <b>{total_sin_pqr}</b> <br>{html_tabla}"
        else:
            error_datawifi_13 = "OK - Sin Novedades"

    else:
        error_datawifi_13 = "Error: Columna 'FECHA DE CREACIÓN' no encontrada"

else:
    error_datawifi_13 = "Sin Validación (Faltan datos de Netadvisor)"

print(f"--- {val_datawifi_13} ---")
print(error_datawifi_13)

--- PQRS ENVIADA DATAWIFI SIN UUID ---
OK - Sin Novedades

## Validaciones Umbrella y CCC

### Validaciones 1 y 2 - FALLAS DE ETIQUETAS INTEGRACIÓN y FALLAS ESCRITURA INTEGRACIÓN

Procesa la columna `log` (JSON) del archivo de integración para detectar inconsistencias.

**Validación 1 - FALLAS DE ETIQUETAS INTEGRACIÓN:**  
Identifica registros con **status = "NO"** (fallidos) cuyo `ref_id` **no aparece posteriormente con status = "SI"** (exitoso).  
Detecta **fallas que no han sido reintentadas con éxito**.

**Validación 2 - FALLAS ESCRITURA INTEGRACIÓN:**  
Identifica `ref_id` que **aparecen en la raíz del JSON** pero **no existen dentro de la estructura anidada** `['PQRS']['ref_id']`.

**Retorna:**
* Variable: `error_umbre_ccc_1` (fallas no corregidas)
* Variable: `error_umbre_ccc_2` (discrepancia de estructura)

In [137]:
val_umbre_ccc_1 = 'FALLAS DE ETIQUETAS INTEGRACIÓN'
val_umbre_ccc_2 = 'FALLAS ESCRITURA INTEGRACIÓN'
error_umbre_ccc_1 = ""
error_umbre_ccc_2 = ""

if 'df_log_api_ccc' in locals() and not df_log_api_ccc.empty:

    df_log_ccc = df_log_api_ccc.reset_index().copy()

    def safe_json_loads(x):
        try:
            return json.loads(x)
        except (TypeError, json.JSONDecodeError):
            return {}

    df_log_ccc['json_data'] = df_log_ccc['log'].apply(safe_json_loads)


    df_log_ccc['ref_id_top'] = df_log_ccc['json_data'].apply(lambda x: x.get('ref_id'))

    df_log_ccc['ref_id_nested'] = df_log_ccc['json_data'].apply(lambda x: x.get('PQRS', {}).get('ref_id'))


    df_fallas = df_log_ccc[df_log_ccc['status'] == "NO"].copy()
    df_exitos = df_log_ccc[df_log_ccc['status'] == "SI"].copy()

    mask_sin_recuperar = ~df_fallas['ref_id_nested'].isin(df_exitos['ref_id_nested'])
    df_errores_no_recuperados = df_fallas[mask_sin_recuperar].copy()

    cols_val1 = ['Fecha_Creación', 'ref_id_nested', 'status']
    df_errores_no_recuperados = df_errores_no_recuperados.rename(columns={'ref_id_nested': 'ref_id'})

    cols_existentes_v1 = [c for c in cols_val1 if c in df_errores_no_recuperados.columns]
    df_vista_v1 = df_errores_no_recuperados[cols_existentes_v1]

    if df_vista_v1.shape[0] > 0:
        html_v1 = df_vista_v1.to_html(index=False)
        error_umbre_ccc_1 = f"Total: <b>{df_vista_v1.shape[0]}</b> <br>{html_v1}"
    else:
        error_umbre_ccc_1 = "Ok - Sin Novedades"

    set_ids_top = set(df_log_ccc['ref_id_top'].dropna())
    set_ids_nested = set(df_log_ccc['ref_id_nested'].dropna())

    ids_diferencia = set_ids_top - set_ids_nested

    df_diferencia_ids = pd.DataFrame(list(ids_diferencia), columns=['ref_id'])

    if df_diferencia_ids.shape[0] > 0:
        html_v2 = df_diferencia_ids.to_html(index=False)
        error_umbre_ccc_2 = f"Total: <b>{df_diferencia_ids.shape[0]}</b> <br>{html_v2}"
    else:
        error_umbre_ccc_2 = "Ok - Sin Novedades"

else:
    error_umbre_ccc_1 = "Sin Validación (Faltan datos de df_log_api_ccc)"
    error_umbre_ccc_2 = "Sin Validación (Faltan datos de df_log_api_ccc)"

print(f"--- {val_umbre_ccc_1} ---")
print(error_umbre_ccc_1)
print(f"--- {val_umbre_ccc_2} ---")
print(error_umbre_ccc_2)

--- FALLAS DE ETIQUETAS INTEGRACIÓN ---
Ok - Sin Novedades
--- FALLAS ESCRITURA INTEGRACIÓN ---
Ok - Sin Novedades

### Validación 3 - ERRORES LOG COMENTARIOS CCC (DÍA ANTERIOR - STATUS != 200)

Analiza el **log de comentarios** de la integración CCC para identificar registros del **día anterior** que presentaron **errores técnicos** (código de estado diferente a 200).

**Lógica Técnica:**
1. Convierte la columna `created_at` a **formato fecha**.
2. Calcula la fecha de **ayer**.
3. Filtra los registros donde **Fecha = Ayer** y **status_code != 200**.

**Retorna:**
* Tabla con los envíos fallidos de ayer.
* Variable: `error_umbre_ccc_3`

In [138]:
val_umbre_ccc_3 = 'ERRORES LOG COMENTARIOS CCC (DÍA ANTERIOR - STATUS != 200)'
error_umbre_ccc_3 = ""

if 'df_log_comentarios_integracion_ccc' in locals() and not df_log_comentarios_integracion_ccc.empty:

    df_analisis_comentarios = df_log_comentarios_integracion_ccc.copy()

    if 'created_at' in df_analisis_comentarios.columns:
        df_analisis_comentarios['created_at'] = pd.to_datetime(df_analisis_comentarios['created_at'], errors='coerce')

        fecha_ayer = (datetime.now() - timedelta(days=1)).date()

        mask_fecha = df_analisis_comentarios['created_at'].dt.date == fecha_ayer
        mask_error = df_analisis_comentarios['status_code'] != 200

        df_errores_comentarios = df_analisis_comentarios[mask_fecha & mask_error].copy()

        cantidad_errores = df_errores_comentarios.shape[0]

        cols_interes = ['pqrs_number', 'created_at', 'status_code', 'is_successful']
        cols_existentes = [c for c in cols_interes if c in df_errores_comentarios.columns]

        df_vista_3 = df_errores_comentarios[cols_existentes].rename(columns={
            'pqrs_number': 'ID_PQRS',
            'created_at': 'Fecha',
            'status_code': 'codigo estado',
            'is_successful': 'Enviado'
        })

        if cantidad_errores > 0:
            html_tabla = df_vista_3.to_html(index=False)
            error_umbre_ccc_3 = f"Total: <b>{cantidad_errores}</b> <br>{html_tabla}"
        else:
            error_umbre_ccc_3 = "OK - Sin Novedades"
    else:
        error_umbre_ccc_3 = "Error: Columna 'created_at' no encontrada en el log"

else:
    error_umbre_ccc_3 = "Sin Validación (Faltan datos en df_log_comentarios_integracion_ccc)"

print(f"--- {val_umbre_ccc_3} ---")
print(error_umbre_ccc_3)

--- ERRORES LOG COMENTARIOS CCC (DÍA ANTERIOR - STATUS != 200) ---
OK - Sin Novedades

### Validación 4 - ERRORES LOG RESOLUTION CCC (DÍA ANTERIOR - STATUS != 200)

Analiza el **log de resoluciones** de la integración CCC para identificar registros del **día anterior** que presentaron **errores técnicos**.

**Lógica Técnica:**
1. Convierte la columna `created_at` a **formato fecha**.
2. Calcula la fecha de **ayer**.
3. Filtra los registros donde **Fecha = Ayer** y **status_code != 200** (o 201 si se considera éxito).

**Retorna:**
* Tabla con las resoluciones fallidas de ayer.
* Variable: `error_umbre_ccc_4`

In [139]:
val_umbre_ccc_4 = 'ERRORES LOG RESOLUTION CCC (DÍA ANTERIOR - STATUS != 200)'
error_umbre_ccc_4 = ""

if 'df_log_cierre_integracion_ccc' in locals() and not df_log_cierre_integracion_ccc.empty:

    df_analisis_resoluciones = df_log_cierre_integracion_ccc.copy()

    if 'created_at' in df_analisis_resoluciones.columns:
        df_analisis_resoluciones['created_at'] = pd.to_datetime(df_analisis_resoluciones['created_at'], errors='coerce')

        fecha_ayer = (datetime.now() - timedelta(days=1)).date()

        mask_fecha = df_analisis_resoluciones['created_at'].dt.date == fecha_ayer

        mask_error = df_analisis_resoluciones['status_code'] != 200

        df_errores_resoluciones = df_analisis_resoluciones[mask_fecha & mask_error].copy()

        cantidad_errores = df_errores_resoluciones.shape[0]

        cols_interes = ['pqrs_number', 'created_at', 'status_code', 'is_successful']
        cols_existentes = [c for c in cols_interes if c in df_errores_resoluciones.columns]

        df_vista_4 = df_errores_resoluciones[cols_existentes].rename(columns={
            'pqrs_number': 'ID_PQRS',
            'created_at': 'Fecha',
            'status_code': 'codigo estado',
            'is_successful': 'Enviado'
        })

        if cantidad_errores > 0:
            html_tabla = df_vista_4.to_html(index=False)
            error_umbre_ccc_4 = f"Total: <b>{cantidad_errores}</b> <br>{html_tabla}"
        else:
            error_umbre_ccc_4 = "OK - Sin Novedades"
    else:
        error_umbre_ccc_4 = "Error: Columna 'created_at' no encontrada en el log"

else:
    error_umbre_ccc_4 = "Sin Validación (Faltan datos en df_log_resoluciones_ccc)"

print(f"--- {val_umbre_ccc_4} ---")
print(error_umbre_ccc_4)

--- ERRORES LOG RESOLUTION CCC (DÍA ANTERIOR - STATUS != 200) ---
OK - Sin Novedades

## Consolidado Errores

In [140]:
from IPython.display import display, HTML

# -----------------------------
# VALIDACIONES UMBRELLA
# -----------------------------
display(HTML("<h2>VALIDACIONES UMBRELLA</h2>"))

# Validación 1
display(HTML(f"VALIDACION 1 {val_umbrella_1}"))
display(HTML(f"{error_umbrella_1}"))

# Validación 2
display(HTML(f"VALIDACION 2 {val_umbrella_2}"))
display(HTML(f"{error_umbrella_2}"))

# Validación 3
display(HTML(f"VALIDACION 3 {val_umbrella_3}"))
display(HTML(f"{error_umbrella_3}"))

# Validación 4
display(HTML(f"VALIDACION 4 {val_umbrella_4}"))
display(HTML(f"{error_umbrella_4}"))

# Validación 5
display(HTML(f"VALIDACION 5 {val_umbrella_5}"))
display(HTML(f"{error_umbrella_5}"))

# Validación 6
display(HTML(f"VALIDACION 6 {val_umbrella_6}"))
display(HTML(f"{error_umbrella_6}"))

# Validación 7
display(HTML(f"VALIDACION 7 {val_umbrella_7}"))
display(HTML(f"{error_umbrella_7}"))

# Validación 8
display(HTML(f"VALIDACION 8 {val_umbrella_8}"))
display(HTML(f"{error_umbrella_8}"))

# Validación 9
display(HTML(f"VALIDACION 9 {val_umbrella_9}"))
display(HTML(f"{error_umbrella_9}"))

# Validación 10
display(HTML(f"VALIDACION 10 {val_umbrella_10}"))
display(HTML(f"{error_umbrella_10}"))

# Validación 11
display(HTML(f"VALIDACION 11 {val_umbrella_11}"))
display(HTML(f"{error_umbrella_11}"))

# Validación 12
display(HTML(f"VALIDACION 12 {val_umbrella_12}"))
display(HTML(f"{error_umbrella_12}"))

# Validación 13
display(HTML(f"VALIDACION 13 {val_umbrella_13}"))
display(HTML(f"{error_umbrella_13}"))

# Validación 14
display(HTML(f"VALIDACION 14 {val_umbrella_14}"))
display(HTML(f"{error_umbrella_14}"))

# Validación 15
display(HTML(f"VALIDACION 15 {val_umbrella_15}"))
display(HTML(f"{error_umbrella_15}"))

# Validación 16
display(HTML(f"VALIDACION 16 {val_umbrella_16}"))
display(HTML(f"{error_umbrella_16}"))

# Validación 17
display(HTML(f"VALIDACION 17 {val_umbrella_17}"))
display(HTML(f"{error_umbrella_17}"))

# Validación 18
display(HTML(f"VALIDACION 18 {val_umbrella_18}"))
display(HTML(f"{error_umbrella_18}"))

# Validación 19
display(HTML(f"VALIDACION 19 {val_umbrella_19}"))
display(HTML(f"{error_umbrella_19}"))

# Validación 20
display(HTML(f"VALIDACION 20 {val_umbrella_20}"))
display(HTML(f"{error_umbrella_20}"))

# Validación 21
display(HTML(f"VALIDACION 21 {val_umbrella_21}"))
display(HTML(f"{error_umbrella_21}"))

# Validación 22
display(HTML(f"VALIDACION 22 {val_umbrella_22}"))
display(HTML(f"{error_umbrella_22}"))

# Validación 23
display(HTML(f"VALIDACION 23 {val_umbrella_23}"))
display(HTML(f"{error_umbrella_23}"))

# Validación 24
display(HTML(f"VALIDACION 24 {val_umbrella_24}"))
display(HTML(f"{error_umbrella_24}"))

# Validación 25
display(HTML(f"VALIDACION 25 {val_umbrella_25}"))
display(HTML(f"{error_umbrella_25}"))

# Validación 26
display(HTML(f"VALIDACION 26 {val_umbrella_26}"))
display(HTML(f"{error_umbrella_26}"))

# Validación 27
display(HTML(f"VALIDACION 27 {val_umbrella_27}"))
display(HTML(f"{error_umbrella_27}"))

# Validación 28
display(HTML(f"VALIDACION 28 {val_umbrella_28}"))
display(HTML(f"{error_umbrella_28}"))


# -----------------------------
# VALIDACIONES UMBRELLA vs DATAWIFI
# -----------------------------
display(HTML("<h2>VALIDACIONES UMBRELLA vs DATAWIFI</h2>"))

# Validación 1
display(HTML(f"VALIDACION 1 {val_umbre_datawifi_1}"))
display(HTML(f"{error_umbre_datawifi_1}"))

# Validación 2
display(HTML(f"VALIDACION 2 {val_umbre_datawifi_2}"))
display(HTML(f"{error_umbre_datawifi_2}"))

# Validación 3
display(HTML(f"VALIDACION 3 {val_umbre_datawifi_3}"))
display(HTML(f"{error_umbre_datawifi_3}"))

# Validación 4
display(HTML(f"VALIDACION 4 {val_umbre_datawifi_4}"))
display(HTML(f"{error_umbre_datawifi_4}"))
# Validación 4_1
display(HTML(f"VALIDACION 4_1 {val_umbre_datawifi_4_1}"))
display(HTML(f"{error_umbre_datawifi_4_1}"))

# Validación 5
display(HTML(f"VALIDACION 5 {val_umbre_datawifi_5}"))
display(HTML(f"{error_umbre_datawifi_5}"))
# Validación 5
display(HTML(f"VALIDACION 5_1 {val_umbre_datawifi_5_1}"))
display(HTML(f"{error_umbre_datawifi_5_1}"))

# Validación 6
display(HTML(f"VALIDACION 6 {val_umbre_datawifi_6}"))
display(HTML(f"{error_umbre_datawifi_6}"))

# Validación 7
display(HTML(f"VALIDACION 7 {val_umbre_datawifi_7}"))
display(HTML(f"{error_umbre_datawifi_7}"))

# Validación 8
display(HTML(f"VALIDACION 8 {val_umbre_datawifi_8}"))
display(HTML(f"{error_umbre_datawifi_8}"))

# Validación 9
display(HTML(f"VALIDACION 9 {val_umbre_datawifi_9}"))
display(HTML(f"{error_umbre_datawifi_9}"))

# Validación 10
display(HTML(f"VALIDACION 10 {val_umbre_datawifi_10}"))
display(HTML(f"{error_umbre_datawifi_10}"))

# Validación 11
display(HTML(f"VALIDACION 11 {val_umbre_datawifi_11}"))
display(HTML(f"{error_umbre_datawifi_11}"))


# -----------------------------
# VALIDACIONES DATAWIFI
# -----------------------------
display(HTML("<h2>VALIDACIONES DATAWIFI</h2>"))

# Validación 1 A 6
display(HTML(f"{val_datawifi_1} : <b>{error_datawifi_1}</b>"))
display(HTML(f"{val_datawifi_2} : <b>{error_datawifi_2}</b>"))
display(HTML(f"{val_datawifi_3} : <b>{error_datawifi_3}</b>"))
display(HTML(f"{val_datawifi_4} : <b>{error_datawifi_4}</b>"))
display(HTML(f"{val_datawifi_5} : <b>{error_datawifi_5}</b>"))
display(HTML(f"{val_datawifi_6} : <b>{error_datawifi_6}</b>"))

# Validación 7
display(HTML(f"VALIDACION 7 {val_datawifi_7}"))
display(HTML(f"{error_datawifi_7}"))

# Validación 8
display(HTML(f"VALIDACION 8 {val_datawifi_8}"))
display(HTML(f"{error_datawifi_8}"))

# Validación 9
display(HTML(f"VALIDACION 9 {val_datawifi_9}"))
display(HTML(f"{error_datawifi_9}"))

# Validación 10
display(HTML(f"VALIDACION 10 {val_datawifi_10}"))
display(HTML(f"{error_datawifi_10}"))

# Validación 11
display(HTML(f"VALIDACION 11 {val_datawifi_11}"))
display(HTML(f"{error_datawifi_11}"))

# Validación 12
display(HTML(f"VALIDACION 12 {val_datawifi_12}"))
display(HTML(f"{error_datawifi_12}"))

# Validación 13
display(HTML(f"VALIDACION 13 {val_datawifi_13}"))
display(HTML(f"{error_datawifi_13}"))


# -----------------------------
# VALIDACIONES UMBRELLA Y CCC
# -----------------------------
display(HTML("<h2>VALIDACIONES UMBRELLA Y CCC</h2>"))

# Validación 1
display(HTML(f"VALIDACION 1 {val_umbre_ccc_1}"))
display(HTML(f"{error_umbre_ccc_1}"))

# Validación 2
display(HTML(f"VALIDACION 2 {val_umbre_ccc_2}"))
display(HTML(f"{error_umbre_ccc_2}"))

# Validación 3
display(HTML(f"VALIDACION 3 {val_umbre_ccc_3}"))
display(HTML(f"{error_umbre_ccc_3}"))

# Validación 4
display(HTML(f"VALIDACION 4 {val_umbre_ccc_4}"))
display(HTML(f"{error_umbre_ccc_4}"))

## Envío Correo

In [141]:
nombres = ['Victor Campos', 'Liseth Guzmán', 'William Mora']

while True:
    for i, nombre in enumerate(nombres, 1):
        print(f"{i}. {nombre}")

    try:
        opcion = int(input("Seleccione una opcion: "))
    except ValueError:
        print("Entrada no válida. Por favor, ingrese un número.\n")
        continue

    if 1 <= opcion <= len(nombres):
        nombre = nombres[opcion - 1]
        print(f"Has seleccionado: {nombre}")
        break  # Salir del bucle cuando se selecciona una opción válida
    else:
        print("Opción no válida, por favor intente de nuevo.\n")

# --- CONFIGURACIÓN DE CORREO ---

# Variable de fecha
hora = datetime.now(pytz.timezone('America/Bogota')).strftime("%H:%M:%S")

# Configuración del servidor SMTP
email_subject = f"Revisiones diarias {FECHA_HOY_DATE}"
sender_email_address = "wsistemasdeinformacion@gmail.com"
receiver_email_address = ["sistemasdeinformacionUT@sky.net.co", "cesar.quinterom@etb.com.co", "nelson.miranda@sky.net.co"]
#receiver_email_address = ["victor.campos@sky.net.co"]
email_smtp = "smtp.gmail.com"
email_password = "fxej nkft pdus xdjy" # Usa tu App Password

# Creación del objeto EmailMessage
message = EmailMessage()

# Configuracion de las cabeceras del email
message['Subject'] = email_subject
message['From'] = sender_email_address
message['To'] = ", ".join(receiver_email_address) # Une la lista de destinatarios

# Creación del cuerpo del correo (HTML con estilos actualizados)
body = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        /* ESTILOS GENERALES */
        body {{
            font-family: 'Arial', sans-serif;
            font-size: 15px;
            color: #333333;
            background-color: #ffffff;
            padding: 20px;
            margin: 0;
        }}

        /* TÍTULO PRINCIPAL */
        h1 {{
            color: #00264d;
            font-size: 28px;
            border-bottom: 3px solid #003366;
            padding-bottom: 15px;
            text-align: center;
            margin-bottom: 30px;
        }}

        /* ESTILO MENÚ PARA SECCIONES (H2) - MODIFICADO A NEGRO */
        h2 {{
            background-color: #000000; /* Fondo Negro para contraste */
            color: #ffffff; /* Letra Blanca */
            font-size: 18px;
            text-align: center; /* Centrado */
            padding: 12px 0; /* Relleno vertical */
            margin-top: 40px; /* Espacio arriba */
            margin-bottom: 20px; /* Espacio abajo */
            text-transform: uppercase;
            letter-spacing: 1px;
            border-radius: 4px;
            width: 100%; /* De lado a lado */
            box-shadow: 0 2px 5px rgba(0,0,0,0.2);
        }}

        /* SUBTÍTULOS (H3) */
        h3 {{
            color: #003366;
            font-size: 16px;
            margin-top: 25px;
            margin-bottom: 8px;
            font-weight: bold;
            border-left: 5px solid #f39c12; /* Pequeño acento naranja */
            padding-left: 10px;
            background-color: #f9f9f9;
            padding-top: 5px;
            padding-bottom: 5px;
        }}

        /* TEXTO Y CONTENIDO */
        p {{
            font-size: 14px;
            color: #444444;
            margin: 5px 0 5px 15px; /* Indentación ligera */
            line-height: 1.5;
        }}

        b {{
            color: #000000;
            font-weight: 700;
        }}

        /* TABLAS - MODIFICADO A ANCHO AUTOMÁTICO */
        table {{
            width: auto; /* Ancho ajustado al contenido */
            border-collapse: collapse;
            margin: 20px 0 20px 10px;
            font-size: 13px;
        }}
        th {{
            background-color: #004080;
            color: white;
            padding: 8px;
            text-align: center;
        }}
        td {{
            padding: 8px;
            border: 1px solid #ddd;
            text-align: center;
        }}
        tr:nth-child(even) {{
            background-color: #f2f2f2;
        }}

        /* PIE DE PÁGINA */
        .footer {{
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #ccc;
            font-size: 13px;
            color: #777;
            text-align: center;
        }}
    </style>
</head>
<body>

    <h1>VALIDACIONES DIARIAS {FECHA_HOY_DATE}</h1>

    <h2>VALIDACIONES UMBRELLA</h2>

    <h3>VALIDACIÓN 1 <br>{val_umbrella_1}</br></h3>
    <p>{error_umbrella_1}</p>

    <h3>VALIDACIÓN 2 <br>{val_umbrella_2}</br></h3>
    <p>{error_umbrella_2}</p>

    <h3>VALIDACIÓN 3 <br>{val_umbrella_3}</br></h3>
    <p>{error_umbrella_3}</p>

    <h3>VALIDACIÓN 4 <br>{val_umbrella_4}</br></h3>
    <p>{error_umbrella_4}</p>

    <h3>VALIDACIÓN 5 <br>{val_umbrella_5}</br></h3>
    <p>{error_umbrella_5}</p>

    <h3>VALIDACIÓN 6 <br>{val_umbrella_6}</br></h3>
    <p>{error_umbrella_6}</p>

    <h3>VALIDACIÓN 7 <br>{val_umbrella_7}</br></h3>
    <p>{error_umbrella_7}</p>

    <h3>VALIDACIÓN 8 <br>{val_umbrella_8}</br></h3>
    <p>{error_umbrella_8}</p>

    <h3>VALIDACIÓN 9 <br>{val_umbrella_9}</br></h3>
    <p>{error_umbrella_9}</p>

    <h3>VALIDACIÓN 10 <br>{val_umbrella_10}</br></h3>
    <p>{error_umbrella_10}</p>

    <h3>VALIDACIÓN 11 <br>{val_umbrella_11}</br></h3>
    <p>{error_umbrella_11}</p>

    <h3>VALIDACIÓN 12 <br>{val_umbrella_12}</br></h3>
    <p>{error_umbrella_12}</p>

    <h3>VALIDACIÓN 13 <br>{val_umbrella_13}</br></h3>
    <p>{error_umbrella_13}</p>

    <h3>VALIDACIÓN 14 <br>{val_umbrella_14}</br></h3>
    <p>{error_umbrella_14}</p>

    <h3>VALIDACIÓN 15 <br>{val_umbrella_15}</br></h3>
    <p>{error_umbrella_15}</p>

    <h3>VALIDACIÓN 16 <br>{val_umbrella_16}</br></h3>
    <p>{error_umbrella_16}</p>

    <h3>VALIDACIÓN 17 <br>{val_umbrella_17}</br></h3>
    <p>{error_umbrella_17}</p>

    <h3>VALIDACIÓN 18 <br>{val_umbrella_18}</br></h3>
    <p>{error_umbrella_18}</p>

    <h3>VALIDACIÓN 19 <br>{val_umbrella_19}</br></h3>
    <p>{error_umbrella_19}</p>

    <h3>VALIDACIÓN 20 <br>{val_umbrella_20}</br></h3>
    <p>{error_umbrella_20}</p>

    <h3>VALIDACIÓN 21 <br>{val_umbrella_21}</br></h3>
    <p>{error_umbrella_21}</p>

    <h3>VALIDACIÓN 22 <br>{val_umbrella_22}</br></h3>
    <p>{error_umbrella_22}</p>

    <h3>VALIDACIÓN 23 <br>{val_umbrella_23}</br></h3>
    <p>{error_umbrella_23}</p>

    <h3>VALIDACIÓN 24 <br>{val_umbrella_24}</br></h3>
    <p>{error_umbrella_24}</p>

    <h3>VALIDACIÓN 25 <br>{val_umbrella_25}</br></h3>
    <p>{error_umbrella_25}</p>

    <h3>VALIDACIÓN 26 <br>{val_umbrella_26}</br></h3>
    <p>{error_umbrella_26}</p>

    <h3>VALIDACIÓN 27 <br>{val_umbrella_27}</br></h3>
    <p>{error_umbrella_27}</p>

    <h3>VALIDACIÓN 28 <br>{val_umbrella_28}</br></h3>
    <p>{error_umbrella_28}</p>

    <h2>VALIDACIONES UMBRELLA vs DATAWIFI</h2>

    <h3>VALIDACIÓN 1 <br>{val_umbre_datawifi_1}</br></h3>
    <p> {error_umbre_datawifi_1}</p>

    <h3>VALIDACIÓN 2 <br>{val_umbre_datawifi_2}</br></h3>
    <p> {error_umbre_datawifi_2}</p>

    <h3>VALIDACIÓN 3 <br>{val_umbre_datawifi_3}</br></h3>
    <p> {error_umbre_datawifi_3}</p>

    <h3>VALIDACIÓN 4 <br>{val_umbre_datawifi_4}</br></h3>
    <p> {error_umbre_datawifi_4}</p>
    <h3>VALIDACIÓN 4_1 <br>{val_umbre_datawifi_4_1}</br></h3>
    <p> {error_umbre_datawifi_4_1}</p>


    <h3>VALIDACIÓN 5 <br>{val_umbre_datawifi_5}</br></h3>
    <p> {error_umbre_datawifi_5}</p>
    <h3>VALIDACIÓN 5_1 <br>{val_umbre_datawifi_5_1}</br></h3>
    <p> {error_umbre_datawifi_5_1}</p>

    <h3>VALIDACIÓN 6 <br>{val_umbre_datawifi_6}</br></h3>
    <p> {error_umbre_datawifi_6}</p>

    <h3>VALIDACIÓN 7 <br>{val_umbre_datawifi_7}</br></h3>
    <p> {error_umbre_datawifi_7}</p>

    <h3>VALIDACIÓN 8 <br>{val_umbre_datawifi_8}</br></h3>
    <p> {error_umbre_datawifi_8}</p>

    <h3>VALIDACIÓN 9 <br>{val_umbre_datawifi_9}</br></h3>
    <p> {error_umbre_datawifi_9}</p>

    <h3>VALIDACIÓN 10 <br>{val_umbre_datawifi_10}</br></h3>
    <p> {error_umbre_datawifi_10}</p>

    <h3>VALIDACIÓN 11 <br>{val_umbre_datawifi_11}</br></h3>
    <p> {error_umbre_datawifi_11}</p>

    <h2>VALIDACIONES DATAWIFI</h2>

    <h3>VALIDACIÓN 1, 2, 3, 4, 5 Y 6</h3>
    <p><b>{val_datawifi_1}</b> {error_datawifi_1}</p>
    <p><b>{val_datawifi_2}</b> {error_datawifi_2}</p>
    <p><b>{val_datawifi_3}</b> {error_datawifi_3}</p>
    <p><b>{val_datawifi_4}</b> {error_datawifi_4}</p>
    <p><b>{val_datawifi_5}</b> {error_datawifi_5}</p>
    <p><b>{val_datawifi_6}</b> {error_datawifi_6}</p>

    <h3>VALIDACIÓN 7 <br>{val_datawifi_7}</br></h3>
    <p> {error_datawifi_7}</p>

    <h3>VALIDACIÓN 8 <br>{val_datawifi_8}</br></h3>
    <p> {error_datawifi_8}</p>

    <h3>VALIDACIÓN 9 <br>{val_datawifi_9}</br></h3>
    <p> {error_datawifi_9}</p>

    <h3>VALIDACIÓN 10 <br>{val_datawifi_10}</br></h3>
    <p> {error_datawifi_10}</p>

    <h3>VALIDACIÓN 11 <br>{val_datawifi_11}</br></h3>
    <p> {error_datawifi_11}</p>

    <h3>VALIDACIÓN 12 <br>{val_datawifi_12}</br></h3>
    <p> {error_datawifi_12}</p>

    <h3>VALIDACIÓN 13 <br>{val_datawifi_13}</br></h3>
    <p> {error_datawifi_13}</p>


    <h2>VALIDACIONES UMBRELLA Y CCC</h2>

    <h3>VALIDACIÓN 1 <br>{val_umbre_ccc_1}</br></h3>
    <p> {error_umbre_ccc_1}</p>

    <h3>VALIDACIÓN 2 <br>{val_umbre_ccc_2}</br></h3>
    <p> {error_umbre_ccc_2}</p>

    <h3>VALIDACIÓN 3 <br>{val_umbre_ccc_3}</br></h3>
    <p> {error_umbre_ccc_3}</p>

    <h3>VALIDACIÓN 4 <br>{val_umbre_ccc_4}</br></h3>
    <p> {error_umbre_ccc_4}</p>


    <div class="footer">
        <p>Proceso automatizado ejecutado por: <b>{nombre}</b> a las {hora}</p>
    </div>

</body>
</html>
"""

# Agregar el contenido HTML al mensaje
message.add_alternative(body, subtype='html')

# --- ENVÍO DE CORREO ---
try:
    # Variable server guarda configuracion del protocolo y puerto
    server = smtplib.SMTP(email_smtp, '587')

    # Identificación del cliente en el servidor SMTP
    server.ehlo()

    # Añade seguridad a la conexión
    server.starttls()

    # Inicio de sesion con las credenciales
    server.login(sender_email_address, email_password)

    # Envio correo
    server.send_message(message)
    print("\n✅ Correo enviado exitosamente.")

except Exception as e:
    print(f"\n❌ Error al enviar el correo: {e}")

finally:
    # Cerrar conexión con el servidor
    if 'server' in locals() and server:
        server.quit()

1. Victor Campos
2. Liseth Guzmán
3. William Mora
Seleccione una opcion: 2
Has seleccionado: Liseth Guzmán

✅ Correo enviado exitosamente.